window.MULLER_RUTA_LEVELS = [
  // ── A1 ──
  { id:'a1-1', title:'Nivel 1 · Primeros pasos', badge:'A1.1', lessons:[
    { id:'a1-1-l1', title:'Saludos y presentación', topic:'presentacion', rewardCoins:10, rewardXp:15,
      grammarTip:'El verbo conjugado va en 2ª posición: Ich bin Ana.',
      phrases:[{de:'Ich bin Ana.',es:'Soy Ana.'},{de:'Ich komme aus Spanien.',es:'Vengo de España.'},{de:'Ich lerne Deutsch.',es:'Aprendo alemán.'}],
      exerciseType:'fill', exerciseQ:'Ich ___ Ana.', exerciseA:'bin' },
    { id:'a1-1-l2', title:'Artículos básicos', topic:'clase', rewardCoins:10, rewardXp:15,
      grammarTip:'Memoriza sustantivo + artículo: der Tisch, die Tür, das Buch.',
      phrases:[{de:'Das ist ein Buch.',es:'Eso es un libro.'},{de:'Die Tür ist offen.',es:'La puerta está abierta.'}],
      exerciseType:'fill', exerciseQ:'Das ist ___ Buch.', exerciseA:'ein' },
    { id:'a1-1-l3', title:'Verbos básicos', topic:'verbos', rewardCoins:10, rewardXp:15,
      grammarTip:'sein y haben: Ich bin, du bist, er ist / ich habe, du hast, er hat.',
      phrases:[{de:'Ich habe einen Hund.',es:'Tengo un perro.'},{de:'Bist du müde?',es:'¿Estás cansado?'}],
      exerciseType:'fill', exerciseQ:'Ich ___ einen Hund.', exerciseA:'habe' }
  ]},
  { id:'a1-2', title:'Nivel 2 · Primera rutina', badge:'A1.2', lessons:[
    { id:'a1-2-l1', title:'Hora y días', topic:'rutina', rewardCoins:12, rewardXp:18,
      grammarTip:'"Um acht Uhr" = a las ocho. Días con mayúscula: Montag.',
      phrases:[{de:'Ich stehe um sieben Uhr auf.',es:'Me levanto a las siete.'},{de:'Am Montag gehe ich zur Arbeit.',es:'El lunes voy al trabajo.'}],
      exerciseType:'fill', exerciseQ:'Ich stehe ___ sieben Uhr auf.', exerciseA:'um' },
    { id:'a1-2-l2', title:'Comida y bebida', topic:'alimentos', rewardCoins:12, rewardXp:18,
      grammarTip:'"Ich möchte" + Akkusativ: Ich möchte einen Kaffee.',
      phrases:[{de:'Ich möchte einen Kaffee.',es:'Quiero un café.'},{de:'Was isst du gern?',es:'¿Qué te gusta comer?'}],
      exerciseType:'fill', exerciseQ:'Ich möchte ___ Kaffee.', exerciseA:'einen' }
  ]},
  { id:'a1-3', title:'Nivel 3 · Cuerpo y ciudad', badge:'A1.3', lessons:[
    { id:'a1-3-l1', title:'Partes del cuerpo', topic:'cuerpo', rewardCoins:12, rewardXp:18,
      grammarTip:'Los artículos: der Kopf (m), die Hand (f), das Auge (n).',
      phrases:[{de:'Der Kopf tut weh.',es:'La cabeza duele.'},{de:'Ich wasche mir die Hände.',es:'Me lavo las manos.'}],
      exerciseType:'fill', exerciseQ:'Der ___ tut weh.', exerciseA:'Kopf' },
    { id:'a1-3-l2', title:'En la ciudad', topic:'ciudad', rewardCoins:12, rewardXp:18,
      grammarTip:'"Wo?" + Dativ: in der Stadt, im Park.',
      phrases:[{de:'Das Kino ist in der Stadt.',es:'El cine está en la ciudad.'},{de:'Der Park ist schön.',es:'El parque es bonito.'}],
      exerciseType:'fill', exerciseQ:'Das Kino ist in ___ Stadt.', exerciseA:'der' }
  ]},
  { id:'a1-4', title:'Nivel 4 · Casa y cocina', badge:'A1.4', lessons:[
    { id:'a1-4-l1', title:'En la cocina', topic:'cocina', rewardCoins:12, rewardXp:18,
      grammarTip:'Artículo correcto: der Löffel, die Gabel, das Messer.',
      phrases:[{de:'Der Löffel ist auf dem Tisch.',es:'La cuchara está en la mesa.'},{de:'Die Gabel ist sauber.',es:'El tenedor está limpio.'}],
      exerciseType:'choose', exerciseQ:'___ Teller ist rund.', exerciseA:'Der',
      options:['Der','Die','Das'] }
  ]},
  // ── A2 ──
  { id:'a2-1', title:'Nivel 5 · Viajes y transporte', badge:'A2.1', lessons:[
    { id:'a2-1-l1', title:'En la estación', topic:'transporte', rewardCoins:15, rewardXp:22,
      grammarTip:'"Ich fahre mit dem Zug" = medio de transporte en Dativ.',
      phrases:[{de:'Ich fahre mit dem Zug nach Berlin.',es:'Voy en tren a Berlín.'},{de:'Der Zug hat Verspätung.',es:'El tren lleva retraso.'}],
      exerciseType:'fill', exerciseQ:'Ich fahre mit ___ Zug.', exerciseA:'dem' },
    { id:'a2-1-l2', title:'En el hotel', topic:'viajes', rewardCoins:15, rewardXp:22,
      grammarTip:'"Ich möchte ein Zimmer reservieren" = verbos modales corteses.',
      phrases:[{de:'Ich möchte ein Zimmer reservieren.',es:'Quiero reservar una habitación.'}],
      exerciseType:'fill', exerciseQ:'Ich möchte ein ___ reservieren.', exerciseA:'Zimmer' }
  ]},
  { id:'a2-2', title:'Nivel 6 · Salud y emociones', badge:'A2.2', lessons:[
    { id:'a2-2-l1', title:'En el médico', topic:'salud', rewardCoins:15, rewardXp:22,
      grammarTip:'"Ich habe Schmerzen in..." + Dativ.',
      phrases:[{de:'Ich habe Kopfschmerzen.',es:'Tengo dolor de cabeza.'},{de:'Der Arzt verschreibt Medikamente.',es:'El médico receta medicamentos.'}],
      exerciseType:'fill', exerciseQ:'Ich habe ___ Schmerzen.', exerciseA:'Kopf' },
    { id:'a2-2-l2', title:'Sentimientos', topic:'emociones', rewardCoins:15, rewardXp:22,
      grammarTip:'"sich fühlen" = sentirse. Ich fühle mich gut.',
      phrases:[{de:'Ich fühle mich heute gut.',es:'Hoy me siento bien.'},{de:'Bist du traurig?',es:'¿Estás triste?'}],
      exerciseType:'fill', exerciseQ:'Ich fühle ___ gut.', exerciseA:'mich' }
  ]},
  { id:'a2-3', title:'Nivel 7 · Ropa y tecnología', badge:'A2.3', lessons:[
    { id:'a2-3-l1', title:'La ropa', topic:'ropa', rewardCoins:15, rewardXp:22,
      grammarTip:'"Ich trage ein Kleid" = llevo un vestido. Anprobieren = probarse.',
      phrases:[{de:'Ich trage heute ein Kleid.',es:'Hoy llevo un vestido.'},{de:'Die Jacke ist zu teuer.',es:'La chaqueta es muy cara.'}],
      exerciseType:'choose', exerciseQ:'___ Kleid ist rot.', exerciseA:'Das',
      options:['Der','Die','Das'] },
    { id:'a2-3-l2', title:'Tecnología', topic:'tecnologia', rewardCoins:15, rewardXp:22,
      grammarTip:'Verbos separables: "Ich lade das Handy auf."',
      phrases:[{de:'Ich lade das Handy auf.',es:'Cargo el móvil.'},{de:'Der Drucker funktioniert nicht.',es:'La impresora no funciona.'}],
      exerciseType:'fill', exerciseQ:'Ich lade das Handy ___.', exerciseA:'auf' }
  ]},
  { id:'a2-4', title:'Nivel 8 · Personalidad', badge:'A2.4', lessons:[
    { id:'a2-4-l1', title:'Adjetivos de carácter', topic:'personalidad', rewardCoins:15, rewardXp:22,
      grammarTip:'Adjetivos después de "ist" se quedan igual: Er ist nett.',
      phrases:[{de:'Er ist sehr freundlich.',es:'Él es muy amable.'},{de:'Mein Bruder ist mutig.',es:'Mi hermano es valiente.'}],
      exerciseType:'choose', exerciseQ:'Sie ist sehr ___.', exerciseA:'nett',
      options:['nett','netter','nette'] }
  ]},
  // ── B1 ──
  { id:'b1-1', title:'Nivel 9 · Trabajo y economía', badge:'B1.1', lessons:[
    { id:'b1-1-l1', title:'Preposiciones genitivo', topic:'preposiciones', rewardCoins:18, rewardXp:26,
      grammarTip:'trotz, wegen, während, statt + Genitiv.',
      phrases:[{de:'Wegen des Regens bleibe ich zu Hause.',es:'Por la lluvia me quedo en casa.'},{de:'Trotz des Geldes ist er unzufrieden.',es:'A pesar del dinero está insatisfecho.'}],
      exerciseType:'fill', exerciseQ:'Wegen ___ Regens bleibe ich.', exerciseA:'des' },
    { id:'b1-1-l2', title:'Oraciones con weil/dass', topic:'conectores', rewardCoins:18, rewardXp:26,
      grammarTip:'"weil" manda el verbo al final: Ich lerne, weil ich reisen möchte.',
      phrases:[{de:'Ich lerne, weil ich reisen möchte.',es:'Estudio porque quiero viajar.'},{de:'Er sagt, dass er krank ist.',es:'Él dice que está enfermo.'}],
      exerciseType:'fill', exerciseQ:'Ich lerne, weil ich reisen ___.', exerciseA:'möchte' }
  ]},
  { id:'b1-2', title:'Nivel 10 · Sociedad y cultura', badge:'B1.2', lessons:[
    { id:'b1-2-l1', title:'Conectores adversativos', topic:'conectores', rewardCoins:18, rewardXp:26,
      grammarTip:'"obwohl" manda el verbo al final: Obwohl es regnet, gehe ich spazieren.',
      phrases:[{de:'Obwohl es regnet, gehe ich spazieren.',es:'Aunque llueve, salgo a pasear.'}],
      exerciseType:'fill', exerciseQ:'Obwohl es ___, gehe ich spazieren.', exerciseA:'regnet' },
    { id:'b1-2-l2', title:'Konnektoren C1', topic:'conectores', rewardCoins:18, rewardXp:26,
      grammarTip:'"nichtsdestotrotz", "insofern", "folglich".',
      phrases:[{de:'Nichtsdestotrotz bleiben wir optimistisch.',es:'No obstante, seguimos optimistas.'}],
      exerciseType:'fill', exerciseQ:'Nichtsdestotrotz ___ wir optimistisch.', exerciseA:'bleiben' }
  ]},
  { id:'b1-3', title:'Nivel 11 · Deporte y ocio', badge:'B1.3', lessons:[
    { id:'b1-3-l1', title:'Konjunktiv II', topic:'gramatica', rewardCoins:18, rewardXp:26,
      grammarTip:'"Ich hätte gern...", "Könnten Sie...?" para peticiones corteses.',
      phrases:[{de:'Ich hätte gern einen Kaffee.',es:'Me gustaría un café.'},{de:'Könnten Sie mir helfen?',es:'¿Podría ayudarme?'}],
      exerciseType:'fill', exerciseQ:'Ich ___ gern einen Kaffee.', exerciseA:'hätte' }
  ]},
  { id:'b1-4', title:'Nivel 12 · Análisis y opinión', badge:'B1.4', lessons:[
    { id:'b1-4-l1', title:'Estructurar opiniones', topic:'opinion', rewardCoins:18, rewardXp:26,
      grammarTip:'"meiner Meinung nach" al inicio: Meiner Meinung nach ist das falsch.',
      phrases:[{de:'Meiner Meinung nach ist das falsch.',es:'En mi opinión, eso está mal.'}],
      exerciseType:'fill', exerciseQ:'Meiner ___ nach ist das falsch.', exerciseA:'Meinung' }
  ]},
  // ── B2 ──
  { id:'b2-1', title:'Nivel 13 · Economía', badge:'B2.1', lessons:[
    { id:'b2-1-l1', title:'Pasiva', topic:'gramatica', rewardCoins:22, rewardXp:32,
      grammarTip:'Pasiva: "würden" + participio. El agente con "von".',
      phrases:[{de:'Das Haus wird gebaut.',es:'La casa está siendo construida.'},{de:'Der Vertrag wurde unterschrieben.',es:'El contrato fue firmado.'}],
      exerciseType:'fill', exerciseQ:'Das Haus ___ gebaut.', exerciseA:'wird' },
    { id:'b2-1-l2', title:'Pasiva alternativas', topic:'gramatica', rewardCoins:22, rewardXp:32,
      grammarTip:'"man" alternativo a pasiva: Man sagt, dass...',
      phrases:[{de:'Man sagt, dass Deutsch schwer ist.',es:'Se dice que el alemán es difícil.'}],
      exerciseType:'fill', exerciseQ:'___ sagt, dass Deutsch schwer ist.', exerciseA:'Man' }
  ]},
  { id:'b2-2', title:'Nivel 14 · Relaciones', badge:'B2.2', lessons:[
    { id:'b2-2-l1', title:'Expresiones idiomáticas', topic:'expresiones', rewardCoins:25, rewardXp:36,
      grammarTip:'"ins Schwarze treffen" (dar en el clavo), "nur Bahnhof verstehen" (no entender nada).',
      phrases:[{de:'Du hast ins Schwarze getroffen!',es:'¡Diste en el clavo!'},{de:'Ich verstehe nur Bahnhof.',es:'No entiendo nada.'}],
      exerciseType:'fill', exerciseQ:'Ich verstehe nur ___.', exerciseA:'Bahnhof' },
    { id:'b2-2-l2', title:'Konjunktiv I', topic:'gramatica', rewardCoins:25, rewardXp:36,
      grammarTip:'Discurso indirecto: Er sagte, er habe keine Zeit.',
      phrases:[{de:'Er sagte, er habe keine Zeit.',es:'Dijo que no tenía tiempo.'}],
      exerciseType:'fill', exerciseQ:'Er sagte, er ___ keine Zeit.', exerciseA:'habe' }
  ]},
  { id:'b2-3', title:'Nivel 15 · Medios', badge:'B2.3', lessons:[
    { id:'b2-3-l1', title:'Relativsätze', topic:'gramatica', rewardCoins:25, rewardXp:36,
      grammarTip:'Pronombres relativos: der/die/das/dem/denen según función.',
      phrases:[{de:'Der Mann, der dort steht, ist mein Chef.',es:'El hombre que está allí es mi jefe.'}],
      exerciseType:'fill', exerciseQ:'Der Mann, ___ dort steht, ist mein Chef.', exerciseA:'der' }
  ]},
  { id:'b2-4', title:'Nivel 16 · Investigación', badge:'B2.4', lessons:[
    { id:'b2-4-l1', title:'Nominalisierung', topic:'estilo', rewardCoins:25, rewardXp:36,
      grammarTip:'Convertir verbos en sustantivos: "die Entscheidung treffen".',
      phrases:[{de:'Die Entscheidung wurde getroffen.',es:'Se tomó la decisión.'}],
      exerciseType:'fill', exerciseQ:'Die ___ wurde getroffen.', exerciseA:'Entscheidung' }
  ]},
  // ── C1 ──
  { id:'c1-1', title:'Nivel 17 · Precisión formal', badge:'C1.1', lessons:[
    { id:'c1-1-l1', title:'Conectores avanzados', topic:'conectores', rewardCoins:30, rewardXp:42,
      grammarTip:'"insofern", "folglich", "nichtsdestotrotz", "demzufolge".',
      phrases:[{de:'Demzufolge müssen wir handeln.',es:'Por consiguiente, debemos actuar.'}],
      exerciseType:'fill', exerciseQ:'Demzufolge ___ wir handeln.', exerciseA:'müssen' },
    { id:'c1-1-l2', title:'Argumentación', topic:'argumentacion', rewardCoins:30, rewardXp:42,
      grammarTip:'Estructura: These → Argument → Beispiel → Schluss.',
      phrases:[{de:'Es lässt sich nicht leugnen, dass...',es:'No se puede negar que...'}],
      exerciseType:'fill', exerciseQ:'Es lässt sich nicht ___, dass...', exerciseA:'leugnen' }
  ]},
  { id:'c1-2', title:'Nivel 18 · Maestría', badge:'C1.2', lessons:[
    { id:'c1-2-l1', title:'Matiz y precisión', topic:'estilo', rewardCoins:35, rewardXp:48,
      grammarTip:'Diferenciar "abstrakt/konkret", "spezifisch/generell", "kausal/kontingent".',
      phrases:[{de:'Diese These ist zu abstrakt.',es:'Esta tesis es demasiado abstracta.'}],
      exerciseType:'fill', exerciseQ:'Diese ___ ist zu abstrakt.', exerciseA:'These' },
    { id:'c1-2-l2', title:'Síntesis', topic:'sintesis', rewardCoins:35, rewardXp:48,
      grammarTip:'Recapitular con "zusammenfassend", "inwiefern", "im Großen und Ganzen".',
      phrases:[{de:'Zusammenfassend lässt sich sagen, dass...',es:'En resumen, se puede decir que...'}],
      exerciseType:'fill', exerciseQ:'___ lässt sich sagen, dass...', exerciseA:'Zusammenfassend' }
  ]}
,
    { id:'c1-2-l3', title:'Discurso', topic:'discurso', rewardCoins:35, rewardXp:48,
      grammarTip:'Erweiterte Partizipialattribute: die von den Wissenschaftlern durchgeführte Untersuchung.',
      phrases:[{de:'die Abstraktion spielt eine zentrale Rolle.',es:'El/la abstracción juega un papel central.'},{de:'Die Bedeutung der Abstraktions ist offensichtlich.',es:'La importancia de abstracción es obvia.'},{de:'Wir müssen die Abstraktion berücksichtigen.',es:'Debemos considerar abstracción.'},{de:'die Konkretisierung spielt eine zentrale Rolle.',es:'El/la concreción juega un papel central.'},{de:'Die Bedeutung der Konkretisierungs ist offensichtlich.',es:'La importancia de concreción es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Abstraktion' },
    { id:'c1-2-l4', title:'Ensayo', topic:'ensayo', rewardCoins:35, rewardXp:48,
      grammarTip:'Satzgefüge mit mehrfacher Einbettung: Verschachtelung von Nebensätzen.',
      phrases:[{de:'die Spezifizierung spielt eine zentrale Rolle.',es:'El/la especificación juega un papel central.'},{de:'Die Bedeutung der Spezifizierungs ist offensichtlich.',es:'La importancia de especificación es obvia.'},{de:'Wir müssen die Spezifizierung berücksichtigen.',es:'Debemos considerar especificación.'},{de:'die Generalisierung spielt eine zentrale Rolle.',es:'El/la generalización juega un papel central.'},{de:'Die Bedeutung der Generalisierungs ist offensichtlich.',es:'La importancia de generalización es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Spezifizierung ist gut.', exerciseA:'Die',
      options:['Der','Die','Das'], },
    { id:'c1-2-l5', title:'Crítica literaria', topic:'critica-literaria', rewardCoins:35, rewardXp:48,
      grammarTip:'Cleft-Sätze: Was mich betrifft, so...; Was...angeht, so...',
      phrases:[{de:'die Typisierung spielt eine zentrale Rolle.',es:'El/la tipificación juega un papel central.'},{de:'Die Bedeutung der Typisierungs ist offensichtlich.',es:'La importancia de tipificación es obvia.'},{de:'Wir müssen die Typisierung berücksichtigen.',es:'Debemos considerar tipificación.'},{de:'die Klassifizierung spielt eine zentrale Rolle.',es:'El/la clasificación juega un papel central.'},{de:'Die Bedeutung der Klassifizierungs ist offensichtlich.',es:'La importancia de clasificación es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Typisierung"?', exerciseA:'Typisierungen' },
    { id:'c1-2-l6', title:'Abstracto', topic:'abstracto', rewardCoins:35, rewardXp:48,
      grammarTip:'Funktionsverbgefüge wissenschaftlich: einer Analyse unterziehen, in Betracht kommen.',
      phrases:[{de:'die Systematisierung spielt eine zentrale Rolle.',es:'El/la sistematización juega un papel central.'},{de:'Die Bedeutung der Systematisierungs ist offensichtlich.',es:'La importancia de sistematización es obvia.'},{de:'Wir müssen die Systematisierung berücksichtigen.',es:'Debemos considerar sistematización.'},{de:'die Strukturierung spielt eine zentrale Rolle.',es:'El/la estructuración juega un papel central.'},{de:'Die Bedeutung der Strukturierungs ist offensichtlich.',es:'La importancia de estructuración es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "sistematización"', exerciseA:'Systematisierung' },
    { id:'c1-2-l7', title:'Conceptual', topic:'conceptual', rewardCoins:35, rewardXp:48,
      grammarTip:'Distanzstellung: Er hat das Buch, das er gestern gekauft hatte, gelesen.',
      phrases:[{de:'die Koordination spielt eine zentrale Rolle.',es:'El/la coordinación juega un papel central.'},{de:'Die Bedeutung der Koordinations ist offensichtlich.',es:'La importancia de coordinación es obvia.'},{de:'Wir müssen die Koordination berücksichtigen.',es:'Debemos considerar coordinación.'},{de:'die Kooperation spielt eine zentrale Rolle.',es:'El/la cooperación juega un papel central.'},{de:'Die Bedeutung der Kooperations ist offensichtlich.',es:'La importancia de cooperación es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Koordination"', exerciseA:'coordinación' },
    { id:'c1-2-l8', title:'Formal', topic:'formal', rewardCoins:35, rewardXp:48,
      grammarTip:'Korrelat "es" vor Nebensätzen: Es ist erstaunlich, dass... Es kommt darauf an, ob...',
      phrases:[{de:'die Interaktion spielt eine zentrale Rolle.',es:'El/la interacción juega un papel central.'},{de:'Die Bedeutung der Interaktions ist offensichtlich.',es:'La importancia de interacción es obvia.'},{de:'Wir müssen die Interaktion berücksichtigen.',es:'Debemos considerar interacción.'},{de:'die Partizipation spielt eine zentrale Rolle.',es:'El/la participación juega un papel central.'},{de:'Die Bedeutung der Partizipations ist offensichtlich.',es:'La importancia de participación es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "interacción"', exerciseA:'Interaktion' },
    { id:'c1-1-l3', title:'Deducción', topic:'deduccion', rewardCoins:30, rewardXp:42,
      grammarTip:'Differenzierte Kausalität: aufgrund, infolge, mangels, kraft, zwecks + Genitiv.',
      phrases:[{de:'die Konsequenz spielt eine zentrale Rolle.',es:'El/la consecuencia juega un papel central.'},{de:'Die Bedeutung der Konsequenzs ist offensichtlich.',es:'La importancia de consecuencia es obvia.'},{de:'Wir müssen die Konsequenz berücksichtigen.',es:'Debemos considerar consecuencia.'},{de:'die Implikation spielt eine zentrale Rolle.',es:'El/la implicación juega un papel central.'},{de:'Die Bedeutung der Implikations ist offensichtlich.',es:'La importancia de implicación es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Konsequenz' },
    { id:'c1-1-l4', title:'Contraste', topic:'contraste', rewardCoins:30, rewardXp:42,
      grammarTip:'Module Angaben: erwartungsgemäß, planmäßig, notfalls, gegebenenfalls, erforderlichenfalls.',
      phrases:[{de:'die Bedingung spielt eine zentrale Rolle.',es:'El/la condición juega un papel central.'},{de:'Die Bedeutung der Bedingungs ist offensichtlich.',es:'La importancia de condición es obvia.'},{de:'Wir müssen die Bedingung berücksichtigen.',es:'Debemos considerar condición.'},{de:'die Grundlage spielt eine zentrale Rolle.',es:'El/la base juega un papel central.'},{de:'Die Bedeutung der Grundlages ist offensichtlich.',es:'La importancia de base es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Bedingung ist gut.', exerciseA:'Die',
      options:['Der','Die','Das'], },
    { id:'c1-1-l5', title:'Causalidad', topic:'causalidad', rewardCoins:30, rewardXp:42,
      grammarTip:'Abstrakte Nomen-Verb-Verbindungen: in Abrede stellen, zur Diskussion stellen.',
      phrases:[{de:'die These spielt eine zentrale Rolle.',es:'El/la tesis juega un papel central.'},{de:'Die Bedeutung der Theses ist offensichtlich.',es:'La importancia de tesis es obvia.'},{de:'Wir müssen die These berücksichtigen.',es:'Debemos considerar tesis.'},{de:'die Antithese spielt eine zentrale Rolle.',es:'El/la antítesis juega un papel central.'},{de:'Die Bedeutung der Antitheses ist offensichtlich.',es:'La importancia de antítesis es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "These"?', exerciseA:'Thesen' },
    { id:'c1-1-l6', title:'Matiz', topic:'matiz', rewardCoins:30, rewardXp:42,
      grammarTip:'Nominalstil nominal: seitens, hinsichtlich, bezüglich, betreffs, mangels.',
      phrases:[{de:'das Paradigma spielt eine zentrale Rolle.',es:'El/la paradigma juega un papel central.'},{de:'Die Bedeutung des Paradigmas ist offensichtlich.',es:'La importancia de paradigma es obvia.'},{de:'Wir müssen das Paradigma berücksichtigen.',es:'Debemos considerar paradigma.'},{de:'die Perspektive spielt eine zentrale Rolle.',es:'El/la perspectiva juega un papel central.'},{de:'Die Bedeutung der Perspektives ist offensichtlich.',es:'La importancia de perspectiva es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "paradigma"', exerciseA:'Paradigma' },
    { id:'c1-1-l7', title:'Precisión', topic:'precision', rewardCoins:30, rewardXp:42,
      grammarTip:'Satzwertige Infinitivkonstruktionen: um zu, ohne zu, anstatt zu con sujeto propio.',
      phrases:[{de:'die Dimension spielt eine zentrale Rolle.',es:'El/la dimensión juega un papel central.'},{de:'Die Bedeutung der Dimensions ist offensichtlich.',es:'La importancia de dimensión es obvia.'},{de:'Wir müssen die Dimension berücksichtigen.',es:'Debemos considerar dimensión.'},{de:'der Faktor spielt eine zentrale Rolle.',es:'El/la factor juega un papel central.'},{de:'Die Bedeutung des Faktors ist offensichtlich.',es:'La importancia de factor es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Dimension"', exerciseA:'dimensión' },
    { id:'c1-1-l8', title:'Retórica', topic:'retorica', rewardCoins:30, rewardXp:42,
      grammarTip:'Mehrgliedrige Konnektoren: geschweige denn, umso mehr als, zumal.',
      phrases:[{de:'die Konstante spielt eine zentrale Rolle.',es:'El/la constante juega un papel central.'},{de:'Die Bedeutung der Konstantes ist offensichtlich.',es:'La importancia de constante es obvia.'},{de:'Wir müssen die Konstante berücksichtigen.',es:'Debemos considerar constante.'},{de:'der Parameter spielt eine zentrale Rolle.',es:'El/la parámetro juega un papel central.'},{de:'Die Bedeutung des Parameters ist offensichtlich.',es:'La importancia de parámetro es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "constante"', exerciseA:'Konstante' },
    { id:'b2-4-l2', title:'Estudio', topic:'estudio', rewardCoins:25, rewardXp:36,
      grammarTip:'Schriftlicher Ausdruck: Verfügbarstellung, Inbetriebnahme, Inanspruchnahme.',
      phrases:[{de:'die Forschung spielt eine zentrale Rolle.',es:'El/la investigación juega un papel central.'},{de:'Die Bedeutung der Forschungs ist offensichtlich.',es:'La importancia de investigación es obvia.'},{de:'Wir müssen die Forschung berücksichtigen.',es:'Debemos considerar investigación.'},{de:'die Wissenschaft spielt eine zentrale Rolle.',es:'El/la ciencia juega un papel central.'},{de:'Die Bedeutung der Wissenschafts ist offensichtlich.',es:'La importancia de ciencia es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Forschung' },
    { id:'b2-4-l3', title:'Publicación', topic:'publicacion', rewardCoins:25, rewardXp:36,
      grammarTip:'Zusammengesetzte Substantive: die Forschungseinrichtung, der Wissenschaftsbetrieb.',
      phrases:[{de:'die Technologie spielt eine zentrale Rolle.',es:'El/la tecnología juega un papel central.'},{de:'Die Bedeutung der Technologies ist offensichtlich.',es:'La importancia de tecnología es obvia.'},{de:'Wir müssen die Technologie berücksichtigen.',es:'Debemos considerar tecnología.'},{de:'der Fortschritt spielt eine zentrale Rolle.',es:'El/la progreso juega un papel central.'},{de:'Die Bedeutung des Fortschritts ist offensichtlich.',es:'La importancia de progreso es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Technologie ist gut.', exerciseA:'Die',
      options:['Der','Die','Das'], },
    { id:'b2-4-l4', title:'Congreso', topic:'congreso', rewardCoins:25, rewardXp:36,
      grammarTip:'Fachsprache nominal: Die Durchführung der Analyse erfolgte... (en lugar de analizar)',
      phrases:[{de:'die Innovation spielt eine zentrale Rolle.',es:'El/la innovación juega un papel central.'},{de:'Die Bedeutung der Innovations ist offensichtlich.',es:'La importancia de innovación es obvia.'},{de:'Wir müssen die Innovation berücksichtigen.',es:'Debemos considerar innovación.'},{de:'die Erfindung spielt eine zentrale Rolle.',es:'El/la invento juega un papel central.'},{de:'Die Bedeutung der Erfindungs ist offensichtlich.',es:'La importancia de invento es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Innovation"?', exerciseA:'Innovationen' },
    { id:'b2-4-l5', title:'Experimento', topic:'experimento', rewardCoins:25, rewardXp:36,
      grammarTip:'Textkohärenz: wiederaufgreifen, bezugnehmend auf, in Bezug auf, hinsichtlich.',
      phrases:[{de:'die Theorie spielt eine zentrale Rolle.',es:'El/la teoría juega un papel central.'},{de:'Die Bedeutung der Theories ist offensichtlich.',es:'La importancia de teoría es obvia.'},{de:'Wir müssen die Theorie berücksichtigen.',es:'Debemos considerar teoría.'},{de:'die Praxis spielt eine zentrale Rolle.',es:'El/la práctica juega un papel central.'},{de:'Die Bedeutung der Praxiss ist offensichtlich.',es:'La importancia de práctica es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "teoría"', exerciseA:'Theorie' },
    { id:'b2-4-l6', title:'Datos', topic:'datos', rewardCoins:25, rewardXp:36,
      grammarTip:'Konzessive Satzverbindungen: wenngleich, obschon, obzwar (formal/escrito).',
      phrases:[{de:'das Labor spielt eine zentrale Rolle.',es:'El/la laboratorio juega un papel central.'},{de:'Die Bedeutung des Labors ist offensichtlich.',es:'La importancia de laboratorio es obvia.'},{de:'Wir müssen das Labor berücksichtigen.',es:'Debemos considerar laboratorio.'},{de:'die Methode spielt eine zentrale Rolle.',es:'El/la método juega un papel central.'},{de:'Die Bedeutung der Methodes ist offensichtlich.',es:'La importancia de método es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Labor"', exerciseA:'laboratorio' },
    { id:'b2-4-l7', title:'Hipótesis', topic:'hipotesis', rewardCoins:25, rewardXp:36,
      grammarTip:'Kausale Satzverbindungen: dadurch dass, aufgrund dessen, infolgedessen.',
      phrases:[{de:'die Statistik spielt eine zentrale Rolle.',es:'El/la estadística juega un papel central.'},{de:'Die Bedeutung der Statistiks ist offensichtlich.',es:'La importancia de estadística es obvia.'},{de:'Wir müssen die Statistik berücksichtigen.',es:'Debemos considerar estadística.'},{de:'die Daten spielt eine zentrale Rolle.',es:'El/la datos juega un papel central.'},{de:'Die Bedeutung der Datens ist offensichtlich.',es:'La importancia de datos es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "estadística"', exerciseA:'Statistik' },
    { id:'b2-4-l8', title:'Estudio', topic:'estudio', rewardCoins:25, rewardXp:36,
      grammarTip:'Module Satzverbindungen: indem, dadurch dass, sodass, derart dass.',
      phrases:[{de:'die Schlussfolgerung spielt eine zentrale Rolle.',es:'El/la conclusión juega un papel central.'},{de:'Die Bedeutung der Schlussfolgerungs ist offensichtlich.',es:'La importancia de conclusión es obvia.'},{de:'Wir müssen die Schlussfolgerung berücksichtigen.',es:'Debemos considerar conclusión.'},{de:'die Hypothese spielt eine zentrale Rolle.',es:'El/la hipótesis juega un papel central.'},{de:'Die Bedeutung der Hypotheses ist offensichtlich.',es:'La importancia de hipótesis es obvia.'}],
      exerciseType:'order', exerciseQ:'Ordena: "Schlussfolgerung"', exerciseA:'Schlussfolgerung' },
    { id:'b2-3-l2', title:'Periodismo', topic:'periodismo', rewardCoins:25, rewardXp:36,
      grammarTip:'Modalpartikeln: doch, ja, wohl, eigentlich, denn, mal. Matizan la frase.',
      phrases:[{de:'die Medien spielt eine zentrale Rolle.',es:'El/la medios juega un papel central.'},{de:'Die Bedeutung der Mediens ist offensichtlich.',es:'La importancia de medios es obvia.'},{de:'Wir müssen die Medien berücksichtigen.',es:'Debemos considerar medios.'},{de:'die Presse spielt eine zentrale Rolle.',es:'El/la prensa juega un papel central.'},{de:'Die Bedeutung der Presses ist offensichtlich.',es:'La importancia de prensa es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Medien' },
    { id:'b2-3-l3', title:'Redes sociales', topic:'redes', rewardCoins:25, rewardXp:36,
      grammarTip:'Modalpartikel "doch" para énfasis: Das ist doch klar! Das weiß doch jeder!',
      phrases:[{de:'das Fernsehen spielt eine zentrale Rolle.',es:'El/la televisión juega un papel central.'},{de:'Die Bedeutung des Fernsehens ist offensichtlich.',es:'La importancia de televisión es obvia.'},{de:'Wir müssen das Fernsehen berücksichtigen.',es:'Debemos considerar televisión.'},{de:'die Nachrichten spielt eine zentrale Rolle.',es:'El/la noticias juega un papel central.'},{de:'Die Bedeutung der Nachrichtens ist offensichtlich.',es:'La importancia de noticias es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Fernsehen ist gut.', exerciseA:'Das',
      options:['Der','Die','Das'], },
    { id:'b2-3-l4', title:'Opinión pública', topic:'opinion-publica', rewardCoins:25, rewardXp:36,
      grammarTip:'Modalpartikel "eigentlich": Was machst du eigentlich? (suaviza/curiosidad)',
      phrases:[{de:'der Journalist spielt eine zentrale Rolle.',es:'El/la periodista juega un papel central.'},{de:'Die Bedeutung des Journalists ist offensichtlich.',es:'La importancia de periodista es obvia.'},{de:'Wir müssen den Journalist berücksichtigen.',es:'Debemos considerar periodista.'},{de:'der Reporter spielt eine zentrale Rolle.',es:'El/la reportero juega un papel central.'},{de:'Die Bedeutung des Reporters ist offensichtlich.',es:'La importancia de reportero es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Journalist"?', exerciseA:'Journalisten' },
    { id:'b2-3-l5', title:'Entrevista', topic:'entrevista', rewardCoins:25, rewardXp:36,
      grammarTip:'Modalpartikel "mal" para informalidad: Komm mal her! Guck mal!',
      phrases:[{de:'der Artikel spielt eine zentrale Rolle.',es:'El/la artículo juega un papel central.'},{de:'Die Bedeutung des Artikels ist offensichtlich.',es:'La importancia de artículo es obvia.'},{de:'Wir müssen den Artikel berücksichtigen.',es:'Debemos considerar artículo.'},{de:'die Schlagzeile spielt eine zentrale Rolle.',es:'El/la titular juega un papel central.'},{de:'Die Bedeutung der Schlagzeiles ist offensichtlich.',es:'La importancia de titular es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "artículo"', exerciseA:'Artikel' },
    { id:'b2-3-l6', title:'Reportaje', topic:'reportaje', rewardCoins:25, rewardXp:36,
      grammarTip:'Modalverb + PassivInfinitiv: Das muss noch gemacht werden.',
      phrases:[{de:'das Interview spielt eine zentrale Rolle.',es:'El/la entrevista juega un papel central.'},{de:'Die Bedeutung des Interviews ist offensichtlich.',es:'La importancia de entrevista es obvia.'},{de:'Wir müssen das Interview berücksichtigen.',es:'Debemos considerar entrevista.'},{de:'die Reportage spielt eine zentrale Rolle.',es:'El/la reportaje juega un papel central.'},{de:'Die Bedeutung der Reportages ist offensichtlich.',es:'La importancia de reportaje es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Interview"', exerciseA:'entrevista' },
    { id:'b2-3-l7', title:'Medios', topic:'medios', rewardCoins:25, rewardXp:36,
      grammarTip:'Anredepronomen: du (informal) vs Sie (formal). En cartas: Du/Sie en mayúscula.',
      phrases:[{de:'die Sendung spielt eine zentrale Rolle.',es:'El/la programa juega un papel central.'},{de:'Die Bedeutung der Sendungs ist offensichtlich.',es:'La importancia de programa es obvia.'},{de:'Wir müssen die Sendung berücksichtigen.',es:'Debemos considerar programa.'},{de:'der Moderator spielt eine zentrale Rolle.',es:'El/la presentador juega un papel central.'},{de:'Die Bedeutung des Moderators ist offensichtlich.',es:'La importancia de presentador es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "programa"', exerciseA:'Sendung' },
    { id:'b2-3-l8', title:'Periodismo', topic:'periodismo', rewardCoins:25, rewardXp:36,
      grammarTip:'Konnektoren: nicht nur...sondern auch, sowohl...als auch, weder...noch.',
      phrases:[{de:'die Einschaltquote spielt eine zentrale Rolle.',es:'El/la audiencia juega un papel central.'},{de:'Die Bedeutung der Einschaltquotes ist offensichtlich.',es:'La importancia de audiencia es obvia.'},{de:'Wir müssen die Einschaltquote berücksichtigen.',es:'Debemos considerar audiencia.'},{de:'die Werbung spielt eine zentrale Rolle.',es:'El/la publicidad juega un papel central.'},{de:'Die Bedeutung der Werbungs ist offensichtlich.',es:'La importancia de publicidad es obvia.'}],
      exerciseType:'order', exerciseQ:'Ordena: "Einschaltquote"', exerciseA:'Einschaltquote' },
    { id:'b2-2-l3', title:'Amistad', topic:'amistad', rewardCoins:25, rewardXp:36,
      grammarTip:'Nebensätze mit "je...desto/umso" (proporción): Je mehr man lernt, desto besser wird man.',
      phrases:[{de:'der Alltag spielt eine zentrale Rolle.',es:'El/la día a día juega un papel central.'},{de:'Die Bedeutung des Alltags ist offensichtlich.',es:'La importancia de día a día es obvia.'},{de:'Wir müssen den Alltag berücksichtigen.',es:'Debemos considerar día a día.'},{de:'die Routine spielt eine zentrale Rolle.',es:'El/la rutina juega un papel central.'},{de:'Die Bedeutung der Routines ist offensichtlich.',es:'La importancia de rutina es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Alltag' },
    { id:'b2-2-l4', title:'Conflicto', topic:'conflicto', rewardCoins:25, rewardXp:36,
      grammarTip:'irrealer Wunschsatz (GEGENWART): Wenn ich doch Zeit hätte! (ojalá tuviera tiempo)',
      phrases:[{de:'die Angewohnheit spielt eine zentrale Rolle.',es:'El/la vicio juega un papel central.'},{de:'Die Bedeutung der Angewohnheits ist offensichtlich.',es:'La importancia de vicio es obvia.'},{de:'Wir müssen die Angewohnheit berücksichtigen.',es:'Debemos considerar vicio.'},{de:'der Lebensstil spielt eine zentrale Rolle.',es:'El/la estilo de vida juega un papel central.'},{de:'Die Bedeutung des Lebensstils ist offensichtlich.',es:'La importancia de estilo de vida es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Angewohnheit ist gut.', exerciseA:'Die',
      options:['Der','Die','Das'], },
    { id:'b2-2-l5', title:'Acuerdo', topic:'acuerdo', rewardCoins:25, rewardXp:36,
      grammarTip:'irrealer Wunschsatz (VERGANGENHEIT): Wenn ich doch gekommen wäre! (ojalá hubiera venido)',
      phrases:[{de:'der Wohlstand spielt eine zentrale Rolle.',es:'El/la bienestar juega un papel central.'},{de:'Die Bedeutung des Wohlstands ist offensichtlich.',es:'La importancia de bienestar es obvia.'},{de:'Wir müssen den Wohlstand berücksichtigen.',es:'Debemos considerar bienestar.'},{de:'die Zufriedenheit spielt eine zentrale Rolle.',es:'El/la satisfacción juega un papel central.'},{de:'Die Bedeutung der Zufriedenheits ist offensichtlich.',es:'La importancia de satisfacción es obvia.'}],
      exerciseType:'fill', exerciseQ:'Ich ___ .', exerciseA:'Wohlstand' },
    { id:'b2-2-l6', title:'Sentimientos', topic:'sentimientos', rewardCoins:25, rewardXp:36,
      grammarTip:'Gleichsetzung mit "als ob": Er tut so, als ob er nichts wüsste.',
      phrases:[{de:'die Einsamkeit spielt eine zentrale Rolle.',es:'El/la soledad juega un papel central.'},{de:'Die Bedeutung der Einsamkeits ist offensichtlich.',es:'La importancia de soledad es obvia.'},{de:'Wir müssen die Einsamkeit berücksichtigen.',es:'Debemos considerar soledad.'},{de:'die Gemeinschaft spielt eine zentrale Rolle.',es:'El/la comunidad juega un papel central.'},{de:'Die Bedeutung der Gemeinschafts ist offensichtlich.',es:'La importancia de comunidad es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "soledad"', exerciseA:'Einsamkeit' },
    { id:'b2-2-l7', title:'Pareja', topic:'pareja', rewardCoins:25, rewardXp:36,
      grammarTip:'Es-Stellung: Es freut mich, dass du gekommen bist. Es ist wichtig zu lernen.',
      phrases:[{de:'die Beziehung spielt eine zentrale Rolle.',es:'El/la relación juega un papel central.'},{de:'Die Bedeutung der Beziehungs ist offensichtlich.',es:'La importancia de relación es obvia.'},{de:'Wir müssen die Beziehung berücksichtigen.',es:'Debemos considerar relación.'},{de:'die Bekanntschaft spielt eine zentrale Rolle.',es:'El/la conocido juega un papel central.'},{de:'Die Bedeutung der Bekanntschafts ist offensichtlich.',es:'La importancia de conocido es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Beziehung"', exerciseA:'relación' },
    { id:'b2-2-l8', title:'Comunicación', topic:'comunicacion', rewardCoins:25, rewardXp:36,
      grammarTip:'Vorangestelltes Genitivattribut (sächsischer Genitiv): Müllers Haus, Deutschlands Zukunft.',
      phrases:[{de:'die Partnerschaft spielt eine zentrale Rolle.',es:'El/la pareja juega un papel central.'},{de:'Die Bedeutung der Partnerschafts ist offensichtlich.',es:'La importancia de pareja es obvia.'},{de:'Wir müssen die Partnerschaft berücksichtigen.',es:'Debemos considerar pareja.'},{de:'die Ehe spielt eine zentrale Rolle.',es:'El/la matrimonio juega un papel central.'},{de:'Die Bedeutung der Ehes ist offensichtlich.',es:'La importancia de matrimonio es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "pareja"', exerciseA:'Partnerschaft' },
    { id:'b2-1-l3', title:'Gestión', topic:'gestion', rewardCoins:22, rewardXp:32,
      grammarTip:'Nominalisierung de verbos: lernen → das Lernen, entscheiden → die Entscheidung.',
      phrases:[{de:'die Wirtschaft spielt eine zentrale Rolle.',es:'El/la economía juega un papel central.'},{de:'Die Bedeutung der Wirtschafts ist offensichtlich.',es:'La importancia de economía es obvia.'},{de:'Wir müssen die Wirtschaft berücksichtigen.',es:'Debemos considerar economía.'},{de:'der Markt spielt eine zentrale Rolle.',es:'El/la mercado juega un papel central.'},{de:'Die Bedeutung des Markts ist offensichtlich.',es:'La importancia de mercado es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Wirtschaft' },
    { id:'b2-1-l4', title:'Inversión', topic:'inversion', rewardCoins:22, rewardXp:32,
      grammarTip:'Nominalisierung con -ung: vorbereiten → die Vorbereitung, verbinden → die Verbindung.',
      phrases:[{de:'die Industrie spielt eine zentrale Rolle.',es:'El/la industria juega un papel central.'},{de:'Die Bedeutung der Industries ist offensichtlich.',es:'La importancia de industria es obvia.'},{de:'Wir müssen die Industrie berücksichtigen.',es:'Debemos considerar industria.'},{de:'die Produktion spielt eine zentrale Rolle.',es:'El/la producción juega un papel central.'},{de:'Die Bedeutung der Produktions ist offensichtlich.',es:'La importancia de producción es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Industrie ist gut.', exerciseA:'Die',
      options:['Der','Die','Das'], },
    { id:'b2-1-l5', title:'Análisis', topic:'analisis', rewardCoins:22, rewardXp:32,
      grammarTip:'Nominalisierung con -heit/-keit: frei → die Freiheit, möglich → die Möglichkeit.',
      phrases:[{de:'die Nachfrage spielt eine zentrale Rolle.',es:'El/la demanda juega un papel central.'},{de:'Die Bedeutung der Nachfrages ist offensichtlich.',es:'La importancia de demanda es obvia.'},{de:'Wir müssen die Nachfrage berücksichtigen.',es:'Debemos considerar demanda.'},{de:'das Angebot spielt eine zentrale Rolle.',es:'El/la oferta juega un papel central.'},{de:'Die Bedeutung des Angebots ist offensichtlich.',es:'La importancia de oferta es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Nachfrage"?', exerciseA:'Nachfragen' },
    { id:'b2-1-l6', title:'Negocios', topic:'negocios', rewardCoins:22, rewardXp:32,
      grammarTip:'Funktionsverbgefüge: zur Entscheidung bringen, in Betracht ziehen, zur Verfügung stellen.',
      phrases:[{de:'der Lieferant spielt eine zentrale Rolle.',es:'El/la proveedor juega un papel central.'},{de:'Die Bedeutung des Lieferants ist offensichtlich.',es:'La importancia de proveedor es obvia.'},{de:'Wir müssen den Lieferant berücksichtigen.',es:'Debemos considerar proveedor.'},{de:'der Hersteller spielt eine zentrale Rolle.',es:'El/la fabricante juega un papel central.'},{de:'Die Bedeutung des Herstellers ist offensichtlich.',es:'La importancia de fabricante es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "proveedor"', exerciseA:'Lieferant' },
    { id:'b2-1-l7', title:'Estrategia', topic:'estrategia', rewardCoins:22, rewardXp:32,
      grammarTip:'Genitivattribut: der Fortschritt der Wissenschaft, die Meinung des Experten.',
      phrases:[{de:'die Konkurrenz spielt eine zentrale Rolle.',es:'El/la competencia juega un papel central.'},{de:'Die Bedeutung der Konkurrenzs ist offensichtlich.',es:'La importancia de competencia es obvia.'},{de:'Wir müssen die Konkurrenz berücksichtigen.',es:'Debemos considerar competencia.'},{de:'das Monopol spielt eine zentrale Rolle.',es:'El/la monopolio juega un papel central.'},{de:'Die Bedeutung des Monopols ist offensichtlich.',es:'La importancia de monopolio es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Konkurrenz"', exerciseA:'competencia' },
    { id:'b2-1-l8', title:'Producción', topic:'produccion', rewardCoins:22, rewardXp:32,
      grammarTip:'Erweiterter Infinitiv mit "zu": den Plan, die Arbeit zu beenden.',
      phrases:[{de:'der Gewinn spielt eine zentrale Rolle.',es:'El/la ganancia juega un papel central.'},{de:'Die Bedeutung des Gewinns ist offensichtlich.',es:'La importancia de ganancia es obvia.'},{de:'Wir müssen den Gewinn berücksichtigen.',es:'Debemos considerar ganancia.'},{de:'der Verlust spielt eine zentrale Rolle.',es:'El/la pérdida juega un papel central.'},{de:'Die Bedeutung des Verlusts ist offensichtlich.',es:'La importancia de pérdida es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "ganancia"', exerciseA:'Gewinn' },
    { id:'b1-4-l2', title:'Argumentos', topic:'argumentos', rewardCoins:18, rewardXp:26,
      grammarTip:'Plusquamperfekt: hatte/war + Partizip. Nachdem ich gegessen hatte, ging ich spazieren.',
      phrases:[{de:'die Lösung spielt eine zentrale Rolle.',es:'El/la solución juega un papel central.'},{de:'Die Bedeutung der Lösungs ist offensichtlich.',es:'La importancia de solución es obvia.'},{de:'Wir müssen die Lösung berücksichtigen.',es:'Debemos considerar solución.'},{de:'das Problem spielt eine zentrale Rolle.',es:'El/la problema juega un papel central.'},{de:'Die Bedeutung des Problems ist offensichtlich.',es:'La importancia de problema es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Lösung' },
    { id:'b1-4-l3', title:'Crítica', topic:'critica', rewardCoins:18, rewardXp:26,
      grammarTip:'Nachdem + Plusquamperfekt → Präteritum: Secuencia temporal en pasado.',
      phrases:[{de:'die Herausforderung spielt eine zentrale Rolle.',es:'El/la desafío juega un papel central.'},{de:'Die Bedeutung der Herausforderungs ist offensichtlich.',es:'La importancia de desafío es obvia.'},{de:'Wir müssen die Herausforderung berücksichtigen.',es:'Debemos considerar desafío.'},{de:'die Möglichkeit spielt eine zentrale Rolle.',es:'El/la posibilidad juega un papel central.'},{de:'Die Bedeutung der Möglichkeits ist offensichtlich.',es:'La importancia de posibilidad es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Herausforderung ist gut.', exerciseA:'Die',
      options:['Der','Die','Das'], },
    { id:'b1-4-l4', title:'Comparación', topic:'comparacion', rewardCoins:18, rewardXp:26,
      grammarTip:'Konjunktiv I presente: er habe, er sei, er werde. Para discurso indirecto.',
      phrases:[{de:'das Ziel spielt eine zentrale Rolle.',es:'El/la objetivo juega un papel central.'},{de:'Die Bedeutung des Ziels ist offensichtlich.',es:'La importancia de objetivo es obvia.'},{de:'Wir müssen das Ziel berücksichtigen.',es:'Debemos considerar objetivo.'},{de:'die Zukunft spielt eine zentrale Rolle.',es:'El/la futuro juega un papel central.'},{de:'Die Bedeutung der Zukunfts ist offensichtlich.',es:'La importancia de futuro es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Ziel"?', exerciseA:'Ziele' },
    { id:'b1-4-l5', title:'Conclusión', topic:'conclusion', rewardCoins:18, rewardXp:26,
      grammarTip:'Konjunktiv I pasado: er habe gehabt, er sei gewesen. Discurso indirecto pasado.',
      phrases:[{de:'die Gegenwart spielt eine zentrale Rolle.',es:'El/la presente juega un papel central.'},{de:'Die Bedeutung der Gegenwarts ist offensichtlich.',es:'La importancia de presente es obvia.'},{de:'Wir müssen die Gegenwart berücksichtigen.',es:'Debemos considerar presente.'},{de:'die Entscheidung spielt eine zentrale Rolle.',es:'El/la decisión juega un papel central.'},{de:'Die Bedeutung der Entscheidungs ist offensichtlich.',es:'La importancia de decisión es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "presente"', exerciseA:'Gegenwart' },
    { id:'b1-4-l6', title:'Perspectiva', topic:'perspectiva', rewardCoins:18, rewardXp:26,
      grammarTip:'Discurso indirecto: Er sagt, er komme morgen. Er sagte, er sei gestern gekommen.',
      phrases:[{de:'die Vorbereitung spielt eine zentrale Rolle.',es:'El/la preparación juega un papel central.'},{de:'Die Bedeutung der Vorbereitungs ist offensichtlich.',es:'La importancia de preparación es obvia.'},{de:'Wir müssen die Vorbereitung berücksichtigen.',es:'Debemos considerar preparación.'},{de:'die Durchführung spielt eine zentrale Rolle.',es:'El/la realización juega un papel central.'},{de:'Die Bedeutung der Durchführungs ist offensichtlich.',es:'La importancia de realización es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Vorbereitung"', exerciseA:'preparación' },
    { id:'b1-4-l7', title:'Evaluación', topic:'evaluacion', rewardCoins:18, rewardXp:26,
      grammarTip:'Partizip I como adjetivo: der lernende Student (el estudiante que aprende).',
      phrases:[{de:'die Auswirkung spielt eine zentrale Rolle.',es:'El/la consecuencia juega un papel central.'},{de:'Die Bedeutung der Auswirkungs ist offensichtlich.',es:'La importancia de consecuencia es obvia.'},{de:'Wir müssen die Auswirkung berücksichtigen.',es:'Debemos considerar consecuencia.'},{de:'die Ursache spielt eine zentrale Rolle.',es:'El/la causa juega un papel central.'},{de:'Die Bedeutung der Ursaches ist offensichtlich.',es:'La importancia de causa es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "consecuencia"', exerciseA:'Auswirkung' },
    { id:'b1-4-l8', title:'Argumentos', topic:'argumentos', rewardCoins:18, rewardXp:26,
      grammarTip:'Partizip I como adverbio: Er kam lachend herein (Entró riendo).',
      phrases:[{de:'der Zusammenhang spielt eine zentrale Rolle.',es:'El/la relación juega un papel central.'},{de:'Die Bedeutung des Zusammenhangs ist offensichtlich.',es:'La importancia de relación es obvia.'},{de:'Wir müssen den Zusammenhang berücksichtigen.',es:'Debemos considerar relación.'},{de:'der Unterschied spielt eine zentrale Rolle.',es:'El/la diferencia juega un papel central.'},{de:'Die Bedeutung des Unterschieds ist offensichtlich.',es:'La importancia de diferencia es obvia.'}],
      exerciseType:'order', exerciseQ:'Ordena: "Zusammenhang"', exerciseA:'Zusammenhang' },
    { id:'b1-3-l2', title:'Hobbies', topic:'hobbies', rewardCoins:18, rewardXp:26,
      grammarTip:'Nebensätze mit "indem" (instrumento): Man lernt, indem man übt.',
      phrases:[{de:'die Gesundheit spielt eine zentrale Rolle.',es:'El/la salud juega un papel central.'},{de:'Die Bedeutung der Gesundheits ist offensichtlich.',es:'La importancia de salud es obvia.'},{de:'Wir müssen die Gesundheit berücksichtigen.',es:'Debemos considerar salud.'},{de:'die Ernährung spielt eine zentrale Rolle.',es:'El/la alimentación juega un papel central.'},{de:'Die Bedeutung der Ernährungs ist offensichtlich.',es:'La importancia de alimentación es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Gesundheit' },
    { id:'b1-3-l3', title:'Naturaleza', topic:'naturaleza', rewardCoins:18, rewardXp:26,
      grammarTip:'Nebensätze con "sodass" (consecuencia): Er lernte viel, sodass er die Prüfung bestand.',
      phrases:[{de:'der Sportart spielt eine zentrale Rolle.',es:'El/la deporte juega un papel central.'},{de:'Die Bedeutung des Sportarts ist offensichtlich.',es:'La importancia de deporte es obvia.'},{de:'Wir müssen den Sportart berücksichtigen.',es:'Debemos considerar deporte.'},{de:'das Training spielt eine zentrale Rolle.',es:'El/la entrenamiento juega un papel central.'},{de:'Die Bedeutung des Trainings ist offensichtlich.',es:'La importancia de entrenamiento es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Sportart ist gut.', exerciseA:'Der',
      options:['Der','Die','Das'], },
    { id:'b1-3-l4', title:'Eventos', topic:'eventos', rewardCoins:18, rewardXp:26,
      grammarTip:'Nebensätze con "damit" (finalidad): Ich erkläre es, damit du es verstehst.',
      phrases:[{de:'der Spieler spielt eine zentrale Rolle.',es:'El/la jugador juega un papel central.'},{de:'Die Bedeutung des Spielers ist offensichtlich.',es:'La importancia de jugador es obvia.'},{de:'Wir müssen den Spieler berücksichtigen.',es:'Debemos considerar jugador.'},{de:'der Trainer spielt eine zentrale Rolle.',es:'El/la entrenador juega un papel central.'},{de:'Die Bedeutung des Trainers ist offensichtlich.',es:'La importancia de entrenador es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Spieler"?', exerciseA:'Spieler' },
    { id:'b1-3-l5', title:'Viajes', topic:'viajes', rewardCoins:18, rewardXp:26,
      grammarTip:'Infinitivsätze con "um...zu": Ich lerne Deutsch, um in Berlin zu arbeiten.',
      phrases:[{de:'der Gegner spielt eine zentrale Rolle.',es:'El/la adversario juega un papel central.'},{de:'Die Bedeutung des Gegners ist offensichtlich.',es:'La importancia de adversario es obvia.'},{de:'Wir müssen den Gegner berücksichtigen.',es:'Debemos considerar adversario.'},{de:'der Sieg spielt eine zentrale Rolle.',es:'El/la victoria juega un papel central.'},{de:'Die Bedeutung des Siegs ist offensichtlich.',es:'La importancia de victoria es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "adversario"', exerciseA:'Gegner' },
    { id:'b1-3-l6', title:'Ocio', topic:'ocio', rewardCoins:18, rewardXp:26,
      grammarTip:'Infinitivsätze con "ohne...zu": Er ging, ohne sich zu verabschieden.',
      phrases:[{de:'der Wettbewerb spielt eine zentrale Rolle.',es:'El/la competición juega un papel central.'},{de:'Die Bedeutung des Wettbewerbs ist offensichtlich.',es:'La importancia de competición es obvia.'},{de:'Wir müssen den Wettbewerb berücksichtigen.',es:'Debemos considerar competición.'},{de:'die Meisterschaft spielt eine zentrale Rolle.',es:'El/la campeonato juega un papel central.'},{de:'Die Bedeutung der Meisterschafts ist offensichtlich.',es:'La importancia de campeonato es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Wettbewerb"', exerciseA:'competición' },
    { id:'b1-3-l7', title:'Aficiones', topic:'aficiones', rewardCoins:18, rewardXp:26,
      grammarTip:'Infinitivsätze con "(an)statt...zu": Statt zu lernen, sieht er fern.',
      phrases:[{de:'der Zuschauer spielt eine zentrale Rolle.',es:'El/la espectador juega un papel central.'},{de:'Die Bedeutung des Zuschauers ist offensichtlich.',es:'La importancia de espectador es obvia.'},{de:'Wir müssen den Zuschauer berücksichtigen.',es:'Debemos considerar espectador.'},{de:'der Rekord spielt eine zentrale Rolle.',es:'El/la récord juega un papel central.'},{de:'Die Bedeutung des Rekords ist offensichtlich.',es:'La importancia de récord es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "espectador"', exerciseA:'Zuschauer' },
    { id:'b1-3-l8', title:'Hobbies', topic:'hobbies', rewardCoins:18, rewardXp:26,
      grammarTip:'Futur I: werden + Infinitiv. Ich werde morgen anrufen.',
      phrases:[{de:'der Verein spielt eine zentrale Rolle.',es:'El/la club juega un papel central.'},{de:'Die Bedeutung des Vereins ist offensichtlich.',es:'La importancia de club es obvia.'},{de:'Wir müssen den Verein berücksichtigen.',es:'Debemos considerar club.'},{de:'das Mitglied spielt eine zentrale Rolle.',es:'El/la miembro juega un papel central.'},{de:'Die Bedeutung des Mitglieds ist offensichtlich.',es:'La importancia de miembro es obvia.'}],
      exerciseType:'order', exerciseQ:'Ordena: "Verein"', exerciseA:'Verein' },
    { id:'b1-2-l3', title:'Educación', topic:'educacion', rewardCoins:18, rewardXp:26,
      grammarTip:'Konjunktiv II Vergangenheit: hätte/wäre + Partizip. Ich wäre gern gekommen.',
      phrases:[{de:'die Gesellschaft spielt eine zentrale Rolle.',es:'El/la sociedad juega un papel central.'},{de:'Die Bedeutung der Gesellschafts ist offensichtlich.',es:'La importancia de sociedad es obvia.'},{de:'Wir müssen die Gesellschaft berücksichtigen.',es:'Debemos considerar sociedad.'},{de:'die Umwelt spielt eine zentrale Rolle.',es:'El/la medio ambiente juega un papel central.'},{de:'Die Bedeutung der Umwelts ist offensichtlich.',es:'La importancia de medio ambiente es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Gesellschaft' },
    { id:'b1-2-l4', title:'Noticias', topic:'noticias', rewardCoins:18, rewardXp:26,
      grammarTip:'Konjunktiv II mit Modalverben: ich könnte, ich müsste, ich sollte, ich dürfte, ich wollte.',
      phrases:[{de:'die Regierung spielt eine zentrale Rolle.',es:'El/la gobierno juega un papel central.'},{de:'Die Bedeutung der Regierungs ist offensichtlich.',es:'La importancia de gobierno es obvia.'},{de:'Wir müssen die Regierung berücksichtigen.',es:'Debemos considerar gobierno.'},{de:'das Gesetz spielt eine zentrale Rolle.',es:'El/la ley juega un papel central.'},{de:'Die Bedeutung des Gesetzs ist offensichtlich.',es:'La importancia de ley es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Regierung ist gut.', exerciseA:'Die',
      options:['Der','Die','Das'], },
    { id:'b1-2-l5', title:'Debate', topic:'debate', rewardCoins:18, rewardXp:26,
      grammarTip:'Passiv Präsens: werden + Partizip. Das Haus wird gebaut.',
      phrases:[{de:'die Freiheit spielt eine zentrale Rolle.',es:'El/la libertad juega un papel central.'},{de:'Die Bedeutung der Freiheits ist offensichtlich.',es:'La importancia de libertad es obvia.'},{de:'Wir müssen die Freiheit berücksichtigen.',es:'Debemos considerar libertad.'},{de:'die Gerechtigkeit spielt eine zentrale Rolle.',es:'El/la justicia juega un papel central.'},{de:'Die Bedeutung der Gerechtigkeits ist offensichtlich.',es:'La importancia de justicia es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Freiheit"?', exerciseA:'Freiheiten' },
    { id:'b1-2-l6', title:'Cultura', topic:'cultura', rewardCoins:18, rewardXp:26,
      grammarTip:'Passiv Präteritum: wurde + Partizip. Das Haus wurde gebaut.',
      phrases:[{de:'der Krieg spielt eine zentrale Rolle.',es:'El/la guerra juega un papel central.'},{de:'Die Bedeutung des Kriegs ist offensichtlich.',es:'La importancia de guerra es obvia.'},{de:'Wir müssen den Krieg berücksichtigen.',es:'Debemos considerar guerra.'},{de:'die Macht spielt eine zentrale Rolle.',es:'El/la poder juega un papel central.'},{de:'Die Bedeutung der Machts ist offensichtlich.',es:'La importancia de poder es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "guerra"', exerciseA:'Krieg' },
    { id:'b1-2-l7', title:'Tradiciones', topic:'tradiciones', rewardCoins:18, rewardXp:26,
      grammarTip:'Passiv mit Modalverben: Das Haus muss gebaut werden. (MV + Partizip + werden)',
      phrases:[{de:'die Demokratie spielt eine zentrale Rolle.',es:'El/la democracia juega un papel central.'},{de:'Die Bedeutung der Demokraties ist offensichtlich.',es:'La importancia de democracia es obvia.'},{de:'Wir müssen die Demokratie berücksichtigen.',es:'Debemos considerar democracia.'},{de:'die Partei spielt eine zentrale Rolle.',es:'El/la partido juega un papel central.'},{de:'Die Bedeutung der Parteis ist offensichtlich.',es:'La importancia de partido es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Demokratie"', exerciseA:'democracia' },
    { id:'b1-2-l8', title:'Valores', topic:'valores', rewardCoins:18, rewardXp:26,
      grammarTip:'Passiv Perfekt: ist + Partizip + worden. Das Haus ist gebaut worden.',
      phrases:[{de:'der Bürger spielt eine zentrale Rolle.',es:'El/la ciudadano juega un papel central.'},{de:'Die Bedeutung des Bürgers ist offensichtlich.',es:'La importancia de ciudadano es obvia.'},{de:'Wir müssen den Bürger berücksichtigen.',es:'Debemos considerar ciudadano.'},{de:'der Ausländer spielt eine zentrale Rolle.',es:'El/la extranjero juega un papel central.'},{de:'Die Bedeutung des Ausländers ist offensichtlich.',es:'La importancia de extranjero es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "ciudadano"', exerciseA:'Bürger' },
    { id:'b1-1-l3', title:'Finanzas', topic:'finanzas', rewardCoins:18, rewardXp:26,
      grammarTip:'Preposiciones con Genitiv: während (durante), wegen (debido a), trotz (a pesar de), statt (en lugar de).',
      phrases:[{de:'die Erfahrung spielt eine zentrale Rolle.',es:'El/la experiencia juega un papel central.'},{de:'Die Bedeutung der Erfahrungs ist offensichtlich.',es:'La importancia de experiencia es obvia.'},{de:'Wir müssen die Erfahrung berücksichtigen.',es:'Debemos considerar experiencia.'},{de:'der Eindruck spielt eine zentrale Rolle.',es:'El/la impresión juega un papel central.'},{de:'Die Bedeutung des Eindrucks ist offensichtlich.',es:'La importancia de impresión es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Erfahrung' },
    { id:'b1-1-l4', title:'La empresa', topic:'empresa', rewardCoins:18, rewardXp:26,
      grammarTip:'Adjektivdeklination nach bestimmtem Artikel: der gute Mann, die gute Frau, das gute Kind.',
      phrases:[{de:'das Vorstellungsgespräch spielt eine zentrale Rolle.',es:'El/la entrevista juega un papel central.'},{de:'Die Bedeutung des Vorstellungsgesprächs ist offensichtlich.',es:'La importancia de entrevista es obvia.'},{de:'Wir müssen das Vorstellungsgespräch berücksichtigen.',es:'Debemos considerar entrevista.'},{de:'die Ausbildung spielt eine zentrale Rolle.',es:'El/la formación juega un papel central.'},{de:'Die Bedeutung der Ausbildungs ist offensichtlich.',es:'La importancia de formación es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Vorstellungsgespräch ist gut.', exerciseA:'Das',
      options:['Der','Die','Das'], },
    { id:'b1-1-l5', title:'Reuniones', topic:'reuniones', rewardCoins:18, rewardXp:26,
      grammarTip:'Adjektivdeklination nach unbestimmtem Artikel: ein guter Mann, eine gute Frau, ein gutes Kind.',
      phrases:[{de:'das Fach spielt eine zentrale Rolle.',es:'El/la asignatura juega un papel central.'},{de:'Die Bedeutung des Fachs ist offensichtlich.',es:'La importancia de asignatura es obvia.'},{de:'Wir müssen das Fach berücksichtigen.',es:'Debemos considerar asignatura.'},{de:'das Semester spielt eine zentrale Rolle.',es:'El/la semestre juega un papel central.'},{de:'Die Bedeutung des Semesters ist offensichtlich.',es:'La importancia de semestre es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Fach"?', exerciseA:'Fächer' },
    { id:'b1-1-l6', title:'Carrera', topic:'carrera', rewardCoins:18, rewardXp:26,
      grammarTip:'Adjektivdeklination ohne Artikel: guter Kaffee, gute Milch, gutes Brot.',
      phrases:[{de:'das Zeugnis spielt eine zentrale Rolle.',es:'El/la certificado juega un papel central.'},{de:'Die Bedeutung des Zeugniss ist offensichtlich.',es:'La importancia de certificado es obvia.'},{de:'Wir müssen das Zeugnis berücksichtigen.',es:'Debemos considerar certificado.'},{de:'der Abschluss spielt eine zentrale Rolle.',es:'El/la título juega un papel central.'},{de:'Die Bedeutung des Abschlusss ist offensichtlich.',es:'La importancia de título es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "certificado"', exerciseA:'Zeugnis' },
    { id:'b1-1-l7', title:'Mercado laboral', topic:'mercado', rewardCoins:18, rewardXp:26,
      grammarTip:'RelativsätzeNominativ: der Mann, der dort steht. Die Frau, die singt. Das Kind, das spielt.',
      phrases:[{de:'die Bibliothek spielt eine zentrale Rolle.',es:'El/la biblioteca juega un papel central.'},{de:'Die Bedeutung der Bibliotheks ist offensichtlich.',es:'La importancia de biblioteca es obvia.'},{de:'Wir müssen die Bibliothek berücksichtigen.',es:'Debemos considerar biblioteca.'},{de:'das Praktikum spielt eine zentrale Rolle.',es:'El/la prácticas juega un papel central.'},{de:'Die Bedeutung des Praktikums ist offensichtlich.',es:'La importancia de prácticas es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Bibliothek"', exerciseA:'biblioteca' },
    { id:'b1-1-l8', title:'Contratos', topic:'contratos', rewardCoins:18, rewardXp:26,
      grammarTip:'RelativsätzeAkkusativ: der Mann, den ich sehe. Die Frau, die ich kenne. Das Kind, das ich mag.',
      phrases:[{de:'die Wissenschaft spielt eine zentrale Rolle.',es:'El/la ciencia juega un papel central.'},{de:'Die Bedeutung der Wissenschafts ist offensichtlich.',es:'La importancia de ciencia es obvia.'},{de:'Wir müssen die Wissenschaft berücksichtigen.',es:'Debemos considerar ciencia.'},{de:'das Unternehmen spielt eine zentrale Rolle.',es:'El/la empresa juega un papel central.'},{de:'Die Bedeutung des Unternehmens ist offensichtlich.',es:'La importancia de empresa es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "ciencia"', exerciseA:'Wissenschaft' },
    { id:'a2-4-l2', title:'Tema: general1', topic:'general1', rewardCoins:10, rewardXp:15,
      grammarTip:'Presta atención a la estructura de la oración.',
      phrases:[{de:'das Gefühl spielt eine zentrale Rolle.',es:'El/la sentimiento juega un papel central.'},{de:'Die Bedeutung des Gefühls ist offensichtlich.',es:'La importancia de sentimiento es obvia.'},{de:'Wir müssen das Gefühl berücksichtigen.',es:'Debemos considerar sentimiento.'},{de:'die Freude spielt eine zentrale Rolle.',es:'El/la alegría juega un papel central.'},{de:'Die Bedeutung der Freudes ist offensichtlich.',es:'La importancia de alegría es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Gefühl' },
    { id:'a2-4-l3', title:'Tema: general2', topic:'general2', rewardCoins:10, rewardXp:15,
      grammarTip:'El verbo conjugado va en segunda posición.',
      phrases:[{de:'die Liebe spielt eine zentrale Rolle.',es:'El/la amor juega un papel central.'},{de:'Die Bedeutung der Liebes ist offensichtlich.',es:'La importancia de amor es obvia.'},{de:'Wir müssen die Liebe berücksichtigen.',es:'Debemos considerar amor.'},{de:'die Angst spielt eine zentrale Rolle.',es:'El/la miedo juega un papel central.'},{de:'Die Bedeutung der Angsts ist offensichtlich.',es:'La importancia de miedo es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Liebe ist gut.', exerciseA:'Die',
      options:['Der','Die','Das'], },
    { id:'a2-4-l4', title:'Tema: general3', topic:'general3', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'die Trauer spielt eine zentrale Rolle.',es:'El/la tristeza juega un papel central.'},{de:'Die Bedeutung der Trauers ist offensichtlich.',es:'La importancia de tristeza es obvia.'},{de:'Wir müssen die Trauer berücksichtigen.',es:'Debemos considerar tristeza.'},{de:'der Mut spielt eine zentrale Rolle.',es:'El/la valentía juega un papel central.'},{de:'Die Bedeutung des Muts ist offensichtlich.',es:'La importancia de valentía es obvia.'}],
      exerciseType:'fill', exerciseQ:'Ich ___ .', exerciseA:'Trauer' },
    { id:'a2-4-l5', title:'Tema: general4', topic:'general4', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'die Sehnsucht spielt eine zentrale Rolle.',es:'El/la anhelo juega un papel central.'},{de:'Die Bedeutung der Sehnsuchts ist offensichtlich.',es:'La importancia de anhelo es obvia.'},{de:'Wir müssen die Sehnsucht berücksichtigen.',es:'Debemos considerar anhelo.'},{de:'das Vertrauen spielt eine zentrale Rolle.',es:'El/la confianza juega un papel central.'},{de:'Die Bedeutung des Vertrauens ist offensichtlich.',es:'La importancia de confianza es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "anhelo"', exerciseA:'Sehnsucht' },
    { id:'a2-4-l6', title:'Tema: general5', topic:'general5', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'die Ruhe spielt eine zentrale Rolle.',es:'El/la calma juega un papel central.'},{de:'Die Bedeutung der Ruhes ist offensichtlich.',es:'La importancia de calma es obvia.'},{de:'Wir müssen die Ruhe berücksichtigen.',es:'Debemos considerar calma.'},{de:'der Stress spielt eine zentrale Rolle.',es:'El/la estrés juega un papel central.'},{de:'Die Bedeutung des Stresss ist offensichtlich.',es:'La importancia de estrés es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Ruhe"', exerciseA:'calma' },
    { id:'a2-4-l7', title:'Tema: general6', topic:'general6', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'die Langeweile spielt eine zentrale Rolle.',es:'El/la aburrimiento juega un papel central.'},{de:'Die Bedeutung der Langeweiles ist offensichtlich.',es:'La importancia de aburrimiento es obvia.'},{de:'Wir müssen die Langeweile berücksichtigen.',es:'Debemos considerar aburrimiento.'},{de:'der Charakter spielt eine zentrale Rolle.',es:'El/la carácter juega un papel central.'},{de:'Die Bedeutung des Charakters ist offensichtlich.',es:'La importancia de carácter es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "aburrimiento"', exerciseA:'Langeweile' },
    { id:'a2-4-l8', title:'Tema: general1', topic:'general1', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'die Stimmung spielt eine zentrale Rolle.',es:'El/la humor/ánimo juega un papel central.'},{de:'Die Bedeutung der Stimmungs ist offensichtlich.',es:'La importancia de humor/ánimo es obvia.'},{de:'Wir müssen die Stimmung berücksichtigen.',es:'Debemos considerar humor/ánimo.'},{de:'die Laune spielt eine zentrale Rolle.',es:'El/la humor juega un papel central.'},{de:'Die Bedeutung der Launes ist offensichtlich.',es:'La importancia de humor es obvia.'}],
      exerciseType:'order', exerciseQ:'Ordena: "Stimmung"', exerciseA:'Stimmung' },
    { id:'a2-3-l3', title:'Tema: general1', topic:'general1', rewardCoins:10, rewardXp:15,
      grammarTip:'Presta atención a la estructura de la oración.',
      phrases:[{de:'das Wetter spielt eine zentrale Rolle.',es:'El/la clima juega un papel central.'},{de:'Die Bedeutung des Wetters ist offensichtlich.',es:'La importancia de clima es obvia.'},{de:'Wir müssen das Wetter berücksichtigen.',es:'Debemos considerar clima.'},{de:'der Regen spielt eine zentrale Rolle.',es:'El/la lluvia juega un papel central.'},{de:'Die Bedeutung des Regens ist offensichtlich.',es:'La importancia de lluvia es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Wetter' },
    { id:'a2-3-l4', title:'Tema: general2', topic:'general2', rewardCoins:10, rewardXp:15,
      grammarTip:'El verbo conjugado va en segunda posición.',
      phrases:[{de:'die Sonne spielt eine zentrale Rolle.',es:'El/la sol juega un papel central.'},{de:'Die Bedeutung der Sonnes ist offensichtlich.',es:'La importancia de sol es obvia.'},{de:'Wir müssen die Sonne berücksichtigen.',es:'Debemos considerar sol.'},{de:'die Wolke spielt eine zentrale Rolle.',es:'El/la nube juega un papel central.'},{de:'Die Bedeutung der Wolkes ist offensichtlich.',es:'La importancia de nube es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Sonne ist gut.', exerciseA:'Die',
      options:['Der','Die','Das'], },
    { id:'a2-3-l5', title:'Tema: general3', topic:'general3', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'das Gewitter spielt eine zentrale Rolle.',es:'El/la tormenta juega un papel central.'},{de:'Die Bedeutung des Gewitters ist offensichtlich.',es:'La importancia de tormenta es obvia.'},{de:'Wir müssen das Gewitter berücksichtigen.',es:'Debemos considerar tormenta.'},{de:'der Blitz spielt eine zentrale Rolle.',es:'El/la relámpago juega un papel central.'},{de:'Die Bedeutung des Blitzs ist offensichtlich.',es:'La importancia de relámpago es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Gewitter"?', exerciseA:'Gewitter' },
    { id:'a2-3-l6', title:'Tema: general4', topic:'general4', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'der Hagel spielt eine zentrale Rolle.',es:'El/la granizo juega un papel central.'},{de:'Die Bedeutung des Hagels ist offensichtlich.',es:'La importancia de granizo es obvia.'},{de:'Wir müssen den Hagel berücksichtigen.',es:'Debemos considerar granizo.'},{de:'der Frost spielt eine zentrale Rolle.',es:'El/la helada juega un papel central.'},{de:'Die Bedeutung des Frosts ist offensichtlich.',es:'La importancia de helada es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "granizo"', exerciseA:'Hagel' },
    { id:'a2-3-l7', title:'Tema: general5', topic:'general5', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'die Luft spielt eine zentrale Rolle.',es:'El/la aire juega un papel central.'},{de:'Die Bedeutung der Lufts ist offensichtlich.',es:'La importancia de aire es obvia.'},{de:'Wir müssen die Luft berücksichtigen.',es:'Debemos considerar aire.'},{de:'die Temperatur spielt eine zentrale Rolle.',es:'El/la temperatura juega un papel central.'},{de:'Die Bedeutung der Temperaturs ist offensichtlich.',es:'La importancia de temperatura es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Luft"', exerciseA:'aire' },
    { id:'a2-3-l8', title:'Tema: general6', topic:'general6', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'der Regenschirm spielt eine zentrale Rolle.',es:'El/la paraguas juega un papel central.'},{de:'Die Bedeutung des Regenschirms ist offensichtlich.',es:'La importancia de paraguas es obvia.'},{de:'Wir müssen den Regenschirm berücksichtigen.',es:'Debemos considerar paraguas.'},{de:'der Regenmantel spielt eine zentrale Rolle.',es:'El/la impermeable juega un papel central.'},{de:'Die Bedeutung des Regenmantels ist offensichtlich.',es:'La importancia de impermeable es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "paraguas"', exerciseA:'Regenschirm' },
    { id:'a2-2-l3', title:'El cuerpo', topic:'cuerpo', rewardCoins:15, rewardXp:22,
      grammarTip:'Verbos reflexivos: sich waschen, sich fühlen, sich freuen. El reflexivo va en Akkusativ.',
      phrases:[{de:'der Körper ist praktisch.',es:'El/la cuerpo es práctico/a.'},{de:'Ich habe einen Körper.',es:'Tengo un/una cuerpo.'},{de:'Das Körper ist neu.',es:'El/la cuerpo es nuevo/a.'},{de:'das Gesicht ist praktisch.',es:'El/la cara es práctico/a.'},{de:'Ich habe ein Gesicht.',es:'Tengo un/una cara.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Körper' },
    { id:'a2-2-l4', title:'Deportes', topic:'deportes', rewardCoins:15, rewardXp:22,
      grammarTip:'Reflexivos con Dativ: ich wasche mir die Hände. El reflexivo en Dativ, el objeto en Akkusativ.',
      phrases:[{de:'der Zahn ist praktisch.',es:'El/la diente es práctico/a.'},{de:'Ich habe einen Zahn.',es:'Tengo un/una diente.'},{de:'Das Zahn ist neu.',es:'El/la diente es nuevo/a.'},{de:'die Zunge ist praktisch.',es:'El/la lengua es práctico/a.'},{de:'Ich habe eine Zunge.',es:'Tengo un/una lengua.'}],
      exerciseType:'choose', exerciseQ:'___ Zahn ist gut.', exerciseA:'Der',
      options:['Der','Die','Das'], },
    { id:'a2-2-l5', title:'Bienestar', topic:'bienestar', rewardCoins:15, rewardXp:22,
      grammarTip:'Pronombres personales: Nominativ → Dativ → Akkusativ: ich → mir → mich, du → dir → dich...',
      phrases:[{de:'der Rücken ist praktisch.',es:'El/la espalda es práctico/a.'},{de:'Ich habe einen Rücken.',es:'Tengo un/una espalda.'},{de:'Das Rücken ist neu.',es:'El/la espalda es nuevo/a.'},{de:'der Bauch ist praktisch.',es:'El/la vientre es práctico/a.'},{de:'Ich habe einen Bauch.',es:'Tengo un/una vientre.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Rücken"?', exerciseA:'Rücken' },
    { id:'a2-2-l6', title:'Citas médicas', topic:'citas', rewardCoins:15, rewardXp:22,
      grammarTip:'Oraciones temporales con "wenn": Wenn ich Zeit habe, gehe ich ins Kino.',
      phrases:[{de:'das Blut ist praktisch.',es:'El/la sangre es práctico/a.'},{de:'Ich habe ein Blut.',es:'Tengo un/una sangre.'},{de:'Das Blut ist neu.',es:'El/la sangre es nuevo/a.'},{de:'die Krankheit ist praktisch.',es:'El/la enfermedad es práctico/a.'},{de:'Ich habe eine Krankheit.',es:'Tengo un/una enfermedad.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "sangre"', exerciseA:'Blut' },
    { id:'a2-2-l7', title:'Familia y amigos', topic:'familia-amigos', rewardCoins:15, rewardXp:22,
      grammarTip:'Oraciones temporales con "als" (pasado puntual): Als ich Kind war, wohnte ich in Madrid.',
      phrases:[{de:'der Husten ist praktisch.',es:'El/la tos es práctico/a.'},{de:'Ich habe einen Husten.',es:'Tengo un/una tos.'},{de:'Das Husten ist neu.',es:'El/la tos es nuevo/a.'},{de:'die Grippe ist praktisch.',es:'El/la gripe es práctico/a.'},{de:'Ich habe eine Grippe.',es:'Tengo un/una gripe.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Husten"', exerciseA:'tos' },
    { id:'a2-2-l8', title:'Tema: emociones', topic:'emociones', rewardCoins:15, rewardXp:22,
      grammarTip:'Nebensätze con "ob" (si indirecta): Ich weiß nicht, ob er kommt.',
      phrases:[{de:'der Termin ist praktisch.',es:'El/la cita es práctico/a.'},{de:'Ich habe einen Termin.',es:'Tengo un/una cita.'},{de:'Das Termin ist neu.',es:'El/la cita es nuevo/a.'},{de:'das Rezept ist praktisch.',es:'El/la receta médica es práctico/a.'},{de:'Ich habe ein Rezept.',es:'Tengo un/una receta médica.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "cita"', exerciseA:'Termin' },
    { id:'a2-1-l3', title:'Orientación', topic:'orientacion', rewardCoins:15, rewardXp:22,
      grammarTip:'Preposiciones de lugar con Dativ: in, auf, unter, über, neben, zwischen, vor, hinter.',
      phrases:[{de:'der Beruf ist praktisch.',es:'El/la profesión es práctico/a.'},{de:'Ich habe einen Beruf.',es:'Tengo un/una profesión.'},{de:'Das Beruf ist neu.',es:'El/la profesión es nuevo/a.'},{de:'der Angestellte ist praktisch.',es:'El/la empleado es práctico/a.'},{de:'Ich habe einen Angestellte.',es:'Tengo un/una empleado.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Beruf' },
    { id:'a2-1-l4', title:'Billetes y monedas', topic:'billetes', rewardCoins:15, rewardXp:22,
      grammarTip:'Preposiciones de lugar con Akkusativ (movimiento): Ich gehe in die Stadt (Wohin?).',
      phrases:[{de:'der Kollege ist praktisch.',es:'El/la compañero es práctico/a.'},{de:'Ich habe einen Kollege.',es:'Tengo un/una compañero.'},{de:'Das Kollege ist neu.',es:'El/la compañero es nuevo/a.'},{de:'die Firma ist praktisch.',es:'El/la empresa es práctico/a.'},{de:'Ich habe eine Firma.',es:'Tengo un/una empresa.'}],
      exerciseType:'choose', exerciseQ:'___ Kollege ist gut.', exerciseA:'Der',
      options:['Der','Die','Das'], },
    { id:'a2-1-l5', title:'Reservas', topic:'reserva', rewardCoins:15, rewardXp:22,
      grammarTip:'Preposiciones Wechselpräpositionen: in, auf, unter... Dativ (Wo?) / Akkusativ (Wohin?).',
      phrases:[{de:'die Besprechung ist praktisch.',es:'El/la reunión es práctico/a.'},{de:'Ich habe eine Besprechung.',es:'Tengo un/una reunión.'},{de:'Das Besprechung ist neu.',es:'El/la reunión es nuevo/a.'},{de:'die Geschäftsreise ist praktisch.',es:'El/la viaje negocios es práctico/a.'},{de:'Ich habe eine Geschäftsreise.',es:'Tengo un/una viaje negocios.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Besprechung"?', exerciseA:'Besprechungen' },
    { id:'a2-1-l6', title:'Turismo', topic:'turismo', rewardCoins:15, rewardXp:22,
      grammarTip:'Comparativo: schnell → schneller, groß → größer, gut → besser, viel → mehr.',
      phrases:[{de:'der Urlaub ist praktisch.',es:'El/la vacaciones es práctico/a.'},{de:'Ich habe einen Urlaub.',es:'Tengo un/una vacaciones.'},{de:'Das Urlaub ist neu.',es:'El/la vacaciones es nuevo/a.'},{de:'die Reise ist praktisch.',es:'El/la viaje es práctico/a.'},{de:'Ich habe eine Reise.',es:'Tengo un/una viaje.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "vacaciones"', exerciseA:'Urlaub' },
    { id:'a2-1-l7', title:'Equipaje', topic:'equipaje', rewardCoins:15, rewardXp:22,
      grammarTip:'Superlativo: am schnellsten, am größten, am besten, am meisten.',
      phrases:[{de:'das Zimmer ist praktisch.',es:'El/la habitación es práctico/a.'},{de:'Ich habe ein Zimmer.',es:'Tengo un/una habitación.'},{de:'Das Zimmer ist neu.',es:'El/la habitación es nuevo/a.'},{de:'die Reservierung ist praktisch.',es:'El/la reserva es práctico/a.'},{de:'Ich habe eine Reservierung.',es:'Tengo un/una reserva.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Zimmer"', exerciseA:'habitación' },
    { id:'a2-1-l8', title:'Navegación', topic:'navegacion', rewardCoins:15, rewardXp:22,
      grammarTip:'Adjetivos antes del sustantivo: ein guter Freund, eine gute Idee, ein gutes Buch.',
      phrases:[{de:'der Ausweis ist praktisch.',es:'El/la carnet es práctico/a.'},{de:'Ich habe einen Ausweis.',es:'Tengo un/una carnet.'},{de:'Das Ausweis ist neu.',es:'El/la carnet es nuevo/a.'},{de:'das Gepäck ist praktisch.',es:'El/la equipaje es práctico/a.'},{de:'Ich habe ein Gepäck.',es:'Tengo un/una equipaje.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "carnet"', exerciseA:'Ausweis' },
    { id:'a1-4-l2', title:'Tema: general1', topic:'general1', rewardCoins:10, rewardXp:15,
      grammarTip:'Presta atención a la estructura de la oración.',
      phrases:[{de:'das Frühstück spielt eine zentrale Rolle.',es:'El/la desayuno juega un papel central.'},{de:'Die Bedeutung des Frühstücks ist offensichtlich.',es:'La importancia de desayuno es obvia.'},{de:'Wir müssen das Frühstück berücksichtigen.',es:'Debemos considerar desayuno.'},{de:'das Mittagessen spielt eine zentrale Rolle.',es:'El/la comida juega un papel central.'},{de:'Die Bedeutung des Mittagessens ist offensichtlich.',es:'La importancia de comida es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Frühstück' },
    { id:'a1-4-l3', title:'Tema: general2', topic:'general2', rewardCoins:10, rewardXp:15,
      grammarTip:'El verbo conjugado va en segunda posición.',
      phrases:[{de:'die Suppe spielt eine zentrale Rolle.',es:'El/la sopa juega un papel central.'},{de:'Die Bedeutung der Suppes ist offensichtlich.',es:'La importancia de sopa es obvia.'},{de:'Wir müssen die Suppe berücksichtigen.',es:'Debemos considerar sopa.'},{de:'der Salat spielt eine zentrale Rolle.',es:'El/la ensalada juega un papel central.'},{de:'Die Bedeutung des Salats ist offensichtlich.',es:'La importancia de ensalada es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Suppe ist gut.', exerciseA:'Die',
      options:['Der','Die','Das'], },
    { id:'a1-4-l4', title:'Tema: general3', topic:'general3', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'das Gemüse spielt eine zentrale Rolle.',es:'El/la verdura juega un papel central.'},{de:'Die Bedeutung des Gemüses ist offensichtlich.',es:'La importancia de verdura es obvia.'},{de:'Wir müssen das Gemüse berücksichtigen.',es:'Debemos considerar verdura.'},{de:'der Kuchen spielt eine zentrale Rolle.',es:'El/la pastel juega un papel central.'},{de:'Die Bedeutung des Kuchens ist offensichtlich.',es:'La importancia de pastel es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Gemüse"?', exerciseA:'Gemüse' },
    { id:'a1-4-l5', title:'Tema: general4', topic:'general4', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'der Käse spielt eine zentrale Rolle.',es:'El/la queso juega un papel central.'},{de:'Die Bedeutung des Käses ist offensichtlich.',es:'La importancia de queso es obvia.'},{de:'Wir müssen den Käse berücksichtigen.',es:'Debemos considerar queso.'},{de:'die Butter spielt eine zentrale Rolle.',es:'El/la mantequilla juega un papel central.'},{de:'Die Bedeutung der Butters ist offensichtlich.',es:'La importancia de mantequilla es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "queso"', exerciseA:'Käse' },
    { id:'a1-4-l6', title:'Tema: general5', topic:'general5', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'der Zucker spielt eine zentrale Rolle.',es:'El/la azúcar juega un papel central.'},{de:'Die Bedeutung des Zuckers ist offensichtlich.',es:'La importancia de azúcar es obvia.'},{de:'Wir müssen den Zucker berücksichtigen.',es:'Debemos considerar azúcar.'},{de:'das Salz spielt eine zentrale Rolle.',es:'El/la sal juega un papel central.'},{de:'Die Bedeutung des Salzs ist offensichtlich.',es:'La importancia de sal es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Zucker"', exerciseA:'azúcar' },
    { id:'a1-4-l7', title:'Tema: general6', topic:'general6', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'der Essig spielt eine zentrale Rolle.',es:'El/la vinagre juega un papel central.'},{de:'Die Bedeutung des Essigs ist offensichtlich.',es:'La importancia de vinagre es obvia.'},{de:'Wir müssen den Essig berücksichtigen.',es:'Debemos considerar vinagre.'},{de:'das Öl spielt eine zentrale Rolle.',es:'El/la aceite juega un papel central.'},{de:'Die Bedeutung des Öls ist offensichtlich.',es:'La importancia de aceite es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "vinagre"', exerciseA:'Essig' },
    { id:'a1-4-l8', title:'Tema: general1', topic:'general1', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'die Nudeln spielt eine zentrale Rolle.',es:'El/la pasta juega un papel central.'},{de:'Die Bedeutung der Nudelns ist offensichtlich.',es:'La importancia de pasta es obvia.'},{de:'Wir müssen die Nudeln berücksichtigen.',es:'Debemos considerar pasta.'},{de:'die Kartoffel spielt eine zentrale Rolle.',es:'El/la patata juega un papel central.'},{de:'Die Bedeutung der Kartoffels ist offensichtlich.',es:'La importancia de patata es obvia.'}],
      exerciseType:'order', exerciseQ:'Ordena: "Nudeln"', exerciseA:'Nudeln' },
    { id:'a1-3-l3', title:'Tema: general1', topic:'general1', rewardCoins:10, rewardXp:15,
      grammarTip:'Presta atención a la estructura de la oración.',
      phrases:[{de:'der Kopf spielt eine zentrale Rolle.',es:'El/la cabeza juega un papel central.'},{de:'Die Bedeutung des Kopfs ist offensichtlich.',es:'La importancia de cabeza es obvia.'},{de:'Wir müssen den Kopf berücksichtigen.',es:'Debemos considerar cabeza.'},{de:'die Hand spielt eine zentrale Rolle.',es:'El/la mano juega un papel central.'},{de:'Die Bedeutung der Hands ist offensichtlich.',es:'La importancia de mano es obvia.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Kopf' },
    { id:'a1-3-l4', title:'Tema: general2', topic:'general2', rewardCoins:10, rewardXp:15,
      grammarTip:'El verbo conjugado va en segunda posición.',
      phrases:[{de:'der Arm spielt eine zentrale Rolle.',es:'El/la brazo juega un papel central.'},{de:'Die Bedeutung des Arms ist offensichtlich.',es:'La importancia de brazo es obvia.'},{de:'Wir müssen den Arm berücksichtigen.',es:'Debemos considerar brazo.'},{de:'das Bein spielt eine zentrale Rolle.',es:'El/la pierna juega un papel central.'},{de:'Die Bedeutung des Beins ist offensichtlich.',es:'La importancia de pierna es obvia.'}],
      exerciseType:'choose', exerciseQ:'___ Arm ist gut.', exerciseA:'Der',
      options:['Der','Die','Das'], },
    { id:'a1-3-l5', title:'Tema: general3', topic:'general3', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'das Ohr spielt eine zentrale Rolle.',es:'El/la oreja juega un papel central.'},{de:'Die Bedeutung des Ohrs ist offensichtlich.',es:'La importancia de oreja es obvia.'},{de:'Wir müssen das Ohr berücksichtigen.',es:'Debemos considerar oreja.'},{de:'der Mund spielt eine zentrale Rolle.',es:'El/la boca juega un papel central.'},{de:'Die Bedeutung des Munds ist offensichtlich.',es:'La importancia de boca es obvia.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Ohr"?', exerciseA:'Ohren' },
    { id:'a1-3-l6', title:'Tema: general4', topic:'general4', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'das Haar spielt eine zentrale Rolle.',es:'El/la pelo juega un papel central.'},{de:'Die Bedeutung des Haars ist offensichtlich.',es:'La importancia de pelo es obvia.'},{de:'Wir müssen das Haar berücksichtigen.',es:'Debemos considerar pelo.'},{de:'der Arzt spielt eine zentrale Rolle.',es:'El/la médico juega un papel central.'},{de:'Die Bedeutung des Arzts ist offensichtlich.',es:'La importancia de médico es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "pelo"', exerciseA:'Haar' },
    { id:'a1-3-l7', title:'Tema: general5', topic:'general5', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'der Schmerz spielt eine zentrale Rolle.',es:'El/la dolor juega un papel central.'},{de:'Die Bedeutung des Schmerzs ist offensichtlich.',es:'La importancia de dolor es obvia.'},{de:'Wir müssen den Schmerz berücksichtigen.',es:'Debemos considerar dolor.'},{de:'das Fieber spielt eine zentrale Rolle.',es:'El/la fiebre juega un papel central.'},{de:'Die Bedeutung des Fiebers ist offensichtlich.',es:'La importancia de fiebre es obvia.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Schmerz"', exerciseA:'dolor' },
    { id:'a1-3-l8', title:'Tema: general6', topic:'general6', rewardCoins:10, rewardXp:15,
      grammarTip:'Practica el vocabulario nuevo en contexto.',
      phrases:[{de:'das Medikament spielt eine zentrale Rolle.',es:'El/la medicamento juega un papel central.'},{de:'Die Bedeutung des Medikaments ist offensichtlich.',es:'La importancia de medicamento es obvia.'},{de:'Wir müssen das Medikament berücksichtigen.',es:'Debemos considerar medicamento.'},{de:'das Geschäft spielt eine zentrale Rolle.',es:'El/la tienda juega un papel central.'},{de:'Die Bedeutung des Geschäfts ist offensichtlich.',es:'La importancia de tienda es obvia.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "medicamento"', exerciseA:'Medikament' },
    { id:'a1-2-l3', title:'El tiempo', topic:'tiempo', rewardCoins:12, rewardXp:18,
      grammarTip:'Verbos modales: können (poder), müssen (tener que), wollen (querer). Ocupan 2ª posición, el otro verbo al final.',
      phrases:[{de:'die Familie ist praktisch.',es:'El/la familia es práctico/a.'},{de:'Ich habe eine Familie.',es:'Tengo un/una familia.'},{de:'Das Familie ist neu.',es:'El/la familia es nuevo/a.'},{de:'der Freund ist praktisch.',es:'El/la amigo es práctico/a.'},{de:'Ich habe einen Freund.',es:'Tengo un/una amigo.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Familie' },
    { id:'a1-2-l4', title:'Calendario', topic:'calendario', rewardCoins:12, rewardXp:18,
      grammarTip:'Campo: El verbo conjugado siempre en segunda posición en oraciones enunciativas.',
      phrases:[{de:'die Stadt ist praktisch.',es:'El/la ciudad es práctico/a.'},{de:'Ich habe eine Stadt.',es:'Tengo un/una ciudad.'},{de:'Das Stadt ist neu.',es:'El/la ciudad es nuevo/a.'},{de:'das Land ist praktisch.',es:'El/la país es práctico/a.'},{de:'Ich habe ein Land.',es:'Tengo un/una país.'}],
      exerciseType:'choose', exerciseQ:'___ Stadt ist gut.', exerciseA:'Die',
      options:['Der','Die','Das'], },
    { id:'a1-2-l5', title:'El clima', topic:'clima', rewardCoins:12, rewardXp:18,
      grammarTip:'Präteritum de sein/haben: ich war/hatte, du warst/hattest, er war/hatte...',
      phrases:[{de:'der Platz ist praktisch.',es:'El/la plaza es práctico/a.'},{de:'Ich habe einen Platz.',es:'Tengo un/una plaza.'},{de:'Das Platz ist neu.',es:'El/la plaza es nuevo/a.'},{de:'der Zug ist praktisch.',es:'El/la tren es práctico/a.'},{de:'Ich habe einen Zug.',es:'Tengo un/una tren.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Platz"?', exerciseA:'Plätze' },
    { id:'a1-2-l6', title:'De compras', topic:'compras', rewardCoins:12, rewardXp:18,
      grammarTip:'Perfekt con haben: ich habe gemacht, du hast gespielt. Para verbos transitivos.',
      phrases:[{de:'das Auto ist teuer.',es:'El/la coche es caro/a.'},{de:'Ich habe ein Auto.',es:'Tengo un/una coche.'},{de:'Das Auto ist neu.',es:'El/la coche es nuevo/a.'},{de:'das Fahrrad ist teuer.',es:'El/la bicicleta es caro/a.'},{de:'Ich habe ein Fahrrad.',es:'Tengo un/una bicicleta.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "coche"', exerciseA:'Auto' },
    { id:'a1-2-l7', title:'Precios', topic:'precios', rewardCoins:12, rewardXp:18,
      grammarTip:'Perfekt con sein: ich bin gegangen, du bist gefahren. Verbos de movimiento/cambio de estado.',
      phrases:[{de:'der Bahnhof ist praktisch.',es:'El/la estación es práctico/a.'},{de:'Ich habe einen Bahnhof.',es:'Tengo un/una estación.'},{de:'Das Bahnhof ist neu.',es:'El/la estación es nuevo/a.'},{de:'der Flughafen ist praktisch.',es:'El/la aeropuerto es práctico/a.'},{de:'Ich habe einen Flughafen.',es:'Tengo un/una aeropuerto.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Bahnhof"', exerciseA:'estación' },
    { id:'a1-2-l8', title:'En el restaurante', topic:'restaurante', rewardCoins:12, rewardXp:18,
      grammarTip:'Separables: el prefijo va al final. "Ich stehe um 7 Uhr auf" (aufstehen).',
      phrases:[{de:'der Preis ist praktisch.',es:'El/la precio es práctico/a.'},{de:'Ich habe einen Preis.',es:'Tengo un/una precio.'},{de:'Das Preis ist neu.',es:'El/la precio es nuevo/a.'},{de:'die Karte ist praktisch.',es:'El/la tarjeta/mapa es práctico/a.'},{de:'Ich habe eine Karte.',es:'Tengo un/una tarjeta/mapa.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "precio"', exerciseA:'Preis' },
    { id:'a1-1-l4', title:'La familia', topic:'familia', rewardCoins:10, rewardXp:15,
      grammarTip:'Artículos definidos: der (m), die (f), das (n). Memoriza cada sustantivo con su artículo.',
      phrases:[{de:'das Haus ist wichtig.',es:'El/la casa es importante.'},{de:'Ich habe ein Haus.',es:'Tengo un/una casa.'},{de:'Das Haus ist neu.',es:'El/la casa es nuevo/a.'},{de:'der Mann ist wichtig.',es:'El/la hombre es importante.'},{de:'Ich habe einen Mann.',es:'Tengo un/una hombre.'}],
      exerciseType:'fill', exerciseQ:'Der ___ ist wichtig.', exerciseA:'Haus' },
    { id:'a1-1-l5', title:'Números y cantidades', topic:'numeros', rewardCoins:10, rewardXp:15,
      grammarTip:'Plural en -e, -en, -er: der Tisch → die Tische, die Frau → die Frauen, das Kind → die Kinder.',
      phrases:[{de:'das Kind ist praktisch.',es:'El/la niño es práctico/a.'},{de:'Ich habe ein Kind.',es:'Tengo un/una niño.'},{de:'Das Kind ist neu.',es:'El/la niño es nuevo/a.'},{de:'der Tisch ist praktisch.',es:'El/la mesa es práctico/a.'},{de:'Ich habe einen Tisch.',es:'Tengo un/una mesa.'}],
      exerciseType:'choose', exerciseQ:'___ Kind ist gut.', exerciseA:'Das',
      options:['Der','Die','Das'], },
    { id:'a1-1-l6', title:'Colores', topic:'colores', rewardCoins:10, rewardXp:15,
      grammarTip:'Nominativo vs Acusativo: Der Hund ist braun (Nom). Ich sehe den Hund (Akk).',
      phrases:[{de:'die Katze ist praktisch.',es:'El/la gato es práctico/a.'},{de:'Ich habe eine Katze.',es:'Tengo un/una gato.'},{de:'Das Katze ist neu.',es:'El/la gato es nuevo/a.'},{de:'der Hund ist praktisch.',es:'El/la perro es práctico/a.'},{de:'Ich habe einen Hund.',es:'Tengo un/una perro.'}],
      exerciseType:'plural', exerciseQ:'¿Cuál es el plural de "Katze"?', exerciseA:'Katzen' },
    { id:'a1-1-l7', title:'Animales', topic:'animales', rewardCoins:10, rewardXp:15,
      grammarTip:'Verbo "sein" (ser/estar): ich bin, du bist, er/sie/es ist, wir sind, ihr seid, sie sind.',
      phrases:[{de:'das Brot ist praktisch.',es:'El/la pan es práctico/a.'},{de:'Ich habe ein Brot.',es:'Tengo un/una pan.'},{de:'Das Brot ist neu.',es:'El/la pan es nuevo/a.'},{de:'der Name ist praktisch.',es:'El/la nombre es práctico/a.'},{de:'Ich habe einen Name.',es:'Tengo un/una nombre.'}],
      exerciseType:'translateDE', exerciseQ:'Traduce al alemán: "pan"', exerciseA:'Brot' },
    { id:'a1-1-l8', title:'En la escuela', topic:'escuela', rewardCoins:10, rewardXp:15,
      grammarTip:'Verbo "haben" (tener): ich habe, du hast, er/sie/es hat, wir haben, ihr habt, sie haben.',
      phrases:[{de:'die Nacht ist praktisch.',es:'El/la noche es práctico/a.'},{de:'Ich habe eine Nacht.',es:'Tengo un/una noche.'},{de:'Das Nacht ist neu.',es:'El/la noche es nuevo/a.'},{de:'die Woche ist praktisch.',es:'El/la semana es práctico/a.'},{de:'Ich habe eine Woche.',es:'Tengo un/una semana.'}],
      exerciseType:'translateES', exerciseQ:'Traduce al español: "Nacht"', exerciseA:'noche' }
  ['wechselpräpositionen','wechselpräpositionen','','','n'],
  ['geschrieben','geschrieben','','','n'],
  ['verlierende','verlierende','','','n'],
  ['geschlossene','geschlossene','','','n'],
  ['repariertes','repariertes','','','n'],
  ['reparierendes','reparierendes','','','n'],
  ['n-deklination','n-deklination','','','n'],
  ['proporcionalidad','proporcionalidad','','','n'],
  ['ausbildschaft','ausbildschaft','','','n'],
  ['entscheidnis','entscheidnis','','','n'],
  ['entscheidschaft','entscheidschaft','','','n'],
  ['entwickelung','entwickelung','','','n'],
  ['bahnhofshof','bahnhofshof','','','n'],
  ['mißverstanden','mißverstanden','','','n'],
  ['vermißstanden','vermißstanden','','','n'],
  ['katzensprung','katzensprung','','','n'],
  ['aufgebunden','aufgebunden','','','n']
]