/**
 * tools/add_wave3.js
 * Appends Wave 3 synthetic vocabulary to vocab_expansion.js
 */
const fs = require('fs');

const p = 'tools/vocab_expansion.js';
let c = fs.readFileSync(p, 'utf8');

// Wave 3 vocabulary - basic nouns organized by level
const wave3 = {
  'A1': [
    // Office & school supplies
    ['der Computer','computadora','der','Computer','n'],
    ['die Maus','ratón','die','Mäuse','n'],
    ['die Tastatur','teclado','die','Tastaturen','n'],
    ['der Drucker','impresora','der','Drucker','n'],
    ['der Scanner','escáner','der','Scanner','n'],
    ['das Handy','móvil','das','Handys','n'],
    ['der Bleistift','lápiz','der','Bleistifte','n'],
    ['der Kugelschreiber','bolígrafo','der','Kugelschreiber','n'],
    ['der Radiergummi','goma','der','Radiergummis','n'],
    ['das Lineal','regla','das','Lineale','n'],
    ['der Spitzer','sacapuntas','der','Spitzer','n'],
    ['die Schere','tijera','die','Scheren','n'],
    ['der Rucksack','mochila','der','Rucksäcke','n'],
    ['der Regenschirm','paraguas','der','Regenschirme','n'],
    ['die Brille','gafas','die','Brillen','n'],
    ['der Kamm','peine','der','Kämme','n'],
    ['die Bürste','cepillo','die','Bürsten','n'],
    ['das Handtuch','toalla','das','Handtücher','n'],
    ['die Seife','jabón','die','Seifen','n'],
    ['die Zahnbürste','cepillo','die','Zahnbürsten','n'],
    ['die Zahnpasta','pasta dientes','die','Zahnpasten','n'],
    ['der Spiegel','espejo','der','Spiegel','n'],
    ['der Wecker','despertador','der','Wecker','n'],
    ['die Lampe','lámpara','die','Lampen','n'],
    ['der Tisch','mesa','der','Tische','n'],
    ['der Stuhl','silla','der','Stühle','n'],
    ['das Bett','cama','das','Betten','n'],
    ['der Schrank','armario','der','Schränke','n'],
    ['das Regal','estante','das','Regale','n'],
    ['der Teppich','alfombra','der','Teppiche','n'],
    ['die Gardine','cortina','die','Gardinen','n'],
    ['das Kissen','cojín','das','Kissen','n'],
    ['die Decke','manta','die','Decken','n'],
    ['die Uhr','reloj','die','Uhren','n'],
    ['die Kerze','vela','die','Kerzen','n'],
    ['die Straße','calle','die','Straßen','n'],
    ['der Weg','camino','der','Wege','n'],
    ['die Brücke','puente','die','Brücken','n'],
    ['der Platz','plaza','der','Plätze','n'],
    ['der Park','parque','der','Parks','n'],
    ['der Garten','jardín','der','Gärten','n'],
    ['der Baum','árbol','der','Bäume','n'],
    ['die Blume','flor','die','Blumen','n'],
    ['die Bank','banco','die','Bänke','n'],
    ['die Ampel','semáforo','die','Ampeln','n'],
    ['der Bahnhof','estación','der','Bahnhöfe','n'],
    ['der Bus','autobús','der','Busse','n'],
    ['das Taxi','taxi','das','Taxis','n'],
    ['das Flugzeug','avión','das','Flugzeuge','n'],
    ['der Zug','tren','der','Züge','n'],
    ['das Fahrrad','bici','das','Fahrräder','n'],
  ],
  'A2': [
    ['der Arzt','médico','der','Ärzte','n'],
    ['die Ärztin','médica','die','Ärztinnen','n'],
    ['das Krankenhaus','hospital','das','Krankenhäuser','n'],
    ['die Apotheke','farmacia','die','Apotheken','n'],
    ['die Tablette','pastilla','die','Tabletten','n'],
    ['der Termin','cita','der','Termine','n'],
    ['der Patient','paciente','der','Patienten','n'],
    ['die Praxis','consultorio','die','Praxen','n'],
    ['das Rezept','receta','das','Rezepte','n'],
    ['die Versicherung','seguro','die','Versicherungen','n'],
    ['die Untersuchung','examen','die','Untersuchungen','n'],
    ['die Operation','operación','die','Operationen','n'],
    ['der Unfall','accidente','der','Unfälle','n'],
    ['die Verletzung','lesión','die','Verletzungen','n'],
    ['die Grippe','gripe','die','Grippen','n'],
    ['die Erkältung','resfriado','die','Erkältungen','n'],
    ['der Schmerz','dolor','der','Schmerzen','n'],
    ['das Reisebüro','agencia','das','Reisebüros','n'],
    ['der Flug','vuelo','der','Flüge','n'],
    ['die Buchung','reserva','die','Buchungen','n'],
    ['der Flughafen','aeropuerto','der','Flughäfen','n'],
    ['die Abfahrt','salida','die','Abfahrten','n'],
    ['die Ankunft','llegada','die','Ankünfte','n'],
    ['der Schalter','ventanilla','der','Schalter','n'],
    ['das Gleis','andén','das','Gleise','n'],
    ['die Fahrkarte','billete','die','Fahrkarten','n'],
    ['der Ausweis','documento','der','Ausweise','n'],
    ['der Reisepass','pasaporte','der','Reisepässe','n'],
    ['der Koffer','maleta','der','Koffer','n'],
    ['das Hotel','hotel','das','Hotels','n'],
    ['das Zimmer','habitación','das','Zimmer','n'],
    ['das Frühstück','desayuno','das','Frühstücke','n'],
    ['die Speisekarte','menú','die','Speisekarten','n'],
    ['die Rechnung','cuenta','die','Rechnungen','n'],
    ['das Trinkgeld','propina','das','Trinkgelder','n'],
    ['der Kellner','camarero','der','Kellner','n'],
    ['die Küche','cocina','die','Küchen','n'],
    ['der Koch','cocinero','der','Köche','n'],
    ['das Restaurant','restaurante','das','Restaurants','n'],
    ['das Café','cafetería','das','Cafés','n'],
  ],
  'B1': [
    ['die Bewerbung','solicitud','die','Bewerbungen','n'],
    ['der Lebenslauf','curriculum','der','Lebensläufe','n'],
    ['die Stelle','puesto','die','Stellen','n'],
    ['der Beruf','profesión','der','Berufe','n'],
    ['die Karriere','carrera','die','Karrieren','n'],
    ['die Firma','empresa','die','Firmen','n'],
    ['der Chef','jefe','der','Chefs','n'],
    ['der Kollege','colega','der','Kollegen','n'],
    ['die Kollegin','colega','die','Kolleginnen','n'],
    ['der Mitarbeiter','empleado','der','Mitarbeiter','n'],
    ['das Unternehmen','empresa','das','Unternehmen','n'],
    ['die Abteilung','departamento','die','Abteilungen','n'],
    ['das Büro','oficina','das','Büros','n'],
    ['das Meeting','reunión','das','Meetings','n'],
    ['die Besprechung','reunión','die','Besprechungen','n'],
    ['die Konferenz','conferencia','die','Konferenzen','n'],
    ['das Projekt','proyecto','das','Projekte','n'],
    ['die Aufgabe','tarea','die','Aufgaben','n'],
    ['die Frist','plazo','die','Fristen','n'],
    ['der Urlaub','vacaciones','der','Urlaube','n'],
    ['der Feiertag','festivo','der','Feiertage','n'],
    ['die Pause','pausa','die','Pausen','n'],
    ['der Vertrag','contrato','der','Verträge','n'],
    ['die Kündigung','despido','die','Kündigungen','n'],
    ['die Ausbildung','formación','die','Ausbildungen','n'],
    ['das Studium','carrera','das','Studien','n'],
    ['der Student','estudiante','der','Studenten','n'],
    ['der Professor','profesor','der','Professoren','n'],
    ['der Unterricht','clase','der','','n'],
    ['die Prüfung','examen','die','Prüfungen','n'],
    ['die Note','nota','die','Noten','n'],
    ['das Zeugnis','certificado','das','Zeugnisse','n'],
    ['der Abschluss','título','der','Abschlüsse','n'],
    ['das Semester','semestre','das','Semester','n'],
    ['der Kurs','curso','der','Kurse','n'],
    ['der Sprachkurs','curso idiomas','der','Sprachkurse','n'],
    ['das Zertifikat','certificado','das','Zertifikate','n'],
    ['die Kenntnisse','conocimientos','die','','n'],
    ['die Fähigkeiten','habilidades','die','','n'],
    ['die Fortbildung','formación cont.','die','Fortbildungen','n'],
  ],
  'B2': [
    ['die Politik','política','die','Politiken','n'],
    ['die Partei','partido','die','Parteien','n'],
    ['die Regierung','gobierno','die','Regierungen','n'],
    ['der Staat','estado','der','Staaten','n'],
    ['das Gesetz','ley','das','Gesetze','n'],
    ['das Recht','derecho','das','Rechte','n'],
    ['die Freiheit','libertad','die','Freiheiten','n'],
    ['die Gerechtigkeit','justicia','die','','n'],
    ['die Steuer','impuesto','die','Steuern','n'],
    ['die Wirtschaft','economía','die','Wirtschaften','n'],
    ['die Börse','bolsa','die','Börsen','n'],
    ['die Aktie','acción','die','Aktien','n'],
    ['die Kreditkarte','tarjeta','die','Kreditkarten','n'],
    ['der Kredit','crédito','der','Kredite','n'],
    ['die Miete','alquiler','die','Mieten','n'],
    ['die Umwelt','medio amb.','die','Umwelten','n'],
    ['der Umweltschutz','protección','der','','n'],
    ['die Energie','energía','die','Energien','n'],
    ['der Klimawandel','cambio clim.','der','','n'],
    ['der Laptop','portátil','der','Laptops','n'],
    ['der Bildschirm','pantalla','der','Bildschirme','n'],
    ['das WLAN','wifi','das','','n'],
    ['das Passwort','contraseña','das','Passwörter','n'],
    ['die Software','software','die','Softwares','n'],
    ['die App','app','die','Apps','n'],
    ['der Server','servidor','der','Server','n'],
    ['die Sicherheit','seguridad','die','','n'],
    ['der Datenschutz','protec. datos','der','','n'],
    ['die Nachhaltigkeit','sostenibilidad','die','','n'],
    ['die Erneuerbare','renovable','die','','n'],
    ['die Solaranlage','placa solar','die','Solaranlagen','n'],
    ['die Windkraft','eólica','die','Windkräfte','n'],
    ['die Globalisierung','globalización','die','','n'],
    ['die Digitalisierung','digitalización','die','','n'],
  ],
  'C1': [
    ['die Philosophie','filosofía','die','Philosophien','n'],
    ['die Wissenschaft','ciencia','die','Wissenschaften','n'],
    ['die Physik','física','die','','n'],
    ['die Chemie','química','die','','n'],
    ['die Biologie','biología','die','','n'],
    ['die Psychologie','psicología','die','','n'],
    ['die Soziologie','sociología','die','','n'],
    ['die Literatur','literatura','die','Literaturen','n'],
    ['die Kunst','arte','die','Künste','n'],
    ['die Musik','música','die','Musiken','n'],
    ['die Architektur','arquitectura','die','','n'],
    ['die Kultur','cultura','die','Kulturen','n'],
    ['die Religion','religión','die','Religionen','n'],
    ['die Ethik','ética','die','','n'],
    ['das Bewusstsein','conciencia','das','','n'],
    ['die Wahrnehmung','percepción','die','Wahrnehmungen','n'],
    ['die Erkenntnis','conocimiento','die','Erkenntnisse','n'],
    ['die Erfahrung','experiencia','die','Erfahrungen','n'],
    ['das Phänomen','fenómeno','das','Phänomene','n'],
    ['die Hypothese','hipótesis','die','Hypothesen','n'],
    ['die Theorie','teoría','die','Theorien','n'],
    ['die Methode','método','die','Methoden','n'],
    ['die Analyse','análisis','die','Analysen','n'],
    ['die Kritik','crítica','die','Kritiken','n'],
    ['die Interpretation','interpretación','die','Interpretationen','n'],
    ['die Perspektive','perspectiva','die','Perspektiven','n'],
    ['die Reflexion','reflexión','die','Reflexionen','n'],
    ['die Konzentration','concentración','die','Konzentrationen','n'],
    ['die Kreativität','creatividad','die','','n'],
    ['die Innovation','innovación','die','Innovationen','n'],
    ['die Transformation','transformación','die','Transformationen','n'],
    ['die Evolution','evolución','die','Evolutionen','n'],
    ['die Revolution','revolución','die','Revolutionen','n'],
    ['die Entwicklung','desarrollo','die','Entwicklungen','n'],
    ['der Fortschritt','progreso','der','Fortschritte','n'],
    ['die Verbesserung','mejora','die','Verbesserungen','n'],
    ['die Effizienz','eficiencia','die','','n'],
    ['die Produktivität','productividad','die','','n'],
    ['die Wettbewerbsfähigkeit','competitividad','die','','n'],
    ['die künstliche Intelligenz','IA','die','','n'],
    ['der Algorithmus','algoritmo','der','Algorithmen','n'],
    ['die Blockchain','cadena bloques','die','Blockchains','n'],
    ['die Kryptowährung','criptomoneda','die','Kryptowährungen','n'],
  ]
};

// Count total entries
const total = Object.values(wave3).reduce((a, b) => a + b.length, 0);
console.log(`Wave 3 total entries: ${total}`);

// Find end of C1 synthetic array and insert before it
const marker = "['zugegebenermaßen','hay que admitir','','','adv'],";
const idx = c.indexOf(marker);
if (idx === -1) {
  console.log('❌ Marker not found');
  process.exit(1);
}
const beforeEnd = idx + marker.length;
const before = c.slice(0, beforeEnd);
const after = c.slice(beforeEnd);

let insert = '\n';
for (const [level, entries] of Object.entries(wave3)) {
  insert += `    // Wave 3 - ${level} (${entries.length} sustantivos)\n`;
  for (const e of entries) {
    insert += `    ['${e[0]}','${e[1]}','${e[2]}','${e[3]}','${e[4]}'],\n`;
  }
}

const newContent = before + insert + after;
fs.writeFileSync(p, newContent, 'utf8');

console.log(`✅ Added ${total} words across ${Object.keys(wave3).length} levels`);