const fs = require('fs');
const c = fs.readFileSync('src/features/ruta/rutaHelpers.jsx', 'utf8');
const addEnd = c.indexOf('MULLER_RUTA_LEVELS');

// Count words in the original addLevel section
const addSection = c.substring(0, addEnd);
const wordCount = addSection.match(/\['/g) ? addSection.match(/\['/g).length : 0;
console.log('Current word count:', wordCount);

// Build 300 synthetic words spread across levels
const newWords = {};

// A1.1 - A1.4 (expand family, house, food, clothes)
newWords['A1.1'] = [
  ['Geschwister','hermanos','die','Geschwister','n'],
  ['Onkel','tío','der','Onkel','n'],
  ['Tante','tía','die','Tanten','n'],
  ['Großvater','abuelo','der','Großväter','n'],
  ['Großmutter','abuela','die','Großmütter','n'],
  ['Cousin','primo','der','Cousins','n'],
  ['Cousine','prima','die','Cousinen','n'],
  ['Neffe','sobrino','der','Neffen','n'],
  ['Nichte','sobrina','die','Nichten','n'],
  ['Eltern','padres','die','','n'],
  ['Teller','plato','der','Teller','n'],
  ['Tasse','taza','die','Tassen','n'],
  ['Gabel','tenedor','die','Gabeln','n'],
  ['Messer','cuchillo','das','Messer','n'],
  ['Löffel','cuchara','der','Löffel','n'],
  ['Glas','vaso','das','Gläser','n'],
  ['Flasche','botella','die','Flaschen','n'],
  ['Milch','leche','die','','n'],
  ['Käse','queso','der','','n'],
  ['Fleisch','carne','das','','n'],
  ['Obst','fruta','das','','n'],
  ['Salat','ensalada','der','Salate','n'],
  ['Reis','arroz','der','','n'],
  ['Suppe','sopa','die','Suppen','n'],
  ['Ei','huevo','das','Eier','n'],
  ['Fisch','pescado','der','Fische','n'],
  ['Kuchen','pastel','der','Kuchen','n'],
  ['Zucker','azúcar','der','','n'],
  ['Salz','sal','das','','n'],
  ['Butter','mantequilla','die','','n'],
];
newWords['A1.2'] = [
  ['Pullover','jersey','der','Pullover','n'],
  ['Hose','pantalón','die','Hosen','n'],
  ['Schuh','zapato','der','Schuhe','n'],
  ['Rock','falda','der','Röcke','n'],
  ['Mantel','abrigo','der','Mäntel','n'],
  ['Kleid','vestido','das','Kleider','n'],
  ['Jacke','chaqueta','die','Jacken','n'],
  ['Socke','calcetín','die','Socken','n'],
  ['Mütze','gorro','die','Mützen','n'],
  ['Hemd','camisa','das','Hemden','n'],
  ['Uhr','reloj','die','Uhren','n'],
  ['Kette','cadena','die','Ketten','n'],
  ['Armband','brazalete','das','Armbänder','n'],
  ['Handschuh','guante','der','Handschuhe','n'],
  ['Schirm','paraguas','der','Schirme','n'],
  ['Geld','dinero','das','','n'],
  ['Portemonnaie','cartera','das','Portemonnaies','n'],
  ['Handy','móvil','das','Handys','n'],
  ['Schlüssel','llave','der','Schlüssel','n'],
  ['Gepäck','equipaje','das','','n'],
];
newWords['A1.3'] = [
  ['Frühling','primavera','der','','n'],
  ['Sommer','verano','der','','n'],
  ['Herbst','otoño','der','','n'],
  ['Winter','invierno','der','','n'],
  ['Regen','lluvia','der','','n'],
  ['Schnee','nieve','der','','n'],
  ['Nebel','niebla','der','','n'],
  ['Wind','viento','der','','n'],
  ['Gewitter','tormenta','das','Gewitter','n'],
  ['Temperatur','temperatura','die','Temperaturen','n'],
  ['Grad','grado','der','Grade','n'],
  ['warm','cálido','adj','','adj'],
  ['kalt','frío','adj','','adj'],
  ['heiß','caliente','adj','','adj'],
  ['kühl','fresco','adj','','adj'],
  ['regnen','llover','v','','v'],
  ['schneien','nevar','v','','v'],
  ['scheinen','brillar','v','','v'],
  ['wehen','soplar','v','','v'],
  ['wolkig','nublado','adj','','adj'],
  ['sonnig','soleado','adj','','adj'],
  ['windig','ventoso','adj','','adj'],
  ['dunkel','oscuro','adj','','adj'],
  ['hell','claro','adj','','adj'],
  ['wichtig','importante','adj','','adj'],
];
newWords['A1.4'] = [
  ['Kopf','cabeza','der','Köpfe','n'],
  ['Schulter','hombro','die','Schultern','n'],
  ['Hand','mano','die','Hände','n'],
  ['Fuß','pie','der','Füße','n'],
  ['Auge','ojo','das','Augen','n'],
  ['Ohr','oído','das','Ohren','n'],
  ['Mund','boca','der','Münder','n'],
  ['Nase','nariz','die','Nasen','n'],
  ['Finger','dedo','der','Finger','n'],
  ['Knie','rodilla','das','Knie','n'],
  ['gesund','sano','adj','','adj'],
  ['krank','enfermo','adj','','adj'],
  ['müde','cansado','adj','','adj'],
  ['gestern','ayer','adv','','adv'],
  ['heute','hoy','adv','','adv'],
  ['morgen','mañana','adv','','adv'],
  ['dann','entonces','adv','','adv'],
  ['später','más tarde','adv','','adv'],
  ['früher','antes','adv','','adv'],
  ['danach','después','adv','','adv'],
  ['vorher','antes','adv','','adv'],
  ['trotzdem','sin embargo','adv','','adv'],
  ['deshalb','por eso','adv','','adv'],
  ['täglich','diario','adj','','adj'],
];
newWords['A2.1'] = [
  ['Arzt','médico','der','Ärzte','n'],
  ['Krankenhaus','hospital','das','Krankenhäuser','n'],
  ['Praxis','consultorio','die','Praxen','n'],
  ['Termin','cita','der','Termine','n'],
  ['beten','rezar','v','','v'],
  ['schreiben','escribir','v','schreibt','v'],
  ['lesen','leer','v','liest','v'],
  ['rechnen','calcular','v','','v'],
  ['zeichnen','dibujar','v','','v'],
  ['singen','cantar','v','singt','v'],
  ['tanzen','bailar','v','','v'],
  ['malen','pintar','v','','v'],
  ['kochen','cocinar','v','','v'],
  ['backen','hornear','v','backt','v'],
  ['putzen','limpiar','v','','v'],
  ['waschen','lavar','v','wäscht','v'],
  ['rasieren','afeitar','v','','v'],
];
newWords['A2.2'] = [
  ['Bahnhof','estación','der','Bahnhöfe','n'],
  ['Flughafen','aeropuerto','der','Flughäfen','n'],
  ['Haltestelle','parada','die','Haltestellen','n'],
  ['Fahrkarte','billete','die','Fahrkarten','n'],
  ['Abfahrt','salida','die','Abfahrten','n'],
  ['Ankunft','llegada','die','Ankünfte','n'],
  ['Verspätung','retraso','die','Verspätungen','n'],
  ['Gleis','andén','das','Gleise','n'],
  ['Zug','tren','der','Züge','n'],
  ['Bus','autobús','der','Busse','n'],
  ['Flug','vuelo','der','Flüge','n'],
  ['Reisepass','pasaporte','der','Reisepässe','n'],
  ['Zimmer','habitación','das','Zimmer','n'],
  ['Hotel','hotel','das','Hotels','n'],
  ['Reservierung','reserva','die','Reservierungen','n'],
  ['Koffer','maleta','der','Koffer','n'],
  ['Karte','mapa','die','Karten','n'],
];
newWords['A2.3'] = [
  ['Post','correo','die','','n'],
  ['Brief','carta','der','Briefe','n'],
  ['Briefkasten','buzón','der','Briefkästen','n'],
  ['Briefmarke','sello','die','Briefmarken','n'],
  ['Paket','paquete','das','Pakete','n'],
  ['Kreditkarte','tarjeta','die','Kreditkarten','n'],
  ['Bank','banco','die','Banken','n'],
  ['Konto','cuenta','das','Konten','n'],
  ['Geldautomat','cajero','der','Geldautomaten','n'],
  ['Telefonnummer','número','die','Telefonnummern','n'],
  ['Adresse','dirección','die','Adressen','n'],
  ['Unterschrift','firma','die','Unterschriften','n'],
  ['Formular','formulario','das','Formulare','n'],
];
newWords['A2.4'] = [
  ['Fußball','fútbol','der','','n'],
  ['Schwimmbad','piscina','das','Schwimmbäder','n'],
  ['Fahrrad','bicicleta','das','Fahrräder','n'],
  ['Wandern','senderismo','das','','n'],
  ['Turnen','gimnasia','das','','n'],
  ['Laufen','correr','das','','n'],
  ['Spiel','juego','das','Spiele','n'],
  ['gewinnen','ganar','v','gewinnt','v'],
  ['verlieren','perder','v','verliert','v'],
  ['trainieren','entrenar','v','','v'],
  ['Schiedsrichter','árbitro','der','Schiedsrichter','n'],
  ['Mannschaft','equipo','die','Mannschaften','n'],
  ['Tor','gol','das','Tore','n'],
  ['Sieg','victoria','der','Siege','n'],
  ['Pokal','trofeo','der','Pokale','n'],
  ['Medaille','medalla','die','Medaillen','n'],
];
newWords['B1.1'] = [
  ['Feier','fiesta','die','Feiern','n'],
  ['Einladung','invitación','die','Einladungen','n'],
  ['Geschenk','regalo','das','Geschenke','n'],
  ['Geburtstag','cumpleaños','der','Geburtstage','n'],
  ['Hochzeit','boda','die','Hochzeiten','n'],
  ['Feiertag','festivo','der','Feiertage','n'],
  ['Weihnachten','Navidad','das','','n'],
  ['Ostern','Pascua','das','','n'],
  ['Traum','sueño','der','Träume','n'],
  ['Wunsch','deseo','der','Wünsche','n'],
  ['Glück','felicidad','das','','n'],
  ['Hoffnung','esperanza','die','Hoffnungen','n'],
  ['Liebe','amor','die','','n'],
];
newWords['B1.2'] = [
  ['Politik','política','die','','n'],
  ['Gesetz','ley','das','Gesetze','n'],
  ['Regierung','gobierno','die','Regierungen','n'],
  ['Partei','partido','die','Parteien','n'],
  ['Wahl','elección','die','Wahlen','n'],
  ['Stimme','voto','die','Stimmen','n'],
  ['Bürger','ciudadano','der','Bürger','n'],
  ['präsentieren','presentar','v','','v'],
  ['diskutieren','discutir','v','','v'],
  ['demonstrieren','manifestar','v','','v'],
  ['verbieten','prohibir','v','verbietet','v'],
  ['erlauben','permitir','v','','v'],
  ['verhandeln','negociar','v','','v'],
  ['zustimmen','aceptar','v','','v'],
  ['ablehnen','rechazar','v','','v'],
  ['entscheiden','decidir','v','entscheidet','v'],
  ['wählen','elegir','v','wählt','v'],
];
newWords['B1.3'] = [
  ['Umwelt','medio ambiente','die','','n'],
  ['Klima','clima','das','','n'],
  ['Energie','energía','die','Energien','n'],
  ['Solar','solar','die','Solar-','n'],
  ['recyceln','reciclar','v','','v'],
  ['schützen','proteger','v','schützt','v'],
  ['sparen','ahorrar','v','','v'],
  ['verschmutzen','contaminar','v','','v'],
  ['erwärmen','calentar','v','','v'],
  ['Ökologie','ecología','die','','n'],
  ['Natur','naturaleza','die','','n'],
  ['Müll','basura','der','','n'],
  ['Abfall','residuo','der','Abfälle','n'],
  ['Ressource','recurso','die','Ressourcen','n'],
  ['nachhaltig','sostenible','adj','','adj'],
  ['erneuerbar','renovable','adj','','adj'],
  ['giftig','tóxico','adj','','adj'],
  ['biologisch','biológico','adj','','adj'],
];
newWords['B1.4'] = [
  ['Wirtschaft','economía','die','','n'],
  ['Arbeitsmarkt','mercado laboral','der','Arbeitsmärkte','n'],
  ['Gehalt','salario','das','Gehälter','n'],
  ['Steuer','impuesto','die','Steuern','n'],
  ['Rente','jubilación','die','Renten','n'],
  ['Versicherung','seguro','die','Versicherungen','n'],
  ['Vertrag','contrato','der','Verträge','n'],
  ['Projekt','proyecto','das','Projekte','n'],
  ['Aufgabe','tarea','die','Aufgaben','n'],
  ['Bewerbung','solicitud','die','Bewerbungen','n'],
  ['Vorstellungsgespräch','entrevista','das','Vorstellungsgespräche','n'],
  ['Schulung','formación','die','Schulungen','n'],
  ['Firma','empresa','die','Firmen','n'],
  ['Produktion','producción','die','Produktionen','n'],
  ['Handel','comercio','der','','n'],
  ['Dienstleistung','servicio','die','Dienstleistungen','n'],
];
newWords['B2.1'] = [
  ['Gericht','tribunal','das','Gerichte','n'],
  ['Recht','derecho','das','Rechte','n'],
  ['Urteil','sentencia','das','Urteile','n'],
  ['Anwalt','abogado','der','Anwälte','n'],
  ['Richter','juez','der','Richter','n'],
  ['klagen','demandar','v','','v'],
  ['verteidigen','defender','v','','v'],
  ['verurteilen','condenar','v','','v'],
  ['freisprechen','absolver','v','spricht frei','v'],
  ['verstoßen','violar','v','verstößt','v'],
  ['auftreten','aparecer','v','tritt auf','v'],
  ['ausüben','ejercer','v','','v'],
  ['ermitteln','investigar','v','','v'],
  ['überwachen','vigilar','v','','v'],
  ['kontrollieren','controlar','v','','v'],
  ['verwalten','administrar','v','','v'],
];
newWords['B2.2'] = [
  ['Kunst','arte','die','Künste','n'],
  ['Kultur','cultura','die','Kulturen','n'],
  ['Ausstellung','exposición','die','Ausstellungen','n'],
  ['Museum','museo','das','Museen','n'],
  ['Theater','teatro','das','Theater','n'],
  ['Konzert','concierto','das','Konzerte','n'],
  ['Gemälde','pintura','das','Gemälde','n'],
  ['Skulptur','escultura','die','Skulpturen','n'],
  ['Literatur','literatura','die','','n'],
  ['Gedicht','poema','das','Gedichte','n'],
  ['Roman','novela','der','Romane','n'],
  ['Instrument','instrumento','das','Instrumente','n'],
  ['melodisch','melódico','adj','','adj'],
  ['kreativ','creativo','adj','','adj'],
  ['ausdrucksstark','expresivo','adj','','adj'],
  ['inspirieren','inspirar','v','','v'],
  ['malen','pintar','v','','v'],
  ['komponieren','componer','v','','v'],
];
newWords['B2.3'] = [
  ['Wissenschaft','ciencia','die','','n'],
  ['Forschung','investigación','die','Forschungen','n'],
  ['Technologie','tecnología','die','Technologien','n'],
  ['Mikroskop','microscopio','das','Mikroskope','n'],
  ['Versuch','experimento','der','Versuche','n'],
  ['Ergebnis','resultado','das','Ergebnisse','n'],
  ['Methode','método','die','Methoden','n'],
  ['Analyst','analista','der','Analysten','n'],
  ['Kriterium','criterio','das','Kriterien','n'],
  ['Hypothese','hipótesis','die','Hypothesen','n'],
  ['Theorie','teoría','die','Theorien','n'],
  ['Labor','laboratorio','das','Labore','n'],
  ['chemisch','químico','adj','','adj'],
  ['physikalisch','físico','adj','','adj'],
  ['biologisch','biológico','adj','','adj'],
  ['mathematisch','matemático','adj','','adj'],
  ['analysieren','analizar','v','','v'],
  ['untersuchen','examinar','v','','v'],
];
newWords['B2.4'] = [
  ['Führung','liderazgo','die','Führungen','n'],
  ['Management','gestión','das','','n'],
  ['Leitung','dirección','die','Leitungen','n'],
  ['Strategie','estrategia','die','Strategien','n'],
  ['Ziel','objetivo','das','Ziele','n'],
  ['Budget','presupuesto','das','Budgets','n'],
  ['Ressource','recurso','die','Ressourcen','n'],
  ['Effizienz','eficiencia','die','','n'],
  ['Innovation','innovación','die','Innovationen','n'],
  ['Wachstum','crecimiento','das','','n'],
  ['Krise','crisis','die','Krisen','n'],
  ['Lösung','solución','die','Lösungen','n'],
  ['koordinieren','coordinar','v','','v'],
  ['organisieren','organizar','v','','v'],
  ['entscheiden','decidir','v','entscheidet','v'],
  ['beeinflussen','influir','v','','v'],
  ['verantwortlich','responsable','adj','','adj'],
  ['erfolgreich','exitoso','adj','','adj'],
];
newWords['C1.1'] = [
  ['Philosophie','filosofía','die','','n'],
  ['Ethik','ética','die','','n'],
  ['Ästhetik','estética','die','','n'],
  ['Theologie','teología','die','','n'],
  ['psychologisch','psicológico','adj','','adj'],
  ['soziologisch','sociológico','adj','','adj'],
  ['philosophisch','filosófico','adj','','adj'],
  ['historisch','histórico','adj','','adj'],
  ['kritisch','crítico','adj','','adj'],
  ['analytisch','analítico','adj','','adj'],
  ['abstrakt','abstracto','adj','','adj'],
  ['interpretieren','interpretar','v','','v'],
  ['reflektieren','reflexionar','v','','v'],
  ['argumentieren','argumentar','v','','v'],
  ['definieren','definir','v','','v'],
  ['bewerten','evaluar','v','bewertet','v'],
  ['beurteilen','juzgar','v','','v'],
  ['schlussfolgern','concluir','v','','v'],
];
newWords['C1.2'] = [
  ['Globalisierung','globalización','die','','n'],
  ['Migration','migración','die','','n'],
  ['Digitalisierung','digitalización','die','','n'],
  ['Roboter','robot','der','Roboter','n'],
  ['Intelligenz','inteligencia','die','','n'],
  ['künstlich','artificial','adj','','adj'],
  ['ethisch','ético','adj','','adj'],
  ['moralisch','moral','adj','','adj'],
  ['virtuell','virtual','adj','','adj'],
  ['vernetzt','conectado','adj','','adj'],
  ['automatisieren','automatizar','v','','v'],
  ['simulieren','simular','v','','v'],
  ['programmieren','programar','v','','v'],
  ['prognostizieren','pronosticar','v','','v'],
  ['innovativ','innovador','adj','','adj'],
  ['nachhaltig','sostenible','adj','','adj'],
  ['transformieren','transformar','v','','v'],
  ['herausfordern','desafiar','v','fordert heraus','v'],
];

// Build the new level strings
const result = Object.keys(newWords).map(levelId => {
  const words = newWords[levelId];
  const wordsStr = words.map(w => `['${w[0]}','${w[1]}','${w[2]}','${w[3]}','${w[4]}']`).join(',');
  return `addLevel('${levelId}',[${wordsStr}]);`;
});

// Find the insertion point - just before MULLER_RUTA_LEVELS
const lastAddPos = addSection.lastIndexOf(');\n');
if (lastAddPos < 0) {
  console.log('ERROR: Could not find last addLevel() call');
  process.exit(1);
}

// Remove the blank line before MULLER_RUTA_LEVELS if it exists
const insertPoint = c.lastIndexOf('\n', addEnd - 1);
const beforeInsert = c.substring(0, addEnd);
const afterInsert = c.substring(addEnd);
const newContent = beforeInsert + '\n' + result.join('\n') + '\n\n' + afterInsert;

fs.writeFileSync('src/features/ruta/rutaHelpers.jsx', newContent);
console.log('✓ Injected ' + Object.keys(newWords).reduce((sum, k) => sum + newWords[k].length, 0) + ' new words');