/**
 * Generador de vocabulario sintético para niveles con pocas palabras
 * 
 * Niveles que necesitan refuerzo:
 * - A2.3: 177 → 300 (+123)
 * - A2.4: 135 → 300 (+165)
 * - B1.2: 233 → 350 (+117)
 * - B1.3: 87  → 350 (+263)
 * - B1.4: 89  → 350 (+261)
 * - B2.4: 276 → 350 (+74)
 * - C1.2: 310 → 400 (+90)
 * 
 * Genera palabras REALES de alemán siguiendo patrones gramaticales.
 */

const fs = require('fs');

const rutaPath = 'src/features/ruta/rutaHelpers.jsx';

// ─── Palabras existentes ───────────────────────────────────────────────────
const rutaContent = fs.readFileSync(rutaPath, 'utf8');
const existingWords = new Set();
const wordRegex = /\['([^']+)','[^']*','[^']*','[^']*','[^']*'\]/g;
let match;
while ((match = wordRegex.exec(rutaContent)) !== null) {
  existingWords.add(match[1].toLowerCase().trim());
}
console.log(`📝 Palabras existentes en ruta: ${existingWords.size}`);

// ─── VOCABULARIO A2 (A2.3 + A2.4) ─────────────────────────────────────────
// Sustantivos cotidianos + verbos básicos + adjetivos comunes
const a2Vocab = [
  // Sustantivos con artículo (A2 - vida cotidiana extendida)
  ['die Arbeit', 'el trabajo', 'die', '-', 'n'],
  ['der Beruf', 'la profesión', 'der', '-e', 'n'],
  ['das Büro', 'la oficina', 'das', '-s', 'n'],
  ['die Fabrik', 'la fábrica', 'die', '-en', 'n'],
  ['die Firma', 'la empresa', 'die', '-en', 'n'],
  ['der Chef', 'el jefe', 'der', '-s', 'n'],
  ['die Kollegin', 'la colega', 'die', '-nen', 'n'],
  ['der Kollege', 'el colega', 'der', '-n', 'n'],
  ['die Besprechung', 'la reunión', 'die', '-en', 'n'],
  ['die Pause', 'el descanso', 'die', '-n', 'n'],
  ['der Urlaub', 'las vacaciones', 'der', '-e', 'n'],
  ['die Reise', 'el viaje', 'die', '-n', 'n'],
  ['das Hotel', 'el hotel', 'das', '-s', 'n'],
  ['der Flughafen', 'el aeropuerto', 'der', 'ä-e', 'n'],
  ['der Bahnhof', 'la estación', 'der', 'ö-e', 'n'],
  ['die Haltestelle', 'la parada', 'die', '-n', 'n'],
  ['der Bus', 'el autobús', 'der', '-se', 'n'],
  ['die Straßenbahn', 'el tranvía', 'die', '-en', 'n'],
  ['der Zug', 'el tren', 'der', 'ü-e', 'n'],
  ['das Taxi', 'el taxi', 'das', '-s', 'n'],
  ['das Flugzeug', 'el avión', 'das', '-e', 'n'],
  ['das Schiff', 'el barco', 'das', '-e', 'n'],
  ['das Fahrrad', 'la bicicleta', 'das', 'ä-er', 'n'],
  ['die Karte', 'el billete/mapa', 'die', '-n', 'n'],
  ['der Fahrplan', 'el horario', 'der', 'ä-e', 'n'],
  ['der Ausflug', 'la excursión', 'der', 'ü-e', 'n'],
  ['die Fahrkarte', 'el billete', 'die', '-n', 'n'],
  ['der Koffer', 'la maleta', 'der', '-', 'n'],
  ['der Rucksack', 'la mochila', 'der', 'ü-e', 'n'],
  ['das Gepäck', 'el equipaje', 'das', '-', 'n'],
  ['der Bahnsteig', 'el andén', 'der', '-e', 'n'],
  ['der Zoll', 'la aduana', 'der', '-e', 'n'],
  ['der Ausweis', 'el carnet', 'der', '-e', 'n'],
  ['die Grenze', 'la frontera', 'die', '-n', 'n'],
  ['die Stadt', 'la ciudad', 'die', 'ä-e', 'n'],
  ['das Dorf', 'el pueblo', 'das', 'ö-er', 'n'],
  ['die Straße', 'la calle', 'die', '-n', 'n'],
  ['der Platz', 'la plaza', 'der', 'ä-e', 'n'],
  ['das Zentrum', 'el centro', 'das', '-en', 'n'],
  ['die Kirche', 'la iglesia', 'die', '-n', 'n'],
  ['die Schule', 'la escuela', 'die', '-n', 'n'],
  ['die Universität', 'la universidad', 'die', '-en', 'n'],
  ['das Krankenhaus', 'el hospital', 'das', 'ä-er', 'n'],
  ['die Post', 'el correo', 'die', '-en', 'n'],
  ['die Bank', 'el banco', 'die', '-en', 'n'],
  ['das Kino', 'el cine', 'das', '-s', 'n'],
  ['das Theater', 'el teatro', 'das', '-', 'n'],
  ['das Museum', 'el museo', 'das', '-en', 'n'],
  ['die Bibliothek', 'la biblioteca', 'die', '-en', 'n'],
  ['der Park', 'el parque', 'der', '-s', 'n'],
  ['der Garten', 'el jardín', 'der', 'ä-en', 'n'],
  ['die Brücke', 'el puente', 'die', '-n', 'n'],
  ['der Fluss', 'el río', 'der', 'ü-e', 'n'],
  ['der See', 'el lago', 'der', '-n', 'n'],
  ['der Berg', 'la montaña', 'der', '-e', 'n'],
  ['der Wald', 'el bosque', 'der', 'ä-er', 'n'],
  ['das Wetter', 'el tiempo', 'das', '-', 'n'],
  ['die Sonne', 'el sol', 'die', '-n', 'n'],
  ['der Mond', 'la luna', 'der', '-e', 'n'],
  ['der Stern', 'la estrella', 'der', '-e', 'n'],
  ['der Himmel', 'el cielo', 'der', '-', 'n'],
  ['die Wolke', 'la nube', 'die', '-n', 'n'],
  ['der Regen', 'la lluvia', 'der', '-', 'n'],
  ['der Schnee', 'la nieve', 'der', '-', 'n'],
  ['der Wind', 'el viento', 'der', '-e', 'n'],
  ['die Jahreszeit', 'la estación', 'die', '-en', 'n'],
  ['der Frühling', 'la primavera', 'der', '-e', 'n'],
  ['der Sommer', 'el verano', 'der', '-', 'n'],
  ['der Herbst', 'el otoño', 'der', '-e', 'n'],
  ['der Winter', 'el invierno', 'der', '-', 'n'],
  ['der Kalender', 'el calendario', 'der', '-', 'n'],
  ['die Monatskarte', 'el abono mensual', 'die', '-n', 'n'],
  ['die Verspätung', 'el retraso', 'die', '-en', 'n'],
  ['die Abfahrt', 'la salida', 'die', '-en', 'n'],
  ['die Ankunft', 'la llegada', 'die', 'ü-e', 'n'],
  ['der Fahrstuhl', 'el ascensor', 'der', 'ü-e', 'n'],
  ['die Treppe', 'la escalera', 'die', '-n', 'n'],
  ['der Eingang', 'la entrada', 'der', 'ä-e', 'n'],
  ['der Ausgang', 'la salida', 'der', 'ä-e', 'n'],
  ['die Tür', 'la puerta', 'die', '-en', 'n'],
  ['das Fenster', 'la ventana', 'das', '-', 'n'],
  ['der Schlüssel', 'la llave', 'der', '-', 'n'],
  ['die Tasche', 'el bolso', 'die', '-n', 'n'],
  ['der Schirm', 'el paraguas', 'der', '-e', 'n'],
  ['die Brille', 'las gafas', 'die', '-n', 'n'],
  ['die Uhr', 'el reloj', 'die', '-en', 'n'],
  ['die Handtasche', 'el bolso de mano', 'die', '-n', 'n'],
  ['der Geldbeutel', 'la cartera', 'der', '-', 'n'],
  ['der Ausflug', 'la excursión', 'der', 'ü-e', 'n'],
  ['die Party', 'la fiesta', 'die', '-s', 'n'],
  ['das Konzert', 'el concierto', 'das', '-e', 'n'],
  ['die Feier', 'la celebración', 'die', '-n', 'n'],
  ['das Geschenk', 'el regalo', 'das', '-e', 'n'],
  ['die Einladung', 'la invitación', 'die', '-en', 'n'],
  ['der Geburtstag', 'el cumpleaños', 'der', '-e', 'n'],
  ['das Fest', 'la fiesta', 'das', '-e', 'n'],
  ['das Silvester', 'el año nuevo', 'das', '-', 'n'],
  ['Ostern', 'Pascua', 'das', '-', 'n'],
  ['Weihnachten', 'Navidad', 'das', '-', 'n'],
  ['die Mannschaft', 'el equipo', 'die', '-en', 'n'],
  ['der Sport', 'el deporte', 'der', '-e', 'n'],
  ['das Spiel', 'el juego', 'das', '-e', 'n'],
  ['das Stadion', 'el estadio', 'das', '-en', 'n'],
  ['das Schwimmbad', 'la piscina', 'das', 'ä-er', 'n'],
  ['der Fußball', 'el fútbol', 'der', 'ä-e', 'n'],
  ['die Musik', 'la música', 'die', '-', 'n'],
  ['das Lied', 'la canción', 'das', '-er', 'n'],
  ['die Gitarre', 'la guitarra', 'die', '-n', 'n'],
  ['der Computer', 'el ordenador', 'der', '-', 'n'],
  ['der Bildschirm', 'la pantalla', 'der', '-e', 'n'],
  ['die Maus', 'el ratón', 'die', 'ä-e', 'n'],
  ['die Tastatur', 'el teclado', 'die', '-en', 'n'],
  ['das Internet', 'internet', 'das', '-', 'n'],
  ['die E-Mail', 'el correo electrónico', 'die', '-s', 'n'],
  ['die Webseite', 'la página web', 'die', '-n', 'n'],
  ['der Drucker', 'la impresora', 'der', '-', 'n'],
  ['das Handy', 'el móvil', 'das', '-s', 'n'],
  ['der Anruf', 'la llamada', 'der', '-e', 'n'],
  ['die Nummer', 'el número', 'die', '-n', 'n'],
  ['der Zettel', 'la nota/papel', 'der', '-', 'n'],
  ['die Tabelle', 'la tabla', 'die', '-n', 'n'],
  ['die Zeitschrift', 'la revista', 'die', '-en', 'n'],
  ['die Zeitung', 'el periódico', 'die', '-en', 'n'],
  ['der Artikel', 'el artículo', 'der', '-', 'n'],
  ['das Blatt', 'la hoja', 'das', 'ä-er', 'n'],
  ['der Stift', 'el bolígrafo', 'der', '-e', 'n'],
  ['der Bleistift', 'el lápiz', 'der', '-e', 'n'],
  ['der Radiergummi', 'la goma de borrar', 'der', '-s', 'n'],
  ['das Lineal', 'la regla', 'das', '-e', 'n'],
  ['der Ordner', 'la carpeta', 'der', '-', 'n'],
  ['der Hefter', 'el archivador', 'der', '-', 'n'],
  ['die Postleitzahl', 'el código postal', 'die', '-en', 'n'],
  ['die Adresse', 'la dirección', 'die', '-n', 'n'],
  ['der Absender', 'el remitente', 'der', '-', 'n'],
  ['der Empfänger', 'el destinatario', 'der', '-', 'n'],
  ['die Briefmarke', 'el sello', 'die', '-n', 'n'],
  ['der Umschlag', 'el sobre', 'der', 'ü-e', 'n'],
  ['die Packung', 'el paquete', 'die', '-en', 'n'],
  ['das Paket', 'el paquete', 'das', '-e', 'n'],
  ['das Portemonnaie', 'el monedero', 'das', '-s', 'n'],
  ['der Euro', 'el euro', 'der', '-', 'n'],
  ['der Cent', 'el céntimo', 'der', '-', 'n'],
  ['der Preis', 'el precio', 'der', '-e', 'n'],
  ['die Kosten', 'los costes', 'die', '-', 'n'],
  ['das Geld', 'el dinero', 'das', '-er', 'n'],
  ['das Portemonnaie', 'el monedero', 'das', '-s', 'n'],
  ['die Münze', 'la moneda', 'die', '-n', 'n'],
  ['der Schein', 'el billete', 'der', '-e', 'n'],
  ['der Einkauf', 'la compra', 'der', 'ä-e', 'n'],
  ['der Markt', 'el mercado', 'der', 'ä-e', 'n'],
  ['das Geschäft', 'la tienda', 'das', '-e', 'n'],
  ['das Kaufhaus', 'los grandes almacenes', 'das', 'ä-er', 'n'],
  ['die Bäckerei', 'la panadería', 'die', '-en', 'n'],
  ['die Metzgerei', 'la carnicería', 'die', '-en', 'n'],
  ['die Apotheke', 'la farmacia', 'die', '-n', 'n'],
  ['der Supermarkt', 'el supermercado', 'der', 'ä-e', 'n'],
  ['die Kasse', 'la caja', 'die', '-n', 'n'],
  ['der Einkaufswagen', 'el carrito', 'der', '-', 'n'],
  ['der Korb', 'la cesta', 'der', 'ö-e', 'n'],
  ['die Tüte', 'la bolsa', 'die', '-n', 'n'],
  ['die Flasche', 'la botella', 'die', '-n', 'n'],
  ['das Glas', 'el vaso', 'das', 'ä-er', 'n'],
  ['die Tasse', 'la taza', 'die', '-n', 'n'],
  ['der Teller', 'el plato', 'der', '-', 'n'],
  ['der Löffel', 'la cuchara', 'der', '-', 'n'],
  ['die Gabel', 'el tenedor', 'die', '-n', 'n'],
  ['das Messer', 'el cuchillo', 'das', '-', 'n'],
  ['der Topf', 'la olla', 'der', 'ö-e', 'n'],
  ['die Pfanne', 'la sartén', 'die', '-n', 'n'],
  ['die Schüssel', 'el bol', 'die', '-n', 'n'],
  ['der Herd', 'la cocina', 'der', '-e', 'n'],
  ['der Kühlschrank', 'la nevera', 'der', 'ä-e', 'n'],
  ['die Spülmaschine', 'el lavavajillas', 'die', '-n', 'n'],
  ['die Waschmaschine', 'la lavadora', 'die', '-n', 'n'],
  ['der Backofen', 'el horno', 'der', 'ö-ä', 'n'],
  ['die Mikrowelle', 'el microondas', 'die', '-n', 'n'],
  ['der Toaster', 'la tostadora', 'der', '-', 'n'],
  ['das Bügeleisen', 'la plancha', 'das', '-', 'n'],
  ['der Besen', 'la escoba', 'der', '-', 'n'],
  ['der Eimer', 'el cubo', 'der', '-', 'n'],
  ['der Müll', 'la basura', 'der', '-', 'n'],
  ['die Mülltonne', 'el cubo de basura', 'die', '-n', 'n'],
  ['der Putzlappen', 'el trapo', 'der', '-', 'n'],
  ['der Staubsauger', 'la aspiradora', 'der', '-', 'n'],
  ['das Badezimmer', 'el baño', 'das', '-', 'n'],
  ['das Schlafzimmer', 'el dormitorio', 'das', '-', 'n'],
  ['das Wohnzimmer', 'el salón', 'das', '-', 'n'],
  ['die Küche', 'la cocina', 'die', '-n', 'n'],
  ['der Keller', 'el sótano', 'der', '-', 'n'],
  ['der Dachboden', 'el ático/buhardilla', 'der', 'ö-ä', 'n'],
  ['der Balkon', 'el balcón', 'der', '-e', 'n'],
  ['die Garage', 'el garaje', 'die', '-n', 'n'],
  ['der Hof', 'el patio', 'der', 'ö-e', 'n'],
  ['der Rasen', 'el césped', 'der', '-', 'n'],
  ['die Blume', 'la flor', 'die', '-n', 'n'],
  ['der Baum', 'el árbol', 'der', 'ä-e', 'n'],
  ['der Strauch', 'el arbusto', 'der', 'äu-e', 'n'],
  ['das Beet', 'el macizo/cama', 'das', '-e', 'n'],
  ['der Zaun', 'la valla', 'der', 'äu-e', 'n'],
  ['die Hecke', 'el seto', 'die', '-n', 'n'],
  ['das Tor', 'la puerta/portal', 'das', '-e', 'n'],
  ['das Stockwerk', 'el piso', 'das', '-e', 'n'],
  ['der Fußboden', 'el suelo', 'der', 'ö-ä', 'n'],
  ['die Decke', 'el techo/manta', 'die', '-n', 'n'],
  ['die Wand', 'la pared', 'die', 'ä-e', 'n'],
  ['die Ecke', 'la esquina', 'die', '-n', 'n'],
  ['der Spalt', 'la rendija', 'der', '-e', 'n'],
  ['das Regal', 'la estantería', 'das', '-e', 'n'],
  ['der Schrank', 'el armario', 'der', 'ä-e', 'n'],
  ['das Bett', 'la cama', 'das', '-en', 'n'],
  ['der Tisch', 'la mesa', 'der', '-e', 'n'],
  ['der Stuhl', 'la silla', 'der', 'ü-e', 'n'],
  ['das Sofa', 'el sofá', 'das', '-s', 'n'],
  ['der Sessel', 'el sillón', 'der', '-', 'n'],
  ['der Teppich', 'la alfombra', 'der', '-e', 'n'],
  ['die Lampe', 'la lámpara', 'die', '-n', 'n'],
  ['das Bild', 'el cuadro', 'das', '-er', 'n'],
  ['der Spiegel', 'el espejo', 'der', '-', 'n'],
  ['die Vase', 'el jarrón', 'die', '-n', 'n'],
  ['der Vorhang', 'la cortina', 'der', 'ä-e', 'n'],
  ['das Kissen', 'la almohada', 'das', '-', 'n'],
  ['die Decke', 'la manta', 'die', '-n', 'n'],
  ['der Wecker', 'el despertador', 'der', '-', 'n'],
  ['der Kleiderschrank', 'el armario', 'der', 'ä-e', 'n'],
  ['der Bügel', 'la percha', 'der', '-', 'n'],
  ['der Schuh', 'el zapato', 'der', '-e', 'n'],
  ['der Stiefel', 'la bota', 'der', '-', 'n'],
  ['die Socke', 'el calcetín', 'die', '-n', 'n'],
  ['die Hose', 'el pantalón', 'die', '-n', 'n'],
  ['die Jacke', 'la chaqueta', 'die', '-n', 'n'],
  ['der Mantel', 'el abrigo', 'der', 'ä-ä', 'n'],
  ['das Hemd', 'la camisa', 'das', '-en', 'n'],
  ['das T-Shirt', 'la camiseta', 'das', '-s', 'n'],
  ['der Pullover', 'el jersey', 'der', '-', 'n'],
  ['der Rock', 'la falda', 'der', 'ö-e', 'n'],
  ['das Kleid', 'el vestido', 'das', '-er', 'n'],
  ['die Bluse', 'la blusa', 'die', '-n', 'n'],
  ['der Hut', 'el sombrero', 'der', 'ü-e', 'n'],
  ['die Mütze', 'el gorro', 'die', '-n', 'n'],
  ['der Schal', 'la bufanda', 'der', '-s/-e', 'n'],
  ['die Handschuhe', 'los guantes', 'die', '-', 'n'],
  ['der Gürtel', 'el cinturón', 'der', '-', 'n'],
  ['die Krawatte', 'la corbata', 'die', '-n', 'n'],
  ['der Knopf', 'el botón', 'der', 'ö-e', 'n'],
  ['der Reißverschluss', 'la cremallera', 'der', 'ü-e', 'n'],
  ['die Kleidung', 'la ropa', 'die', '-', 'n'],
  ['die Größe', 'la talla', 'die', '-n', 'n'],
  ['die Farbe', 'el color', 'die', '-n', 'n'],
  ['die Seife', 'el jabón', 'die', '-n', 'n'],
  ['das Shampoo', 'el champú', 'das', '-s', 'n'],
  ['das Handtuch', 'la toalla', 'das', 'ü-er', 'n'],
  ['die Bürste', 'el cepillo', 'die', '-n', 'n'],
  ['der Kamm', 'el peine', 'der', 'ä-e', 'n'],
  ['die Zahnbürste', 'el cepillo de dientes', 'die', '-n', 'n'],
  ['die Zahnpasta', 'la pasta de dientes', 'die', '-en', 'n'],
  ['der Rasierer', 'la maquinilla de afeitar', 'der', '-', 'n'],
  ['das Deo', 'el desodorante', 'das', '-s', 'n'],
  ['das Parfüm', 'el perfume', 'das', '-e', 'n'],
  ['die Creme', 'la crema', 'die', '-s', 'n'],
  ['der Föhn', 'el secador', 'der', '-e', 'n'],
  ['der Körper', 'el cuerpo', 'der', '-', 'n'],
  ['der Kopf', 'la cabeza', 'der', 'ö-e', 'n'],
  ['das Gesicht', 'la cara', 'das', '-er', 'n'],
  ['das Auge', 'el ojo', 'das', '-n', 'n'],
  ['die Nase', 'la nariz', 'die', '-n', 'n'],
  ['der Mund', 'la boca', 'der', 'ü-er', 'n'],
  ['das Ohr', 'la oreja', 'das', '-en', 'n'],
  ['der Hals', 'el cuello', 'der', 'ä-e', 'n'],
  ['die Schulter', 'el hombro', 'die', '-n', 'n'],
  ['der Arm', 'el brazo', 'der', '-e', 'n'],
  ['die Hand', 'la mano', 'die', 'ä-e', 'n'],
  ['der Finger', 'el dedo', 'der', '-', 'n'],
  ['das Bein', 'la pierna', 'das', '-e', 'n'],
  ['der Fuß', 'el pie', 'der', 'ü-e', 'n'],
  ['das Knie', 'la rodilla', 'das', '-', 'n'],
  ['der Rücken', 'la espalda', 'der', '-', 'n'],
  ['der Bauch', 'la barriga', 'der', 'äu-e', 'n'],
  ['das Herz', 'el corazón', 'das', '-en', 'n'],
  ['das Blut', 'la sangre', 'das', '-', 'n'],
  ['die Haut', 'la piel', 'die', 'äu-e', 'n'],
  ['der Muskel', 'el músculo', 'der', '-n', 'n'],
  ['der Knochen', 'el hueso', 'der', '-', 'n'],
  ['die Krankheit', 'la enfermedad', 'die', '-en', 'n'],
  ['der Schmerz', 'el dolor', 'der', '-en', 'n'],
  ['der Arzt', 'el médico', 'der', 'ä-e', 'n'],
  ['die Ärztin', 'la médica', 'die', '-nen', 'n'],
  ['die Praxis', 'la consulta', 'die', '-en', 'n'],
  ['das Rezept', 'la receta', 'das', '-e', 'n'],
  ['die Tablette', 'la pastilla', 'die', '-n', 'n'],
  ['die Medizin', 'la medicina', 'die', '-en', 'n'],
  ['die Spritze', 'la inyección', 'die', '-n', 'n'],
  ['die Untersuchung', 'el examen', 'die', '-en', 'n'],
  ['der Termin', 'la cita', 'der', '-e', 'n'],
  ['die Sprechstunde', 'la consulta/horario', 'die', '-n', 'n'],
  ['der Zahnarzt', 'el dentista', 'der', 'ä-e', 'n'],
  ['die Apotheke', 'la farmacia', 'die', '-n', 'n'],
  ['das Fieber', 'la fiebre', 'das', '-', 'n'],
  ['der Husten', 'la tos', 'der', '-', 'n'],
  ['der Schnupfen', 'el catarro', 'der', '-', 'n'],
  ['die Grippe', 'la gripe', 'die', '-n', 'n'],
  ['die Erkältung', 'el resfriado', 'die', '-en', 'n'],
  ['die Allergie', 'la alergia', 'die', '-n', 'n'],
  ['das Pflaster', 'la tirita', 'das', '-', 'n'],
  ['der Verband', 'el vendaje', 'der', 'ä-e', 'n'],
  ['der Krankenwagen', 'la ambulancia', 'der', '-', 'n'],
  ['die Familie', 'la familia', 'die', '-n', 'n'],
  ['der Vater', 'el padre', 'der', 'ä-', 'n'],
  ['die Mutter', 'la madre', 'die', 'ü-', 'n'],
  ['der Sohn', 'el hijo', 'der', 'ö-e', 'n'],
  ['die Tochter', 'la hija', 'die', 'ö-', 'n'],
  ['der Bruder', 'el hermano', 'der', 'ü-', 'n'],
  ['die Schwester', 'la hermana', 'die', '-n', 'n'],
  ['der Onkel', 'el tío', 'der', '-', 'n'],
  ['die Tante', 'la tía', 'die', '-n', 'n'],
  ['der Cousin', 'el primo', 'der', '-s', 'n'],
  ['die Cousine', 'la prima', 'die', '-n', 'n'],
  ['der Opa', 'el abuelo', 'der', '-s', 'n'],
  ['die Oma', 'la abuela', 'die', '-s', 'n'],
  ['der Enkel', 'el nieto', 'der', '-', 'n'],
  ['die Enkelin', 'la nieta', 'die', '-nen', 'n'],
  ['der Neffe', 'el sobrino', 'der', '-n', 'n'],
  ['die Nichte', 'la sobrina', 'die', '-n', 'n'],
  ['der Mann', 'el marido', 'der', 'ä-er', 'n'],
  ['die Frau', 'la mujer/esposa', 'die', '-en', 'n'],
  ['der Freund', 'el amigo', 'der', '-e', 'n'],
  ['die Freundin', 'la amiga', 'die', '-nen', 'n'],
  ['der Nachbar', 'el vecino', 'der', '-n', 'n'],
  ['die Nachbarin', 'la vecina', 'die', '-nen', 'n'],
  ['der Gast', 'el invitado', 'der', 'ä-e', 'n'],
  ['der Besuch', 'la visita', 'der', '-e', 'n'],
  ['der Name', 'el nombre', 'der', '-n', 'n'],
  ['der Vorname', 'el nombre de pila', 'der', '-n', 'n'],
  ['der Nachname', 'el apellido', 'der', '-n', 'n'],
  ['die Unterschrift', 'la firma', 'die', '-en', 'n'],
  ['der Wohnort', 'el lugar de residencia', 'der', '-e', 'n'],
  ['die Nachricht', 'la noticia/mensaje', 'die', '-en', 'n'],
  ['die Frage', 'la pregunta', 'die', '-n', 'n'],
  ['die Antwort', 'la respuesta', 'die', '-en', 'n'],
  ['der Satz', 'la oración', 'der', 'ä-e', 'n'],
  ['der Buchstabe', 'la letra', 'der', '-n', 'n'],
  ['das Wort', 'la palabra', 'das', 'ö-er', 'n'],
  ['der Traum', 'el sueño', 'der', 'äu-e', 'n'],
  ['die Idee', 'la idea', 'die', '-n', 'n'],
  ['der Wunsch', 'el deseo', 'der', 'ü-e', 'n'],
  ['der Plan', 'el plan', 'der', 'ä-e', 'n'],
  ['das Ziel', 'la meta', 'das', '-e', 'n'],
  ['die Hoffnung', 'la esperanza', 'die', '-en', 'n'],
  ['die Angst', 'el miedo', 'die', 'ä-e', 'n'],
  ['die Freude', 'la alegría', 'die', '-n', 'n'],
  ['der Spaß', 'la diversión', 'der', '-e', 'n'],
  ['das Glück', 'la suerte', 'das', '-', 'n'],
  ['die Liebe', 'el amor', 'die', '-n', 'n'],
  ['der Hass', 'el odio', 'der', '-', 'n'],
  ['die Wut', 'la ira', 'die', '-', 'n'],
  ['die Ruhe', 'la tranquilidad', 'die', '-', 'n'],
  ['die Geduld', 'la paciencia', 'die', '-', 'n'],
  ['der Mut', 'el valor', 'der', '-', 'n'],
  ['die Ordnung', 'el orden', 'die', '-en', 'n'],
  ['das Chaos', 'el caos', 'das', '-', 'n'],
  ['die Wahrheit', 'la verdad', 'die', '-en', 'n'],
  ['die Lüge', 'la mentira', 'die', '-n', 'n'],
  ['das Recht', 'el derecho', 'das', '-e', 'n'],
  ['die Pflicht', 'el deber', 'die', '-en', 'n'],
  ['die Regel', 'la regla', 'die', '-n', 'n'],
  ['der Befehl', 'la orden', 'der', '-e', 'n'],
  ['das Gesetz', 'la ley', 'das', '-e', 'n'],
  ['die Strafe', 'el castigo', 'die', '-n', 'n'],
  ['die Belohnung', 'la recompensa', 'die', '-en', 'n'],
  ['das Gefühl', 'el sentimiento', 'das', '-e', 'n'],
  ['die Laune', 'el humor', 'die', '-n', 'n'],
  ['der Respekt', 'el respeto', 'der', '-e', 'n'],
  ['das Vertrauen', 'la confianza', 'das', '-', 'n'],
  ['der Zweifel', 'la duda', 'der', '-', 'n'],
  ['die Überraschung', 'la sorpresa', 'die', '-en', 'n'],
  ['das Vergnügen', 'el placer', 'das', '-', 'n'],
  ['der Ärger', 'el enfado', 'der', '-', 'n'],
  ['die Enttäuschung', 'la decepción', 'die', '-en', 'n'],
  ['die Sorge', 'la preocupación', 'die', '-n', 'n'],
  ['die Sehnsucht', 'la nostalgia/anhelo', 'die', 'ü-e', 'n'],
  // Verbos A2
  ['putzen', 'limpiar', '', '', 'v'],
  ['waschen', 'lavar', '', '', 'v'],
  ['kochen', 'cocinar', '', '', 'v'],
  ['backen', 'hornear', '', '', 'v'],
  ['braten', 'freír', '', '', 'v'],
  ['schneiden', 'cortar', '', '', 'v'],
  ['mischen', 'mezclar', '', '', 'v'],
  ['füllen', 'llenar', '', '', 'v'],
  ['gießen', 'regar/verter', '', '', 'v'],
  ['decken', 'cubrir', '', '', 'v'],
  ['duschen', 'ducharse', '', '', 'v'],
  ['baden', 'bañarse', '', '', 'v'],
  ['sich waschen', 'lavarse', '', '', 'v'],
  ['sich anziehen', 'vestirse', '', '', 'v'],
  ['sich ausziehen', 'desvestirse', '', '', 'v'],
  ['aufräumen', 'ordenar', '', '', 'v'],
  ['abwaschen', 'fregar', '', '', 'v'],
  ['aufhängen', 'colgar', '', '', 'v'],
  ['einräumen', 'colocar', '', '', 'v'],
  ['ausräumen', 'vaciar', '', '', 'v'],
  ['bügeln', 'planchar', '', '', 'v'],
  ['nähen', 'coser', '', '', 'v'],
  ['stricken', 'tejer', '', '', 'v'],
  ['basteln', 'hacer manualidades', '', '', 'v'],
  ['malen', 'pintar', '', '', 'v'],
  ['zeichnen', 'dibujar', '', '', 'v'],
  ['fotografieren', 'fotografiar', '', '', 'v'],
  ['filmen', 'filmar', '', '', 'v'],
  ['wandern', 'hacer senderismo', '', '', 'v'],
  ['reiten', 'montar a caballo', '', '', 'v'],
  ['segeln', 'navegar', '', '', 'v'],
  ['angeln', 'pescar', '', '', 'v'],
  ['joggen', 'correr', '', '', 'v'],
  ['klettern', 'escalar', '', '', 'v'],
  ['skaten', 'patinar', '', '', 'v'],
  ['radfahren', 'ir en bici', '', '', 'v'],
  ['reisen', 'viajar', '', '', 'v'],
  ['übernachten', 'pasar la noche', '', '', 'v'],
  ['buchen', 'reservar', '', '', 'v'],
  ['stornieren', 'cancelar', '', '', 'v'],
  ['einchecken', 'facturar', '', '', 'v'],
  ['auschecken', 'salir del hotel', '', '', 'v'],
  ['packen', 'hacer la maleta', '', '', 'v'],
  ['auspacken', 'deshacer la maleta', '', '', 'v'],
  ['einpacken', 'empacar', '', '', 'v'],
  ['umsteigen', 'transbordar', '', '', 'v'],
  ['abfahren', 'salir', '', '', 'v'],
  ['ankommen', 'llegar', '', '', 'v'],
  ['einsteigen', 'subir', '', '', 'v'],
  ['aussteigen', 'bajar', '', '', 'v'],
  ['abholen', 'recoger', '', '', 'v'],
  ['bringen', 'traer', '', '', 'v'],
  ['abgeben', 'entregar', '', '', 'v'],
  ['einwerfen', 'echar', '', '', 'v'],
  ['unterschreiben', 'firmar', '', '', 'v'],
  ['verlieren', 'perder', '', '', 'v'],
  ['finden', 'encontrar', '', '', 'v'],
  ['suchen', 'buscar', '', '', 'v'],
  ['zeigen', 'mostrar', '', '', 'v'],
  ['erzählen', 'contar', '', '', 'v'],
  ['beschreiben', 'describir', '', '', 'v'],
  ['erklären', 'explicar', '', '', 'v'],
  ['fragen', 'preguntar', '', '', 'v'],
  ['antworten', 'responder', '', '', 'v'],
  ['bitten', 'pedir (un favor)', '', '', 'v'],
  ['danken', 'agradecer', '', '', 'v'],
  ['wünschen', 'desear', '', '', 'v'],
  ['hoffen', 'esperar', '', '', 'v'],
  ['glauben', 'creer', '', '', 'v'],
  ['meinen', 'opinar', '', '', 'v'],
  ['denken', 'pensar', '', '', 'v'],
  ['vergessen', 'olvidar', '', '', 'v'],
  ['erinnern', 'recordar', '', '', 'v'],
  ['lernen', 'aprender', '', '', 'v'],
  ['studieren', 'estudiar', '', '', 'v'],
  ['üben', 'practicar', '', '', 'v'],
  ['wiederholen', 'repetir', '', '', 'v'],
  ['verstehen', 'entender', '', '', 'v'],
  ['wissen', 'saber', '', '', 'v'],
  ['kennen', 'conocer', '', '', 'v'],
  ['können', 'poder/saber', '', '', 'v'],
  ['müssen', 'tener que', '', '', 'v'],
  ['dürfen', 'poder (permiso)', '', '', 'v'],
  ['sollen', 'deber', '', '', 'v'],
  ['wollen', 'querer', '', '', 'v'],
  ['mögen', 'gustar', '', '', 'v'],
  ['feiern', 'celebrar', '', '', 'v'],
  ['tanzen', 'bailar', '', '', 'v'],
  ['singen', 'cantar', '', '', 'v'],
  ['spielen', 'jugar/tocar', '', '', 'v'],
  ['gewinnen', 'ganar', '', '', 'v'],
  ['verlieren', 'perder', '', '', 'v'],
  ['trainieren', 'entrenar', '', '', 'v'],
  ['einladen', 'invitar', '', '', 'v'],
  ['schenken', 'regalar', '', '', 'v'],
  ['bekommen', 'recibir', '', '', 'v'],
  ['anrufen', 'llamar', '', '', 'v'],
  ['abschicken', 'enviar', '', '', 'v'],
  ['empfangen', 'recibir', '', '', 'v'],
  ['drucken', 'imprimir', '', '', 'v'],
  ['löschen', 'borrar', '', '', 'v'],
  ['speichern', 'guardar', '', '', 'v'],
  ['kopieren', 'copiar', '', '', 'v'],
  ['reparieren', 'reparar', '', '', 'v'],
  ['kaputtmachen', 'romper', '', '', 'v'],
  ['wegwerfen', 'tirar', '', '', 'v'],
  ['aufheben', 'guardar/conservar', '', '', 'v'],
  ['probieren', 'probar', '', '', 'v'],
  ['passieren', 'pasar/suceder', '', '', 'v'],
  ['stimmen', 'ser correcto', '', '', 'v'],
  ['fehlen', 'faltar', '', '', 'v'],
  ['reichen', 'bastar', '', '', 'v'],
  ['kosten', 'costar', '', '', 'v'],
  ['bezahlen', 'pagar', '', '', 'v'],
  ['sparen', 'ahorrar', '', '', 'v'],
  ['leihen', 'prestar', '', '', 'v'],
  ['tauschen', 'intercambiar', '', '', 'v'],
  ['bestellen', 'pedir', '', '', 'v'],
  ['empfehlen', 'recomendar', '', '', 'v'],
  ['auswählen', 'seleccionar', '', '', 'v'],
  ['probegieren', 'probarse', '', '', 'v'],
  ['anprobieren', 'probarse', '', '', 'v'],
  ['passen', 'quedar bien', '', '', 'v'],
  ['stehen', 'quedar (ropa)', '', '', 'v'],
  ['gefallen', 'gustar', '', '', 'v'],
  ['öffnen', 'abrir', '', '', 'v'],
  ['schließen', 'cerrar', '', '', 'v'],
  ['zumachen', 'cerrar', '', '', 'v'],
  ['aufmachen', 'abrir', '', '', 'v'],
  ['anmachen', 'encender', '', '', 'v'],
  ['ausmachen', 'apagar', '', '', 'v'],
  ['einschalten', 'encender', '', '', 'v'],
  ['ausschalten', 'apagar', '', '', 'v'],
  ['wohnen', 'vivir', '', '', 'v'],
  ['mieten', 'alquilar', '', '', 'v'],
  ['vermieten', 'alquilar (ser dueño)', '', '', 'v'],
  ['einziehen', 'mudarse', '', '', 'v'],
  ['ausziehen', 'mudarse', '', '', 'v'],
  ['renovieren', 'renovar', '', '', 'v'],
  ['streichen', 'pintar', '', '', 'v'],
  ['kleben', 'pegar', '', '', 'v'],
  ['nageln', 'clavar', '', '', 'v'],
  ['schrauben', 'atornillar', '', '', 'v'],
  ['basteln', 'hacer bricolaje', '', '', 'v'],
  ['parken', 'aparcar', '', '', 'v'],
  ['tanken', 'echar gasolina', '', '', 'v'],
  ['reparieren', 'arreglar', '', '', 'v'],
  ['laden', 'cargar', '', '', 'v'],
  ['starten', 'arrancar', '', '', 'v'],
  ['stoppen', 'parar', '', '', 'v'],
  ['blühen', 'florecer', '', '', 'v'],
  ['wachsen', 'crecer', '', '', 'v'],
  ['gießen', 'regar', '', '', 'v'],
  ['ernten', 'cosechar', '', '', 'v'],
  ['pflanzen', 'plantar', '', '', 'v'],
  ['graben', 'cavar', '', '', 'v'],
  ['jäten', 'desherbar', '', '', 'v'],
  ['mähen', 'segar', '', '', 'v'],
  ['regnen', 'llover', '', '', 'v'],
  ['schneien', 'nevar', '', '', 'v'],
  ['donnern', 'tronar', '', '', 'v'],
  ['blitzen', 'relampaguear', '', '', 'v'],
  ['frieren', 'tener frío', '', '', 'v'],
  ['tauen', 'derretirse', '', '', 'v'],
  ['scheinen', 'brillar', '', '', 'v'],
  ['wehen', 'soplar', '', '', 'v'],
  // Adjetivos A2
  ['hungrig', 'hambriento', '', '', 'adj'],
  ['durstig', 'sediento', '', '', 'adj'],
  ['müde', 'cansado', '', '', 'adj'],
  ['wach', 'despierto', '', '', 'adj'],
  ['krank', 'enfermo', '', '', 'adj'],
  ['gesund', 'sano', '', '', 'adj'],
  ['fit', 'en forma', '', '', 'adj'],
  ['schlank', 'delgado', '', '', 'adj'],
  ['dick', 'gordo', '', '', 'adj'],
  ['jung', 'joven', '', '', 'adj'],
  ['alt', 'viejo', '', '', 'adj'],
  ['hübsch', 'guapo', '', '', 'adj'],
  ['hässlich', 'feo', '', '', 'adj'],
  ['stark', 'fuerte', '', '', 'adj'],
  ['schwach', 'débil', '', '', 'adj'],
  ['fleißig', 'trabajador', '', '', 'adj'],
  ['faul', 'perezoso', '', '', 'adj'],
  ['ehrlich', 'honesto', '', '', 'adj'],
  ['höflich', 'cortés', '', '', 'adj'],
  ['freundlich', 'amable', '', '', 'adj'],
  ['nett', 'simpático', '', '', 'adj'],
  ['böse', 'malo/enfadado', '', '', 'adj'],
  ['lustig', 'divertido', '', '', 'adj'],
  ['traurig', 'triste', '', '', 'adj'],
  ['glücklich', 'feliz', '', '', 'adj'],
  ['ärgerlich', 'enfadado', '', '', 'adj'],
  ['zufrieden', 'satisfecho', '', '', 'adj'],
  ['aufgeregt', 'emocionado', '', '', 'adj'],
  ['ruhig', 'tranquilo', '', '', 'adj'],
  ['laut', 'ruidoso', '', '', 'adj'],
  ['leise', 'silencioso', '', '', 'adj'],
  ['schnell', 'rápido', '', '', 'adv'],
  ['langsam', 'lento', '', '', 'adj'],
  ['weit', 'lejos', '', '', 'adj'],
  ['nah', 'cerca', '', '', 'adj'],
  ['hoch', 'alto', '', '', 'adj'],
  ['tief', 'profundo', '', '', 'adj'],
  ['breit', 'ancho', '', '', 'adj'],
  ['eng', 'estrecho', '', '', 'adj'],
  ['dick', 'grueso', '', '', 'adj'],
  ['dünn', 'fino', '', '', 'adj'],
  ['hart', 'duro', '', '', 'adj'],
  ['weich', 'blando', '', '', 'adj'],
  ['schwer', 'pesado/difícil', '', '', 'adj'],
  ['leicht', 'ligero/fácil', '', '', 'adj'],
  ['warm', 'caliente', '', '', 'adj'],
  ['kalt', 'frío', '', '', 'adj'],
  ['heiß', 'caluroso', '', '', 'adj'],
  ['kühl', 'fresco', '', '', 'adj'],
  ['sauber', 'limpio', '', '', 'adj'],
  ['schmutzig', 'sucio', '', '', 'adj'],
  ['neu', 'nuevo', '', '', 'adj'],
  ['alt', 'viejo', '', '', 'adj'],
  ['modern', 'moderno', '', '', 'adj'],
  ['kaputt', 'roto', '', '', 'adj'],
  ['ganz', 'entero', '', '', 'adj'],
  ['halb', 'medio', '', '', 'adj'],
  ['billig', 'barato', '', '', 'adj'],
  ['teuer', 'caro', '', '', 'adj'],
  ['kostenlos', 'gratis', '', '', 'adj'],
  ['wichtig', 'importante', '', '', 'adj'],
  ['richtig', 'correcto', '', '', 'adj'],
  ['falsch', 'incorrecto', '', '', 'adj'],
  ['möglich', 'posible', '', '', 'adj'],
  ['nötig', 'necesario', '', '', 'adj'],
  ['fertig', 'listo/terminado', '', '', 'adj'],
  ['frei', 'libre', '', '', 'adj'],
  ['besetzt', 'ocupado', '', '', 'adj'],
  ['offen', 'abierto', '', '', 'adj'],
  ['geschlossen', 'cerrado', '', '', 'adj'],
  ['sicher', 'seguro', '', '', 'adj'],
  ['gefährlich', 'peligroso', '', '', 'adj'],
  ['einfach', 'sencillo', '', '', 'adj'],
  ['schwierig', 'difícil', '', '', 'adj'],
  ['kompliziert', 'complicado', '', '', 'adj'],
  ['lang', 'largo', '', '', 'adj'],
  ['kurz', 'corto', '', '', 'adj'],
  ['groß', 'grande', '', '', 'adj'],
  ['klein', 'pequeño', '', '', 'adj'],
  ['niedrig', 'bajo', '', '', 'adj'],
  ['dunkel', 'oscuro', '', '', 'adj'],
  ['hell', 'claro', '', '', 'adj'],
  ['bunt', 'colorido', '', '', 'adj'],
  ['trocken', 'seco', '', '', 'adj'],
  ['nass', 'mojado', '', '', 'adj'],
  ['weich', 'suave', '', '', 'adj'],
  ['rau', 'áspero', '', '', 'adj'],
  ['glatt', 'liso', '', '', 'adj'],
  ['rund', 'redondo', '', '', 'adj'],
  ['spitz', 'afilado', '', '', 'adj'],
  ['stumpf', 'romo', '', '', 'adj'],
];

// ─── VOCABULARIO B1 ─────────────────────────────────────────────────────────
const b1Vocab = [
  // Abstractos B1
  ['die Meinung', 'la opinión', 'die', '-en', 'n'],
  ['die Entscheidung', 'la decisión', 'die', '-en', 'n'],
  ['die Entwicklung', 'el desarrollo', 'die', '-en', 'n'],
  ['die Beziehung', 'la relación', 'die', '-en', 'n'],
  ['die Erfahrung', 'la experiencia', 'die', '-en', 'n'],
  ['die Möglichkeit', 'la posibilidad', 'die', '-en', 'n'],
  ['die Schwierigkeit', 'la dificultad', 'die', '-en', 'n'],
  ['die Lösung', 'la solución', 'die', '-en', 'n'],
  ['die Verbindung', 'la conexión', 'die', '-en', 'n'],
  ['die Bedeutung', 'el significado', 'die', '-en', 'n'],
  ['die Erwartung', 'la expectativa', 'die', '-en', 'n'],
  ['die Vorstellung', 'la imaginación', 'die', '-en', 'n'],
  ['die Erinnerung', 'el recuerdo', 'die', '-en', 'n'],
  ['die Absicht', 'la intención', 'die', '-en', 'n'],
  ['die Behandlung', 'el tratamiento', 'die', '-en', 'n'],
  ['die Bemühung', 'el esfuerzo', 'die', '-en', 'n'],
  ['die Bereitschaft', 'la disposición', 'die', '-en', 'n'],
  ['die Beschreibung', 'la descripción', 'die', '-en', 'n'],
  ['die Bestätigung', 'la confirmación', 'die', '-en', 'n'],
  ['die Beteiligung', 'la participación', 'die', '-en', 'n'],
  ['die Betreuung', 'el cuidado', 'die', '-en', 'n'],
  ['die Bewegung', 'el movimiento', 'die', '-en', 'n'],
  ['die Beziehung', 'la relación', 'die', '-en', 'n'],
  ['die Bildung', 'la formación', 'die', '-en', 'n'],
  ['die Darstellung', 'la representación', 'die', '-en', 'n'],
  ['die Definition', 'la definición', 'die', '-en', 'n'],
  ['die Diskussion', 'la discusión', 'die', '-en', 'n'],
  ['die Durchführung', 'la realización', 'die', '-en', 'n'],
  ['die Einstellung', 'la actitud', 'die', '-en', 'n'],
  ['die Entfernung', 'la distancia', 'die', '-en', 'n'],
  ['die Entschuldigung', 'la disculpa', 'die', '-en', 'n'],
  ['die Erfindung', 'el invento', 'die', '-en', 'n'],
  ['die Erklärung', 'la explicación', 'die', '-en', 'n'],
  ['die Ernährung', 'la alimentación', 'die', '-en', 'n'],
  ['die Erziehung', 'la educación', 'die', '-en', 'n'],
  ['die Fähigkeit', 'la capacidad', 'die', '-en', 'n'],
  ['die Forschung', 'la investigación', 'die', '-en', 'n'],
  ['die Freiheit', 'la libertad', 'die', '-en', 'n'],
  ['die Garantie', 'la garantía', 'die', '-n', 'n'],
  ['die Gefahr', 'el peligro', 'die', '-en', 'n'],
  ['die Gelegenheit', 'la oportunidad', 'die', '-en', 'n'],
  ['die Gemeinschaft', 'la comunidad', 'die', '-en', 'n'],
  ['die Generation', 'la generación', 'die', '-en', 'n'],
  ['die Gesellschaft', 'la sociedad', 'die', '-en', 'n'],
  ['die Gewalt', 'la violencia', 'die', '-', 'n'],
  ['die Gewohnheit', 'la costumbre', 'die', '-en', 'n'],
  ['die Grenze', 'el límite', 'die', '-n', 'n'],
  ['die Grundlage', 'la base', 'die', '-n', 'n'],
  ['die Hälfte', 'la mitad', 'die', '-n', 'n'],
  ['die Handlung', 'la acción', 'die', '-en', 'n'],
  ['die Herausforderung', 'el desafío', 'die', '-en', 'n'],
  ['die Herkunft', 'el origen', 'die', '-e', 'n'],
  ['die Initiative', 'la iniciativa', 'die', '-n', 'n'],
  ['die Kenntnis', 'el conocimiento', 'die', '-se', 'n'],
  ['die Kommunikation', 'la comunicación', 'die', '-en', 'n'],
  ['die Konkurrenz', 'la competencia', 'die', '-en', 'n'],
  ['die Kontrolle', 'el control', 'die', '-n', 'n'],
  ['die Kultur', 'la cultura', 'die', '-en', 'n'],
  ['die Kunst', 'el arte', 'die', '-e', 'n'],
  ['die Lage', 'la situación', 'die', '-n', 'n'],
  ['die Leistung', 'el rendimiento', 'die', '-en', 'n'],
  ['die Leitung', 'la dirección', 'die', '-en', 'n'],
  ['die Maßnahme', 'la medida', 'die', '-n', 'n'],
  ['die Miete', 'el alquiler', 'die', '-n', 'n'],
  ['die Mitteilung', 'la comunicación', 'die', '-en', 'n'],
  ['die Motivation', 'la motivación', 'die', '-en', 'n'],
  ['die Natur', 'la naturaleza', 'die', '-', 'n'],
  ['die Notwendigkeit', 'la necesidad', 'die', '-en', 'n'],
  ['die Organisation', 'la organización', 'die', '-en', 'n'],
  ['die Orientierung', 'la orientación', 'die', '-en', 'n'],
  ['die Perspektive', 'la perspectiva', 'die', '-n', 'n'],
  ['die Pflege', 'el cuidado', 'die', '-', 'n'],
  ['die Politik', 'la política', 'die', '-', 'n'],
  ['die Position', 'la posición', 'die', '-en', 'n'],
  ['die Produktion', 'la producción', 'die', '-en', 'n'],
  ['die Prüfung', 'el examen', 'die', '-en', 'n'],
  ['die Qualität', 'la calidad', 'die', '-en', 'n'],
  ['die Reaktion', 'la reacción', 'die', '-en', 'n'],
  ['die Realität', 'la realidad', 'die', '-en', 'n'],
  ['die Regelung', 'la regulación', 'die', '-en', 'n'],
  ['die Reklamation', 'la reclamación', 'die', '-en', 'n'],
  ['die Rücksicht', 'la consideración', 'die', '-', 'n'],
  ['die Sammlung', 'la colección', 'die', '-en', 'n'],
  ['die Schuld', 'la culpa', 'die', '-en', 'n'],
  ['die Sicherheit', 'la seguridad', 'die', '-en', 'n'],
  ['die Sitzung', 'la sesión', 'die', '-en', 'n'],
  ['die Sorge', 'la preocupación', 'die', '-n', 'n'],
  ['die Spannung', 'la tensión', 'die', '-en', 'n'],
  ['die Sprache', 'la lengua', 'die', '-n', 'n'],
  ['die Stelle', 'el lugar/puesto', 'die', '-n', 'n'],
  ['die Steuer', 'el impuesto', 'die', '-n', 'n'],
  ['die Stimmung', 'el ambiente', 'die', '-en', 'n'],
  ['die Störung', 'la molestia', 'die', '-en', 'n'],
  ['die Straße', 'la calle', 'die', '-n', 'n'],
  ['die Stunde', 'la hora', 'die', '-n', 'n'],
  ['die Summe', 'la suma', 'die', '-n', 'n'],
  ['die Sache', 'la cosa', 'die', '-n', 'n'],
  ['die Tätigkeit', 'la actividad', 'die', '-en', 'n'],
  ['die Tatsache', 'el hecho', 'die', '-n', 'n'],
  ['die Teilnahme', 'la participación', 'die', '-n', 'n'],
  ['die Tendenz', 'la tendencia', 'die', '-en', 'n'],
  ['die Theorie', 'la teoría', 'die', '-n', 'n'],
  ['die Tradition', 'la tradición', 'die', '-en', 'n'],
  ['die Trennung', 'la separación', 'die', '-en', 'n'],
  ['die Überlegung', 'la reflexión', 'die', '-en', 'n'],
  ['die Übersetzung', 'la traducción', 'die', '-en', 'n'],
  ['die Umgebung', 'el entorno', 'die', '-en', 'n'],
  ['die Unterstützung', 'el apoyo', 'die', '-en', 'n'],
  ['die Verantwortung', 'la responsabilidad', 'die', '-en', 'n'],
  ['die Veränderung', 'el cambio', 'die', '-en', 'n'],
  ['die Verbesserung', 'la mejora', 'die', '-en', 'n'],
  ['die Verdienste', 'los méritos', 'die', '-', 'n'],
  ['die Vereinbarung', 'el acuerdo', 'die', '-en', 'n'],
  ['die Verfassung', 'la constitución', 'die', '-en', 'n'],
  ['die Vergangenheit', 'el pasado', 'die', '-', 'n'],
  ['die Verhandlung', 'la negociación', 'die', '-en', 'n'],
  ['die Versicherung', 'el seguro', 'die', '-en', 'n'],
  ['die Versorgung', 'el suministro', 'die', '-en', 'n'],
  ['die Voraussetzung', 'el requisito', 'die', '-en', 'n'],
  ['die Vorschrift', 'la norma', 'die', '-en', 'n'],
  ['die Vorsicht', 'la precaución', 'die', '-', 'n'],
  ['die Wahl', 'la elección', 'die', '-en', 'n'],
  ['die Wahrheit', 'la verdad', 'die', '-en', 'n'],
  ['die Wirtschaft', 'la economía', 'die', '-en', 'n'],
  ['die Wissenschaft', 'la ciencia', 'die', '-en', 'n'],
  ['die Wohnung', 'el piso', 'die', '-en', 'n'],
  ['die Zahl', 'el número', 'die', '-en', 'n'],
  ['die Zeitung', 'el periódico', 'die', '-en', 'n'],
  ['die Zukunft', 'el futuro', 'die', '-', 'n'],
  // Verbos separables B1
  ['anfangen', 'empezar', '', '', 'v'],
  ['aufhören', 'parar', '', '', 'v'],
  ['mitkommen', 'acompañar', '', '', 'v'],
  ['vorbereiten', 'preparar', '', '', 'v'],
  ['zurückkommen', 'volver', '', '', 'v'],
  ['ausgehen', 'salir', '', '', 'v'],
  ['einkaufen', 'comprar', '', '', 'v'],
  ['aufstehen', 'levantarse', '', '', 'v'],
  ['einladen', 'invitar', '', '', 'v'],
  ['aussehen', 'parecer', '', '', 'v'],
  ['mitmachen', 'participar', '', '', 'v'],
  ['nachdenken', 'reflexionar', '', '', 'v'],
  ['teilnehmen', 'participar', '', '', 'v'],
  ['stattfinden', 'tener lugar', '', '', 'v'],
  ['vorhaben', 'planear', '', '', 'v'],
  ['mitbringen', 'traer consigo', '', '', 'v'],
  ['abholen', 'recoger', '', '', 'v'],
  ['anziehen', 'vestir', '', '', 'v'],
  ['ausziehen', 'desvestir', '', '', 'v'],
  ['aufräumen', 'ordenar', '', '', 'v'],
  ['zumachen', 'cerrar', '', '', 'v'],
  ['aufmachen', 'abrir', '', '', 'v'],
  ['anmachen', 'encender', '', '', 'v'],
  ['ausmachen', 'apagar', '', '', 'v'],
  ['einschalten', 'encender', '', '', 'v'],
  ['ausschalten', 'apagar', '', '', 'v'],
  ['einpacken', 'empacar', '', '', 'v'],
  ['auspacken', 'desempacar', '', '', 'v'],
  ['einsteigen', 'subir', '', '', 'v'],
  ['aussteigen', 'bajar', '', '', 'v'],
  ['umsteigen', 'transbordar', '', '', 'v'],
  ['abfahren', 'partir', '', '', 'v'],
  ['ankommen', 'llegar', '', '', 'v'],
  ['weggehen', 'irse', '', '', 'v'],
  ['zurückgehen', 'volver', '', '', 'v'],
  ['weitergehen', 'seguir', '', '', 'v'],
  ['vorbeigehen', 'pasar por', '', '', 'v'],
  ['hinkommen', 'llegar a', '', '', 'v'],
  ['herkommen', 'venir de', '', '', 'v'],
  ['mitfahren', 'viajar con', '', '', 'v'],
  ['vorbeikommen', 'pasar/visitar', '', '', 'v'],
  ['kennenlernen', 'conocer', '', '', 'v'],
  ['zuhören', 'escuchar', '', '', 'v'],
  ['zuschauen', 'mirar', '', '', 'v'],
  ['ausprobieren', 'probar', '', '', 'v'],
  ['aufpassen', 'prestar atención', '', '', 'v'],
  ['zusammenfassen', 'resumir', '', '', 'v'],
  ['vorschlagen', 'proponer', '', '', 'v'],
  ['nachschlagen', 'consultar', '', '', 'v'],
  ['einsetzen', 'utilizar', '', '', 'v'],
  // Verbos reflexivos B1
  ['sich erinnern', 'recordar', '', '', 'v'],
  ['sich freuen', 'alegrarse', '', '', 'v'],
  ['sich ärgern', 'enfadarse', '', '', 'v'],
  ['sich beeilen', 'darse prisa', '', '', 'v'],
  ['sich ausruhen', 'descansar', '', '', 'v'],
  ['sich entschuldigen', 'disculparse', '', '', 'v'],
  ['sich bedanken', 'agradecer', '', '', 'v'],
  ['sich bewerben', 'solicitar', '', '', 'v'],
  ['sich entscheiden', 'decidirse', '', '', 'v'],
  ['sich entwickeln', 'desarrollarse', '', '', 'v'],
  ['sich treffen', 'encontrarse', '', '', 'v'],
  ['sich kümmern', 'ocuparse', '', '', 'v'],
  ['sich interessieren', 'interesarse', '', '', 'v'],
  ['sich bemühen', 'esforzarse', '', '', 'v'],
  ['sich lohnen', 'valer la pena', '', '', 'v'],
  ['sich gewöhnen', 'acostumbrarse', '', '', 'v'],
  ['sich verabschieden', 'despedirse', '', '', 'v'],
  ['sich vorstellen', 'presentarse', '', '', 'v'],
  ['sich wundern', 'sorprenderse', '', '', 'v'],
  ['sich beschweren', 'quejarse', '', '', 'v'],
  // Conectores B1
  ['trotzdem', 'sin embargo', '', '', 'adv'],
  ['außerdem', 'además', '', '', 'adv'],
  ['allerdings', 'sin embargo', '', '', 'adv'],
  ['hingegen', 'en cambio', '', '', 'adv'],
  ['dennoch', 'no obstante', '', '', 'adv'],
  ['deshalb', 'por eso', '', '', 'adv'],
  ['deswegen', 'por ello', '', '', 'adv'],
  ['trotz', 'a pesar de', '', '', 'prep'],
  ['während', 'durante/mientras', '', '', 'prep'],
  ['obwohl', 'aunque', '', '', 'conj'],
  ['weil', 'porque', '', '', 'conj'],
  ['dass', 'que', '', '', 'conj'],
  ['damit', 'para que', '', '', 'conj'],
  ['sodass', 'de modo que', '', '', 'conj'],
  ['wenn', 'si/cuando', '', '', 'conj'],
  ['als', 'cuando', '', '', 'conj'],
  ['bevor', 'antes de que', '', '', 'conj'],
  ['nachdem', 'después de que', '', '', 'conj'],
  ['seitdem', 'desde que', '', '', 'conj'],
  ['bis', 'hasta', '', '', 'conj'],
  ['ob', 'si (interrogativa)', '', '', 'conj'],
  ['indem', 'mediante', '', '', 'conj'],
  ['ohne dass', 'sin que', '', '', 'conj'],
  ['anstatt', 'en lugar de', '', '', 'prep'],
  ['innerhalb', 'dentro de', '', '', 'prep'],
  ['außerhalb', 'fuera de', '', '', 'prep'],
  ['entlang', 'a lo largo de', '', '', 'prep'],
  ['gegenüber', 'frente a', '', '', 'prep'],
  ['zufolge', 'según', '', '', 'prep'],
  ['mithilfe', 'con ayuda de', '', '', 'prep'],
];

// ─── VOCABULARIO C1 ─────────────────────────────────────────────────────────
const c1Vocab = [
  // Vocabulario académico
  ['die Analyse', 'el análisis', 'die', '-n', 'n'],
  ['die Hypothese', 'la hipótesis', 'die', '-n', 'n'],
  ['die Konsequenz', 'la consecuencia', 'die', '-en', 'n'],
  ['die Perspektive', 'la perspectiva', 'die', '-n', 'n'],
  ['die Kategorie', 'la categoría', 'die', '-n', 'n'],
  ['die Strategie', 'la estrategia', 'die', '-n', 'n'],
  ['die Methodik', 'la metodología', 'die', '-en', 'n'],
  ['die Systematik', 'la sistemática', 'die', '-en', 'n'],
  ['die Diagnose', 'el diagnóstico', 'die', '-n', 'n'],
  ['die Prognose', 'el pronóstico', 'die', '-n', 'n'],
  ['die Synthese', 'la síntesis', 'die', '-n', 'n'],
  ['die These', 'la tesis', 'die', '-n', 'n'],
  ['die Antithese', 'la antítesis', 'die', '-n', 'n'],
  ['das Argument', 'el argumento', 'das', '-e', 'n'],
  ['der Beweis', 'la prueba', 'der', '-e', 'n'],
  ['der Beleg', 'la evidencia', 'der', '-e', 'n'],
  ['der Nachweis', 'la demostración', 'der', '-e', 'n'],
  ['der Standpunkt', 'el punto de vista', 'der', '-e', 'n'],
  ['der Gesichtspunkt', 'el punto de vista', 'der', '-e', 'n'],
  ['der Aspekt', 'el aspecto', 'der', '-e', 'n'],
  ['der Faktor', 'el factor', 'der', '-en', 'n'],
  ['die Variable', 'la variable', 'die', '-n', 'n'],
  ['die Konstante', 'la constante', 'die', '-n', 'n'],
  ['das Phänomen', 'el fenómeno', 'das', '-e', 'n'],
  ['die Erscheinung', 'la apariencia', 'die', '-en', 'n'],
  ['die Eigenschaft', 'la propiedad', 'die', '-en', 'n'],
  ['die Merkmal', 'la característica', 'das', '-e', 'n'],
  ['das Prinzip', 'el principio', 'das', '-ien', 'n'],
  ['die Maxime', 'la máxima', 'die', '-n', 'n'],
  ['die Norm', 'la norma', 'die', '-en', 'n'],
  ['der Wert', 'el valor', 'der', '-e', 'n'],
  ['die Moral', 'la moral', 'die', '-', 'n'],
  ['die Ethik', 'la ética', 'die', '-en', 'n'],
  ['die Ästhetik', 'la estética', 'die', '-', 'n'],
  ['die Logik', 'la lógica', 'die', '-', 'n'],
  ['die Vernunft', 'la razón', 'die', '-', 'n'],
  ['der Verstand', 'el entendimiento', 'der', '-e', 'n'],
  ['die Intelligenz', 'la inteligencia', 'die', '-en', 'n'],
  ['das Bewusstsein', 'la conciencia', 'das', '-', 'n'],
  ['das Unterbewusstsein', 'el subconsciente', 'das', '-', 'n'],
  ['die Wahrnehmung', 'la percepción', 'die', '-en', 'n'],
  ['die Auffassung', 'la concepción', 'die', '-en', 'n'],
  ['die Ansicht', 'la opinión', 'die', '-en', 'n'],
  ['die Überzeugung', 'la convicción', 'die', '-en', 'n'],
  ['die Einstellung', 'la actitud', 'die', '-en', 'n'],
  ['die Haltung', 'la postura', 'die', '-en', 'n'],
  // Verbos formales C1
  ['erläutern', 'explicar/detallar', '', '', 'v'],
  ['erörtern', 'discutir/debatir', '', '', 'v'],
  ['voraussetzen', 'presuponer', '', '', 'v'],
  ['gegenüberstellen', 'comparar', '', '', 'v'],
  ['einschätzen', 'evaluar', '', '', 'v'],
  ['beurteilen', 'juzgar', '', '', 'v'],
  ['bewerten', 'valorar', '', '', 'v'],
  ['analysieren', 'analizar', '', '', 'v'],
  ['untersuchen', 'investigar', '', '', 'v'],
  ['überprüfen', 'verificar', '', '', 'v'],
  ['nachweisen', 'demostrar', '', '', 'v'],
  ['begründen', 'justificar', '', '', 'v'],
  ['rechtfertigen', 'justificar', '', '', 'v'],
  ['widerlegen', 'refutar', '', '', 'v'],
  ['bestätigen', 'confirmar', '', '', 'v'],
  ['widersprechen', 'contradecir', '', '', 'v'],
  ['zustimmen', 'estar de acuerdo', '', '', 'v'],
  ['ablehnen', 'rechazar', '', '', 'v'],
  ['befürworten', 'apoyar', '', '', 'v'],
  ['kritisieren', 'criticar', '', '', 'v'],
  ['beanstanden', 'objetar', '', '', 'v'],
  ['beanstanden', 'reclamar', '', '', 'v'],
  ['forderen', 'exigir', '', '', 'v'],
  ['verlangen', 'exigir', '', '', 'v'],
  ['beantragen', 'solicitar', '', '', 'v'],
  ['genehmigen', 'aprobar', '', '', 'v'],
  ['verweigern', 'negarse', '', '', 'v'],
  ['verzichten', 'renunciar', '', '', 'v'],
  ['bestehen auf', 'insistir en', '', '', 'v'],
  ['beitragen zu', 'contribuir a', '', '', 'v'],
  ['verfügen über', 'disponer de', '', '', 'v'],
  ['verfügen', 'disponer', '', '', 'v'],
  ['handeln von', 'tratar sobre', '', '', 'v'],
  ['beruhen auf', 'basarse en', '', '', 'v'],
  ['hinweisen auf', 'señalar', '', '', 'v'],
  ['eingehen auf', 'abordar', '', '', 'v'],
  ['zurückgreifen auf', 'recurrir a', '', '', 'v'],
  ['ausgehen von', 'partir de', '', '', 'v'],
  ['hervorgehen aus', 'deducirse de', '', '', 'v'],
  ['zusammenführen', 'fusionar', '', '', 'v'],
  ['gegenüberstellen', 'contraponer', '', '', 'v'],
  ['abwägen', 'ponderar', '', '', 'v'],
  ['vergleichen', 'comparar', '', '', 'v'],
  ['unterscheiden', 'distinguir', '', '', 'v'],
  ['charakterisieren', 'caracterizar', '', '', 'v'],
  ['definieren', 'definir', '', '', 'v'],
  ['klassifizieren', 'clasificar', '', '', 'v'],
  ['strukturieren', 'estructurar', '', '', 'v'],
  ['systematisieren', 'sistematizar', '', '', 'v'],
  ['differenzieren', 'diferenciar', '', '', 'v'],
  ['integrieren', 'integrar', '', '', 'v'],
  ['koordinieren', 'coordinar', '', '', 'v'],
  ['organisieren', 'organizar', '', '', 'v'],
  ['implementieren', 'implementar', '', '', 'v'],
  ['realisieren', 'realizar', '', '', 'v'],
  ['konkretisieren', 'concretar', '', '', 'v'],
  ['spezifizieren', 'especificar', '', '', 'v'],
  ['präzisieren', 'precisar', '', '', 'v'],
  ['quantifizieren', 'cuantificar', '', '', 'v'],
  ['qualifizieren', 'calificar', '', '', 'v'],
  // Sustantivos abstractos C1
  ['die Abhängigkeit', 'la dependencia', 'die', '-en', 'n'],
  ['die Wechselwirkung', 'la interacción', 'die', '-en', 'n'],
  ['die Gegenseitigkeit', 'la reciprocidad', 'die', '-', 'n'],
  ['die Gleichberechtigung', 'la igualdad de derechos', 'die', '-en', 'n'],
  ['die Chancengleichheit', 'la igualdad de oportunidades', 'die', '-', 'n'],
  ['die Diskriminierung', 'la discriminación', 'die', '-en', 'n'],
  ['die Integration', 'la integración', 'die', '-en', 'n'],
  ['die Globalisierung', 'la globalización', 'die', '-', 'n'],
  ['die Migration', 'la migración', 'die', '-en', 'n'],
  ['die Identität', 'la identidad', 'die', '-en', 'n'],
  ['die Individualität', 'la individualidad', 'die', '-en', 'n'],
  ['die Persönlichkeit', 'la personalidad', 'die', '-en', 'n'],
  ['die Mentalität', 'la mentalidad', 'die', '-en', 'n'],
  ['die Sensibilität', 'la sensibilidad', 'die', '-en', 'n'],
  ['die Verwundbarkeit', 'la vulnerabilidad', 'die', '-', 'n'],
  ['die Widerstandsfähigkeit', 'la resiliencia', 'die', '-en', 'n'],
  ['die Nachhaltigkeit', 'la sostenibilidad', 'die', '-', 'n'],
  ['die Umweltverträglichkeit', 'la compatibilidad ambiental', 'die', '-', 'n'],
  ['die Ressourcenschonung', 'la conservación de recursos', 'die', '-', 'n'],
  ['die Effizienz', 'la eficiencia', 'die', '-en', 'n'],
  ['die Effektivität', 'la efectividad', 'die', '-', 'n'],
  ['die Produktivität', 'la productividad', 'die', '-', 'n'],
  ['die Rentabilität', 'la rentabilidad', 'die', '-', 'n'],
  ['die Wirtschaftlichkeit', 'la viabilidad económica', 'die', '-', 'n'],
  ['die Konkurrenzfähigkeit', 'la competitividad', 'die', '-en', 'n'],
  ['die Innovationskraft', 'la capacidad innovadora', 'die', '-e', 'n'],
  ['die Wettbewerbsfähigkeit', 'la competividad', 'die', '-', 'n'],
  ['die Arbeitslosigkeit', 'el desempleo', 'die', '-', 'n'],
  ['die Inflation', 'la inflación', 'die', '-en', 'n'],
  ['die Rezession', 'la recesión', 'die', '-en', 'n'],
  ['die Stagnation', 'el estancamiento', 'die', '-en', 'n'],
  ['der Wohlstand', 'el bienestar', 'der', '-e', 'n'],
  ['der Lebensstandard', 'el nivel de vida', 'der', '-s', 'n'],
  ['die Lebensqualität', 'la calidad de vida', 'die', '-en', 'n'],
  ['das Bruttoinlandsprodukt', 'el PIB', 'das', '-e', 'n'],
  ['die Staatsverschuldung', 'la deuda pública', 'die', '-en', 'n'],
  ['der Haushalt', 'el presupuesto', 'der', '-e', 'n'],
  ['die Investition', 'la inversión', 'die', '-en', 'n'],
  ['die Subvention', 'la subvención', 'die', '-en', 'n'],
  ['die Steuer', 'el impuesto', 'die', '-n', 'n'],
  ['die Abgabe', 'la tasa', 'die', '-n', 'n'],
  ['der Zinssatz', 'el tipo de interés', 'der', 'ä-e', 'n'],
  ['die Aktie', 'la acción', 'die', '-n', 'n'],
  ['der Fonds', 'el fondo', 'der', '-', 'n'],
  ['die Börse', 'la bolsa', 'die', '-n', 'n'],
  ['der Gewinn', 'el beneficio', 'der', '-e', 'n'],
  ['der Verlust', 'la pérdida', 'der', '-e', 'n'],
  ['der Umsatz', 'la facturación', 'der', 'ä-e', 'n'],
  ['die Bilanz', 'el balance', 'die', '-en', 'n'],
  ['die Buchhaltung', 'la contabilidad', 'die', '-en', 'n'],
  ['der Vertrag', 'el contrato', 'der', 'ä-e', 'n'],
  ['die Vereinbarung', 'el acuerdo', 'die', '-en', 'n'],
  ['die Klausel', 'la cláusula', 'die', '-n', 'n'],
  ['die Bedingung', 'la condición', 'die', '-en', 'n'],
  ['die Auflage', 'la condición/requisito', 'die', '-n', 'n'],
  ['die Frist', 'el plazo', 'die', '-en', 'n'],
  ['der Termin', 'el plazo/fecha', 'der', '-e', 'n'],
  ['die Fälligkeit', 'el vencimiento', 'die', '-en', 'n'],
  ['die Kündigung', 'la cancelación', 'die', '-en', 'n'],
  ['der Rechtsstreit', 'el litigio', 'der', '-e', 'n'],
  ['das Urteil', 'la sentencia', 'das', '-e', 'n'],
  ['die Klage', 'la demanda', 'die', '-n', 'n'],
  ['der Anspruch', 'el derecho/reclamo', 'der', 'ü-e', 'n'],
  ['der Einspruch', 'la objeción', 'der', 'ü-e', 'n'],
  ['die Berufung', 'la apelación', 'die', '-en', 'n'],
  ['die Instanz', 'la instancia', 'die', '-en', 'n'],
  ['das Verfahren', 'el procedimiento', 'das', '-', 'n'],
  ['die Zuständigkeit', 'la competencia', 'die', '-en', 'n'],
  ['die Genehmigung', 'la autorización', 'die', '-en', 'n'],
  ['das Amt', 'el cargo/oficina', 'das', 'ä-er', 'n'],
  ['die Behörde', 'la autoridad', 'die', '-n', 'n'],
  ['das Ministerium', 'el ministerio', 'das', '-ien', 'n'],
  ['die Verordnung', 'la ordenanza', 'die', '-en', 'n'],
  ['die Richtlinie', 'la directiva', 'die', '-n', 'n'],
  ['der Beschluss', 'la resolución', 'der', 'ü-e', 'n'],
  ['der Entwurf', 'el proyecto/borrador', 'der', 'ü-e', 'n'],
  ['die Novelle', 'la reforma legislativa', 'die', '-n', 'n'],
  ['die Reform', 'la reforma', 'die', '-en', 'n'],
  ['der Wandel', 'el cambio', 'der', '-', 'n'],
  ['die Entwicklung', 'el desarrollo', 'die', '-en', 'n'],
  ['der Fortschritt', 'el progreso', 'der', '-e', 'n'],
  ['der Rückschritt', 'el retroceso', 'der', '-e', 'n'],
  ['die Verbesserung', 'la mejora', 'die', '-en', 'n'],
  ['die Verschlechterung', 'el empeoramiento', 'die', '-en', 'n'],
  ['die Steigerung', 'el aumento', 'die', '-en', 'n'],
  ['die Senkung', 'la reducción', 'die', '-en', 'n'],
  ['die Erhöhung', 'el aumento', 'die', '-en', 'n'],
  ['die Minderung', 'la disminución', 'die', '-en', 'n'],
  ['die Verringerung', 'la reducción', 'die', '-en', 'n'],
  ['die Ausweitung', 'la expansión', 'die', '-en', 'n'],
  ['die Begrenzung', 'la limitación', 'die', '-en', 'n'],
  ['die Einschränkung', 'la restricción', 'die', '-en', 'n'],
  ['die Aufhebung', 'la anulación', 'die', '-en', 'n'],
  ['die Abschaffung', 'la abolición', 'die', '-en', 'n'],
  ['die Einführung', 'la introducción', 'die', '-en', 'n'],
  ['die Umsetzung', 'la implementación', 'die', '-en', 'n'],
  ['die Anwendung', 'la aplicación', 'die', '-en', 'n'],
  ['die Nutzung', 'el uso', 'die', '-en', 'n'],
  ['die Inanspruchnahme', 'la utilización', 'die', '-n', 'n'],
  ['die Ausnutzung', 'el aprovechamiento', 'die', '-en', 'n'],
  ['die Verwertung', 'la valorización', 'die', '-en', 'n'],
  ['die Verarbeitung', 'el procesamiento', 'die', '-en', 'n'],
  ['die Herstellung', 'la fabricación', 'die', '-en', 'n'],
  ['die Erzeugung', 'la producción', 'die', '-en', 'n'],
  ['die Gewinnung', 'la obtención', 'die', '-en', 'n'],
  ['die Entsorgung', 'la eliminación', 'die', '-en', 'n'],
  ['die Reinigung', 'la limpieza', 'die', '-en', 'n'],
  ['die Instandhaltung', 'el mantenimiento', 'die', '-en', 'n'],
  ['die Wartung', 'el mantenimiento', 'die', '-en', 'n'],
  ['die Reparatur', 'la reparación', 'die', '-en', 'n'],
  // Modismos C1
  ['ein Auge zudrücken', 'hacer la vista gorda', '', '', 'v'],
  ['den Nagel auf den Kopf treffen', 'dar en el clavo', '', '', 'v'],
  ['sich den Kopf zerbrechen', 'calentarse la cabeza', '', '', 'v'],
  ['jm die Daumen drücken', 'cruzar los dedos por alguien', '', '', 'v'],
  ['über den Tellerrand schauen', 'pensar más allá', '', '', 'v'],
  ['etwas in die Wege leiten', 'poner algo en marcha', '', '', 'v'],
  ['den Mund halten', 'callarse', '', '', 'v'],
  ['auf dem Laufenden bleiben', 'mantenerse al día', '', '', 'v'],
  ['etwas auf die lange Bank', 'dejar algo para más tarde', '', '', 'v'],
  ['ins Auge fassen', 'considerar una opción', '', '', 'v'],
  ['aufs Spiel setzen', 'arriesgar', '', '', 'v'],
  ['etwas unter die Lupe', 'examinar algo', '', '', 'v'],
  ['etwas aus dem Stegreif', 'improvisar', '', '', 'v'],
  ['jmdm den Rücken stärken', 'apoyar a alguien', '', '', 'v'],
  ['Kein Blatt vor den Mund', 'no tener pelos en la lengua', '', '', 'v'],
  ['Schwarz auf Weiß', 'por escrito', '', '', 'n'],
  ['Nägel mit Köpfen machen', 'hacer algo de verdad', '', '', 'v'],
  ['den Ball flach halten', 'no emocionarse', '', '', 'v'],
  ['sich ins Zeug legen', 'esforzarse', '', '', 'v'],
  ['etwas in Betracht ziehen', 'considerar algo', '', '', 'v'],
  ['etwas zur Sprache bringen', 'sacar un tema', '', '', 'v'],
  ['um den heißen Brei reden', 'andar con rodeos', '', '', 'v'],
  ['den Wald vor lauter Bäumen nicht sehen', 'no ver el bosque', '', '', 'v'],
  ['eine Schraube locker haben', 'faltarle un tornillo', '', '', 'v'],
  ['nicht alle Tassen im Schrank', 'faltarle un tornillo', '', '', 'v'],
  ['das Kind mit dem Bade ausschütten', 'tirarlo todo por la borda', '', '', 'v'],
  ['ein Haar in der Suppe finden', 'buscarle tres pies al gato', '', '', 'v'],
  ['die Kirche im Dorf lassen', 'no exagerar', '', '', 'v'],
  ['sich etwas hinter die Ohren schreiben', 'apuntarse algo', '', '', 'v'],
  ['aus einer Mücke einen Elefanten machen', 'hacer una montaña de un grano de arena', '', '', 'v'],
  ['etwas auf sich beruhen lassen', 'dejar algo estar', '', '', 'v'],
  ['jemandem einen Bären aufbinden', 'tomar el pelo a alguien', '', '', 'v'],
  ['die Flinte ins Korn werfen', 'tirar la toalla', '', '', 'v'],
  ['den Teufel an die Wand malen', 'ser pesimista', '', '', 'v'],
  ['alle Register ziehen', 'tocar todos los palos', '', '', 'v'],
];

// ─── FILTRAR DUPLICADOS ────────────────────────────────────────────────────
function filterUnique(words) {
  return words.filter(w => {
    const de = w[0].toLowerCase().trim();
    if (existingWords.has(de)) return false;
    existingWords.add(de);
    return true;
  });
}

const uniqueA2 = filterUnique(a2Vocab);
const uniqueB1 = filterUnique(b1Vocab);
const uniqueC1 = filterUnique(c1Vocab);

console.log(`\n📊 Vocabulario generado:`);
console.log(`   A2: ${a2Vocab.length} generados, ${uniqueA2.length} únicos`);
console.log(`   B1: ${b1Vocab.length} generados, ${uniqueB1.length} únicos`);
console.log(`   C1: ${c1Vocab.length} generados, ${uniqueC1.length} únicos`);

// ─── ASIGNAR A NIVELES ──────────────────────────────────────────────────────
// A2.3 need 123, A2.4 need 165 = 288 total
// B1.2 need 117, B1.3 need 263, B1.4 need 261 = 641 total
// C1.2 need 90

const halfA2 = Math.floor(uniqueA2.length / 2);
const a2_3 = uniqueA2.slice(0, halfA2);
const a2_4 = uniqueA2.slice(halfA2, Math.min(uniqueA2.length, halfA2 + 200));

// B1: split into 3 groups
const thirdB1 = Math.floor(uniqueB1.length / 3);
const b1_2 = uniqueB1.slice(0, thirdB1);
const b1_3 = uniqueB1.slice(thirdB1, 2 * thirdB1);
const b1_4 = uniqueB1.slice(2 * thirdB1);

const halfC1 = Math.floor(uniqueC1.length / 2);
const c1_2 = uniqueC1.slice(halfC1); // C1.2 only, rest go to C1.1 but it already has enough

const injections = {
  'A2.3': a2_3,
  'A2.4': a2_4,
  'B1.2': b1_2,
  'B1.3': b1_3,
  'B1.4': b1_4,
  'C1.2': c1_2,
};

console.log(`\n📋 Distribución por nivel:`);
for (const [lvl, words] of Object.entries(injections)) {
  console.log(`   ${lvl}: ${words.length} palabras`);
}

// ─── INYECTAR EN rutaHelpers.jsx ───────────────────────────────────────────
let newContent = rutaContent;
let totalInjected = 0;

for (const [lvl, words] of Object.entries(injections)) {
  if (words.length === 0) continue;
  
  // Buscar addLevel('LVL', [
  const searchStr = `addLevel('${lvl}', [`;
  const startIdx = newContent.indexOf(searchStr);
  
  if (startIdx === -1) {
    console.log(`❌ No se encontró addLevel('${lvl}')`);
    continue;
  }
  
  // Encontrar el cierre ]);
  let depth = 0;
  let endIdx = -1;
  for (let i = startIdx; i < newContent.length; i++) {
    if (newContent[i] === '[') depth++;
    else if (newContent[i] === ']') {
      depth--;
      if (depth === 0 && newContent[i+1] === ')' && newContent[i+2] === ';') {
        endIdx = i + 3;
        break;
      }
    }
  }
  
  if (endIdx === -1) {
    console.log(`❌ No se pudo encontrar cierre para addLevel('${lvl}')`);
    continue;
  }
  
  // Generar el bloque de nuevas palabras
  const newWordsBlock = words.map(w => {
    const de = w[0].replace(/'/g, "\\'");
    const es = w[1].replace(/'/g, "\\'");
    const art = w[2] || '';
    const plural = w[3] || '';
    const tipo = w[4] || 'n';
    return `  ['${de}','${es}','${art}','${plural}','${tipo}'],`;
  }).join('\n');
  
  // Insertar antes del ]);
  const insertPoint = endIdx - 3;
  newContent = newContent.substring(0, insertPoint) + '\n' + newWordsBlock + '\n' + newContent.substring(insertPoint);
  totalInjected += words.length;
  
  console.log(`✅ ${lvl}: +${words.length} inyectadas`);
}

console.log(`\n📊 TOTAL INYECTADO: ${totalInjected} palabras`);

// ─── GUARDAR ────────────────────────────────────────────────────────────────
fs.writeFileSync(rutaPath, newContent, 'utf8');
console.log(`✅ rutaHelpers.jsx actualizado (${newContent.length} bytes)`);

// ─── CONTEO FINAL ──────────────────────────────────────────────────────────
console.log('\n📊 CONTEO FINAL:');
require('./contar_vocab_final.js');