// VOCABULARIO EXPANDIDO MEGA (+ todas las fuentes)
// Generado el 2026-05-07T22:44:26.553Z

// ── A1.1 (+42) ──
addLevel('A1.1',[
['string','[string]','','','n'],
['Nueva','[Nueva]','','','n'],
['Aprendiendo','[Aprendiendo]','','','n'],
['Familiar','[Familiar]','','','n'],
['Dominada','[Dominada]','','','n'],
['Experto','[Experto]','','','n'],
['verb','[verb]','','','n'],
['prep','[prep]','','','n'],
['failed','[failed]','','','n'],
['difficult','[difficult]','','','n'],
['weak','[weak]','','','n'],
['learning','[learning]','','','n'],
['die Schultasche','la mochila escolar','die','Schultaschen','n'],
['der Radiergummi','la goma de borrar','der','Radiergummis','n'],
['der Spitzer','el sacapuntas','der','Spitzer','n'],
['das Lineal','la regla','das','Lineale','n'],
['der Klebstoff','el pegamento','der','Klebstoffe','n'],
['die Schere','las tijeras','die','Scheren','n'],
['der Rucksack','la mochila','der','Rucksäcke','n'],
['die Federtasche','el estuche','die','Federtaschen','n'],
['das Heft','el cuaderno','das','Hefte','n'],
['der Taschenrechner','la calculadora','der','Taschenrechner','n'],
['die Turnschuhe','las zapatillas','die','Turnschuhen','n'],
['der Buntstift','el lápiz de color','der','Buntstifte','n'],
['das Frühstück','el desayuno','das','Frühstücke','n'],
['das Mittagessen','el almuerzo','das','Mittagessen','n'],
['das Abendessen','la cena','das','Abendessen','n'],
['die Zahnbürste','el cepillo de dientes','die','Zahnbürsten','n'],
['das Handtuch','la toalla','das','Handtücher','n'],
['die Seife','el jabón','die','Seifen','n'],
['der Kamm','el peine','der','Kämme','n'],
['der Wecker','el despertador','der','Wecker','n'],
['putzen','limpiar','','','v'],
['aufräumen','ordenar','','','v'],
['abwaschen','fregar','','','v'],
['geschlossen','cerrado','','','adj'],
['geöffnet','abierto','','','adj'],
['gemütlich','acogedor','','','adj'],
['bequem','cómodo','','','adj'],
['fleißig','trabajador','','','adj'],
['faul','perezoso','','','adj'],
['freundlich','amigable','','','adj'],
]);

// ── A1.2 (+41) ──
addLevel('A1.2',[
['recordings','[recordings]','','','n'],
['mastered','[mastered]','','','n'],
['smart','[smart]','','','n'],
['articulos','[articulos]','','','n'],
['articles','[articles]','','','n'],
['verbos','[verbos]','','','n'],
['preposiciones','[preposiciones]','','','n'],
['guion','[guion]','','','n'],
['Akkusativ','[Akkusativ]','','','n'],
['über','[über]','','','n'],
['nach','[nach]','','','n'],
['durch','[durch]','','','n'],
['die Eisenbahn','el ferrocarril','die','Eisenbahnen','n'],
['der Flughafen','el aeropuerto','der','Flughäfen','n'],
['der Bahnsteig','el andén','der','Bahnsteige','n'],
['das Gleis','la vía','das','Gleise','n'],
['die Abfahrt','la salida','die','Abfahrten','n'],
['die Ankunft','la llegada','die','Ankünfte','n'],
['das Abteil','el compartimento','das','Abteile','n'],
['die Fahrkarte','el billete','die','Fahrkarten','n'],
['der Schaffner','el revisor','der','Schaffner','n'],
['der Ausflug','la excursión','der','Ausflüge','n'],
['die Wanderung','la caminata','die','Wanderungen','n'],
['das Picknick','el picnic','das','Picknicks','n'],
['das Ferienhaus','la casa de vacaciones','das','Ferienhäuser','n'],
['der Campingplatz','el camping','der','Campingplätze','n'],
['das Schwimmbad','la piscina','das','Schwimmbäder','n'],
['die Sporthalle','el polideportivo','die','Sporthallen','n'],
['das Stadion','el estadio','das','Stadien','n'],
['die Turnhalle','el gimnasio','die','Turnhallen','n'],
['die Sauna','la sauna','die','Saunen','n'],
['die Terrasse','la terraza','die','Terrassen','n'],
['der Balkon','el balcón','der','Balkone','n'],
['der Keller','el sótano','der','Keller','n'],
['der Dachboden','el ático','der','Dachböden','n'],
['die Garage','el garaje','die','Garagen','n'],
['der Garten','el jardín','der','Gärten','n'],
['einpacken','empaquetar','','','v'],
['auspacken','desempaquetar','','','v'],
['einkaufen','comprar','','','v'],
['verkaufen','vender','','','v'],
]);

// ── A1.3 (+32) ──
addLevel('A1.3',[
['readwrite','[readwrite]','','','n'],
['gegen','[gegen]','','','n'],
['ohne','[ohne]','','','n'],
['seit','[seit]','','','n'],
['trotz','[trotz]','','','n'],
['während','[während]','','','n'],
['wegen','[wegen]','','','n'],
['statt','[statt]','','','n'],
['dank','[dank]','','','n'],
['laut','[laut]','','','n'],
['unter','[unter]','','','n'],
['neben','[neben]','','','n'],
['zeigen','mostrar','','','v'],
['fragen','preguntar','','','v'],
['antworten','responder','','','v'],
['öffnen','abrir','','','v'],
['schließen','cerrar','','','v'],
['holen','traer','','','v'],
['bringen','traer','','','v'],
['bezahlen','pagar','','','v'],
['suchen','buscar','','','v'],
['finden','encontrar','','','v'],
['brauchen','necesitar','','','v'],
['wünschen','desear','','','v'],
['feiern','celebrar','','','v'],
['reisen','viajar','','','v'],
['wandern','senderismo','','','v'],
['klettern','trepar','','','v'],
['schwimmen','nadar','','','v'],
['tanzen','bailar','','','v'],
['malen','pintar','','','v'],
['basteln','manualidades','','','v'],
]);

// ── A1.4 (+28) ──
addLevel('A1.4',[
['readonly','[readonly]','','','n'],
['zwischen','[zwischen]','','','n'],
['hinter','[hinter]','','','n'],
['Dativ','[Dativ]','','','n'],
['Genitiv','[Genitiv]','','','n'],
['el hombre','[el hombre]','','','n'],
['la mujer','[la mujer]','','','n'],
['la mesa','[la mesa]','','','n'],
['el libro','[el libro]','','','n'],
['la silla','[la silla]','','','n'],
['la pizarra','[la pizarra]','','','n'],
['la ventana','[la ventana]','','','n'],
['telefonieren','telefonear','','','v'],
['parken','aparcar','','','v'],
['abholen','recoger','','','v'],
['einladen','invitar','','','v'],
['aussteigen','bajarse','','','v'],
['einsteigen','subirse','','','v'],
['abfahren','salir','','','v'],
['ankommen','llegar','','','v'],
['mitbringen','traer consigo','','','v'],
['vorbereiten','preparar','','','v'],
['einladen','invitar','','','v'],
['ausgeben','gastar','','','v'],
['einteilen','dividir','','','v'],
['einschlafen','dormirse','','','v'],
['aufwachen','despertarse','','','v'],
['aufstehen','levantarse','','','v'],
]);

// ── A2.1 (+12) ──
addLevel('A2.1',[
['default','[default]','','','n'],
['el profesor','[el profesor]','','','n'],
['la alumna','[la alumna]','','','n'],
['el cuaderno','[el cuaderno]','','','n'],
['el perro','[el perro]','','','n'],
['la gata','[la gata]','','','n'],
['la casa','[la casa]','','','n'],
['la manzana','[la manzana]','','','n'],
['la leche','[la leche]','','','n'],
['el agua','[el agua]','','','n'],
['el tren','[el tren]','','','n'],
['el coche','[el coche]','','','n'],
]);

// ── A2.2 (+12) ──
addLevel('A2.2',[
['Rotkäppchen','[Rotkäppchen]','','','n'],
['el ordenador','[el ordenador]','','','n'],
['la libertad','[la libertad]','','','n'],
['la confianza','[la confianza]','','','n'],
['la historia','[la historia]','','','n'],
['el momento','[el momento]','','','n'],
['el resultado','[el resultado]','','','n'],
['el desarrollo','[el desarrollo]','','','n'],
['el requisito','[el requisito]','','','n'],
['la empresa','[la empresa]','','','n'],
['el progreso','[el progreso]','','','n'],
['la responsabilidad','[la responsabilidad]','','','n'],
]);

// ── A2.3 (+30) ──
addLevel('A2.3',[
['Umweltschutz','[Umweltschutz]','','','n'],
['la memoria','[la memoria]','','','n'],
['la sociedad','[la sociedad]','','','n'],
['la posibilidad','[la posibilidad]','','','n'],
['la oferta','[la oferta]','','','n'],
['warten auf','[warten auf]','','','n'],
['esperar','[esperar]','','','n'],
['sich freuen auf','[sich freuen auf]','','','n'],
['sich freuen über','[sich freuen über]','','','n'],
['denken an','[denken an]','','','n'],
['pensar en','[pensar en]','','','n'],
['sich erinnern an','[sich erinnern an]','','','n'],
['erzählen','contar','','','v'],
['erklären','explicar','','','v'],
['beschreiben','describir','','','v'],
['vergessen','olvidar','','','v'],
['erinnern','recordar','','','v'],
['glauben','creer','','','v'],
['meinen','opinar','','','v'],
['denken','pensar','','','v'],
['gefallen','gustar','','','v'],
['schmecken','saber a','','','v'],
['fühlen','sentir','','','v'],
['berühren','tocar','','','v'],
['tragen','llevar','','','v'],
['anziehen','vestirse','','','v'],
['waschen','lavar','','','v'],
['backen','hornear','','','v'],
['braten','freír','','','v'],
['schneiden','cortar','','','v'],
]);

// ── A2.4 (+23) ──
addLevel('A2.4',[
['recordar','[recordar]','','','n'],
['sich kümmern um','[sich kümmern um]','','','n'],
['ocuparse de','[ocuparse de]','','','n'],
['bitten um','[bitten um]','','','n'],
['pedir','[pedir]','','','n'],
['sich interessieren für','[sich interessieren für]','','','n'],
['interesarse por','[interesarse por]','','','n'],
['danken für','[danken für]','','','n'],
['agradecer por','[agradecer por]','','','n'],
['sich vorbereiten auf','[sich vorbereiten auf]','','','n'],
['prepararse para','[prepararse para]','','','n'],
['vermieten','alquilar','','','v'],
['umziehen','mudarse','','','v'],
['gründen','fundar','','','v'],
['verwalten','administrar','','','v'],
['pflegen','cuidar','','','v'],
['reparieren','reparar','','','v'],
['einrichten','amueblar','','','v'],
['renovieren','renovar','','','v'],
['versichern','asegurar','','','v'],
['einziehen','mudarse','','','v'],
['auswandern','emigrar','','','v'],
['einwandern','inmigrar','','','v'],
]);

// ── B1.1 (+45) ──
addLevel('B1.1',[
['Lukas','[Lukas]','','','n'],
['ausstellen','[ausstellen]','','','n'],
['exponer','[exponer]','','','n'],
['Elena','[Elena]','','','n'],
['sprechen über','[sprechen über]','','','n'],
['hablar sobre','[hablar sobre]','','','n'],
['sich beschweren über','[sich beschweren über]','','','n'],
['quejarse de','[quejarse de]','','','n'],
['teilnehmen an','[teilnehmen an]','','','n'],
['participar en','[participar en]','','','n'],
['sich treffen mit','[sich treffen mit]','','','n'],
['encontrarse con','[encontrarse con]','','','n'],
['helfen bei','[helfen bei]','','','n'],
['träumen von','[träumen von]','','','n'],
['abhängen von','[abhängen von]','','','n'],
['die Selbstständigkeit','el autoempleo','die','Selbstständigkeiten','n'],
['die Arbeitslosigkeit','el desempleo','die','Arbeitslosigkeiten','n'],
['die Bewerbung','la solicitud','die','Bewerbungen','n'],
['das Vorstellungsgespräch','la entrevista','das','Vorstellungsgespräche','n'],
['der Arbeitgeber','el empleador','der','Arbeitgeber','n'],
['der Arbeitnehmer','el empleado','der','Arbeitnehmer','n'],
['das Gehalt','el salario','das','Gehälter','n'],
['die Steuer','el impuesto','die','Steuern','n'],
['die Versicherung','el seguro','die','Versicherungen','n'],
['die Rente','la pensión','die','Renten','n'],
['der Kredit','el crédito','der','Kredite','n'],
['die Hypothek','la hipoteca','die','Hypotheken','n'],
['die Miete','el alquiler','die','Mieten','n'],
['die Nebenkosten','los gastos adicionales','die','Nebenkosten','n'],
['die Kaution','la fianza','die','Kautionen','n'],
['der Vertrag','el contrato','der','Verträge','n'],
['die Kündigung','la cancelación','die','Kündigungen','n'],
['die Frist','el plazo','die','Fristen','n'],
['die Genehmigung','el permiso','die','Genehmigungen','n'],
['die Anmeldung','el registro','die','Anmeldungen','n'],
['die Abmeldung','la baja','die','Abmeldungen','n'],
['der Nachweis','el comprobante','der','Nachweise','n'],
['die Bescheinigung','el certificado','die','Bescheinigungen','n'],
['der Ausweis','el documento','der','Ausweise','n'],
['der Pass','el pasaporte','der','Pässe','n'],
['der Führerschein','el carnet de conducir','der','Führerscheine','n'],
['der Personalausweis','el DNI','der','Personalausweise','n'],
['voraussetzen','presuponer','','','v'],
['gewährleisten','garantizar','','','v'],
['beanspruchen','reclamar','','','v'],
]);

// ── B1.2 (+15) ──
addLevel('B1.2',[
['el artista','[el artista]','','','n'],
['el reconocimiento','[el reconocimiento]','','','n'],
['bekommen','[bekommen]','','','n'],
['recibir','[recibir]','','','n'],
['depender de','[depender de]','','','n'],
['sich gewöhnen an','[sich gewöhnen an]','','','n'],
['acostumbrarse a','[acostumbrarse a]','','','n'],
['verzichten auf','[verzichten auf]','','','n'],
['renunciar a','[renunciar a]','','','n'],
['passen zu','[passen zu]','','','n'],
['sich entscheiden für','[sich entscheiden für]','','','n'],
['decidirse por','[decidirse por]','','','n'],
['sich konzentrieren auf','[sich konzentrieren auf]','','','n'],
['concentrarse en','[concentrarse en]','','','n'],
['bestehen aus','[bestehen aus]','','','n'],
]);

// ── B1.3 (+19) ──
addLevel('B1.3',[
['el cuadro','[el cuadro]','','','n'],
['entstehen','[entstehen]','','','n'],
['super','[super]','','','n'],
['genial','[genial]','','','n'],
['consistir en','[consistir en]','','','n'],
['leiden unter','[leiden unter]','','','n'],
['sich unterscheiden von','[sich unterscheiden von]','','','n'],
['diferenciarse de','[diferenciarse de]','','','n'],
['glauben an','[glauben an]','','','n'],
['creer en','[creer en]','','','n'],
['sich fürchten vor','[sich fürchten vor]','','','n'],
['temer a','[temer a]','','','n'],
['schützen vor','[schützen vor]','','','n'],
['proteger de','[proteger de]','','','n'],
['einladen zu','[einladen zu]','','','n'],
['abstrakt','[abstrakt]','','','adj'],
['harmonisch','[harmonisch]','','','adj'],
['unabhängig','[unabhängig]','','','adj'],
['verantwortlich','[verantwortlich]','','','adj'],
]);

// ── B1.4 (+19) ──
addLevel('B1.4',[
['la influencia','[la influencia]','','','n'],
['el pintor','[el pintor]','','','n'],
['la escultura','[la escultura]','','','n'],
['la historia de vida','[la historia de vida]','','','n'],
['invitar a','[invitar a]','','','n'],
['gehören zu','[gehören zu]','','','n'],
['pertenecer a','[pertenecer a]','','','n'],
['para','[para]','','','n'],
['contra','[contra]','','','n'],
['alrededor de','[alrededor de]','','','n'],
['außer','[außer]','','','n'],
['excepto','[excepto]','','','n'],
['a pesar de','[a pesar de]','','','n'],
['durante','[durante]','','','n'],
['debido a','[debido a]','','','n'],
['zuverlässig','[zuverlässig]','','','adj'],
['nachhaltig','[nachhaltig]','','','adj'],
['umfassend','[umfassend]','','','adj'],
['anspruchsvoll','[anspruchsvoll]','','','adj'],
]);

// ── B2.1 (+19) ──
addLevel('B2.1',[
['geboren werden','[geboren werden]','','','n'],
['nacer','[nacer]','','','n'],
['fliehen','[fliehen]','','','n'],
['huir','[huir]','','','n'],
['en lugar de','[en lugar de]','','','n'],
['gracias a','[gracias a]','','','n'],
['entlang','[entlang]','','','n'],
['a lo largo de','[a lo largo de]','','','n'],
['hasta','[hasta]','','','n'],
['heit','[heit]','','','n'],
['keit','[keit]','','','n'],
['schaft','[schaft]','','','n'],
['ling','[ling]','','','n'],
['ismus','[ismus]','','','n'],
['ment','[ment]','','','n'],
['beeindruckend','[beeindruckend]','','','adj'],
['durchschnittlich','[durchschnittlich]','','','adj'],
['entscheidend','[entscheidend]','','','adj'],
['fortschrittlich','[fortschrittlich]','','','adj'],
]);

// ── B2.2 (+19) ──
addLevel('B2.2',[
['kämpfen gegen','[kämpfen gegen]','','','n'],
['luchar contra','[luchar contra]','','','n'],
['sich einsetzen für','[sich einsetzen für]','','','n'],
['interceder por','[interceder por]','','','n'],
['loge','[loge]','','','n'],
['chen','[chen]','','','n'],
['lein','[lein]','','','n'],
['Nach','[Nach]','','','n'],
['Über','[Über]','','','n'],
['Durch','[Durch]','','','n'],
['Gegen','[Gegen]','','','n'],
['Ohne','[Ohne]','','','n'],
['Seit','[Seit]','','','n'],
['Trotz','[Trotz]','','','n'],
['Während','[Während]','','','n'],
['gegensätzlich','[gegensätzlich]','','','adj'],
['hervorragend','[hervorragend]','','','adj'],
['konkret','[konkret]','','','adj'],
['konsequent','[konsequent]','','','adj'],
]);

// ── B2.3 (+19) ──
addLevel('B2.3',[
['el derecho humano','[el derecho humano]','','','n'],
['el prejuicio','[el prejuicio]','','','n'],
['recht haben','[recht haben]','','','n'],
['el rayo','[el rayo]','','','n'],
['Wegen','[Wegen]','','','n'],
['Dank','[Dank]','','','n'],
['Laut','[Laut]','','','n'],
['Statt','[Statt]','','','n'],
['Familie','[Familie]','','','n'],
['Beruf','[Beruf]','','','n'],
['Wohnen','[Wohnen]','','','n'],
['Reisen','[Reisen]','','','n'],
['Essen','[Essen]','','','n'],
['Hobbys','[Hobbys]','','','n'],
['Deutsch lernen','[Deutsch lernen]','','','n'],
['mangelhaft','[mangelhaft]','','','adj'],
['oberflächlich','[oberflächlich]','','','adj'],
['professionell','[professionell]','','','adj'],
['realistisch','[realistisch]','','','adj'],
]);

// ── B2.4 (+18) ──
addLevel('B2.4',[
['el robo','[el robo]','','','n'],
['verhaften','[verhaften]','','','n'],
['detener','[detener]','','','n'],
['Zukunft','[Zukunft]','','','n'],
['Gesundheit','[Gesundheit]','','','n'],
['Medien','[Medien]','','','n'],
['Umwelt','[Umwelt]','','','n'],
['Technologie','[Technologie]','','','n'],
['Sprachen','[Sprachen]','','','n'],
['Einkaufen','[Einkaufen]','','','n'],
['Feiertage','[Feiertage]','','','n'],
['numeric','[numeric]','','','n'],
['short','[short]','','','n'],
['Preposiciones','[Preposiciones]','','','n'],
['umstritten','[umstritten]','','','adj'],
['unzureichend','[unzureichend]','','','adj'],
['vergleichbar','[vergleichbar]','','','adj'],
['wahrscheinlich','[wahrscheinlich]','','','adj'],
]);

// ── C1.1 (+13) ──
addLevel('C1.1',[
['mixed','[mixed]','','','n'],
['speed','[speed]','','','n'],
['perfect','[perfect]','','','n'],
['volume','[volume]','','','n'],
['verbs','[verbs]','','','n'],
['comeback','[comeback]','','','n'],
['Alta','[Alta]','','','n'],
['Media','[Media]','','','n'],
['Baja','[Baja]','','','n'],
['wesentlich','[wesentlich]','','','adj'],
['wissenschaftlich','[wissenschaftlich]','','','adj'],
['zweckmäßig','[zweckmäßig]','','','adj'],
['ausreichend','[ausreichend]','','','adj'],
]);

// ── C1.2 (+2) ──
addLevel('C1.2',[
['bedeutend','[bedeutend]','','','adj'],
['charakteristisch','[charakteristisch]','','','adj'],
]);

