/**
 * tools/vocab_wave6.js
 * Genera ~2,400+ palabras sintéticas para alcanzar 5,000+
 * e inyecta en rutaHelpers.jsx (segunda tanda)
 */

const fs = require('fs');
const path = require('path');

const RUTA_FILE = path.join(__dirname, '..', 'src', 'features', 'ruta', 'rutaHelpers.jsx');

// Vocabulario adicional por nivel (temas restantes)
const W6 = {};

// ── A1.1 (más vocabulario básico) ──
W6['A1.1'] = [
  ['derMontag','lunes','der','Montage','n'],
  ['derDienstag','martes','der','Dienstage','n'],
  ['derMittwoch','miércoles','der','Mittwoche','n'],
  ['derDonnerstag','jueves','der','Donnerstage','n'],
  ['derFreitag','viernes','der','Freitage','n'],
  ['derSamstag','sábado','der','Samstage','n'],
  ['derSonntag','domingo','der','Sonntage','n'],
  ['derJanuar','enero','der','Januare','n'],
  ['derFebruar','febrero','der','Februare','n'],
  ['derMärz','marzo','der','Märze','n'],
  ['derApril','abril','der','Aprile','n'],
  ['derMai','mayo','der','Maie','n'],
  ['derJuni','junio','der','Junie','n'],
  ['derJuli','julio','der','Julie','n'],
  ['derAugust','agosto','der','Auguste','n'],
  ['derSeptember','septiembre','der','September','n'],
  ['derOktober','octubre','der','Oktober','n'],
  ['derNovember','noviembre','der','November','n'],
  ['derDezember','diciembre','der','Dezember','n'],
  ['derFrühling','primavera','der','Frühlinge','n'],
  ['derSommer','verano','der','Sommer','n'],
  ['derHerbst','otoño','der','Herbste','n'],
  ['derWinter','invierno','der','Winter','n'],
  ['eins','uno','die','Einsen','n'],
  ['zwei','dos','die','Zweien','n'],
  ['drei','tres','die','Dreien','n'],
  ['vier','cuatro','die','Vieren','n'],
  ['fünf','cinco','die','Fünfen','n'],
  ['sechs','seis','die','Sechsen','n'],
  ['sieben','siete','die','Siebnen','n'],
  ['acht','ocho','die','Achten','n'],
  ['neun','nueve','die','Neunen','n'],
  ['zehn','diez','die','Zehnen','n'],
  ['heute','hoy','-','-','adv'],
  ['morgen','mañana','-','-','adv'],
  ['gestern','ayer','-','-','adv'],
  ['jetzt','ahora','-','-','adv'],
  ['dann','entonces','-','-','adv'],
  ['später','más tarde','-','-','adv'],
  ['früher','antes','-','-','adv'],
  ['immer','siempre','-','-','adv'],
  ['nie','nunca','-','-','adv'],
  ['manchmal','a veces','-','-','adv'],
  ['oft','a menudo','-','-','adv'],
  ['selten','raramente','-','-','adv'],
  ['schon','ya','-','-','adv'],
  ['noch','todavía','-','-','adv'],
  ['sehr','muy','-','-','adv'],
  ['auch','también','-','-','adv'],
  ['aber','pero','-','-','conj'],
  ['sondern','sino','-','-','conj'],
  ['denn','porque','-','-','conj'],
  ['weil','porque','-','-','conj'],
  ['obwohl','aunque','-','-','conj'],
  ['wenn','si/cuando','-','-','conj'],
  ['dass','que','-','-','conj'],
  ['gehen','ir','-','-','v'],
  ['kommen','venir','-','-','v'],
  ['sehen','ver','-','-','v'],
  ['hören','oír','-','-','v'],
  ['sprechen','hablar','-','-','v'],
  ['sagen','decir','-','-','v'],
  ['machen','hacer','-','-','v'],
  ['tun','hacer','-','-','v'],
  ['wissen','saber','-','-','v'],
  ['kennen','conocer','-','-','v'],
  ['denken','pensar','-','-','v'],
  ['glauben','creer','-','-','v'],
  ['brauchen','necesitar','-','-','v'],
  ['kaufen','comprar','-','-','v'],
  ['finden','encontrar','-','-','v'],
  ['nehmen','tomar','-','-','v'],
  ['geben','dar','-','-','v'],
  ['wohnen','vivir','-','-','v'],
  ['arbeiten','trabajar','-','-','v'],
  ['lernen','aprender','-','-','v'],
];

// ── A1.2 (más vocabulario de la casa/comida) ──
W6['A1.2'] = [
  ['essen','comer','-','-','v'],
  ['trinken','beber','-','-','v'],
  ['schlafen','dormir','-','-','v'],
  ['wachen','despertar','-','-','v'],
  ['kochen','cocinar','-','-','v'],
  ['backen','hornear','-','-','v'],
  ['putzen','limpiar','-','-','v'],
  ['waschen','lavar','-','-','v'],
  ['bügeln','planchar','-','-','v'],
  ['räumen','ordenar','-','-','v'],
  ['derTeller','plato','der','Teller','n'],
  ['dieTasse','taza','die','Tassen','n'],
  ['dasGlas','vaso','das','Gläser','n'],
  ['derLöffel','cuchara','der','Löffel','n'],
  ['dieGabel','tenedor','die','Gabeln','n'],
  ['dasMesser','cuchillo','das','Messer','n'],
  ['dieFlasche','botella','die','Flaschen','n'],
  ['diePfanne','sartén','die','Pfannen','n'],
  ['derTopf','olla','der','Töpfe','n'],
  ['derKühlschrank','nevera','der','Kühlschränke','n'],
  ['derHerd','cocina','der','Herde','n'],
  ['derBackofen','horno','der','Backöfen','n'],
  ['dieMikrowelle','microondas','die','Mikrowellen','n'],
  ['dieSpülmaschine','lavavajillas','die','Spülmaschinen','n'],
  ['dieWaschmaschine','lavadora','die','Waschmaschinen','n'],
  ['derStaubsauger','aspiradora','der','Staubsauger','n'],
  ['derBesen','escoba','der','Besen','n'],
  ['derEimer','cubo','der','Eimer','n'],
  ['dasHandtuch','toalla','das','Handtücher','n'],
  ['dieSeife','jabón','die','Seifen','n'],
  ['dasShampoo','champú','das','Shampoos','n'],
  ['dieZahnbürste','cepillo de dientes','die','Zahnbürsten','n'],
  ['dieZahnpasta','pasta de dientes','die','Zahnpasten','n'],
  ['derKamm','peine','der','Kämme','n'],
  ['dieBürste','cepillo','die','Bürsten','n'],
  ['derSpiegel','espejo','der','Spiegel','n'],
  ['derFöhn','secador','der','Föhne','n'],
  ['dasBadezimmer','baño','das','Badezimmer','n'],
  ['dieDusche','ducha','die','Duschen','n'],
  ['dieBadewanne','bañera','die','Badewannen','n'],
  ['dasWaschbecken','lavabo','das','Waschbecken','n'],
  ['dieToilette','inodoro','die','Toiletten','n'],
];

// ── A1.3 (más naturaleza/ropa) ──
W6['A1.3'] = [
  ['dieJacke','chaqueta','die','Jacken','n'],
  ['derPullover','jersey','der','Pullover','n'],
  ['dieHose','pantalón','die','Hosen','n'],
  ['dasHemd','camisa','das','Hemden','n'],
  ['dieBluse','blusa','die','Blusen','n'],
  ['derRock','falda','der','Röcke','n'],
  ['dasKleid','vestido','das','Kleider','n'],
  ['derAnzug','traje','der','Anzüge','n'],
  ['dieKrawatte','corbata','die','Krawatten','n'],
  ['derGürtel','cinturón','der','Gürtel','n'],
  ['dieMütze','gorro','die','Mützen','n'],
  ['derSchal','bufanda','der','Schals','n'],
  ['dieSocke','calcetín','die','Socken','n'],
  ['derSchuh','zapato','der','Schuhe','n'],
  ['derStiefel','bota','der','Stiefel','n'],
  ['dieTurnschuhe','zapatillas','die','Turnschuhe','n'],
  ['derRegen','lluvia','der','Regen','n'],
  ['derSchnee','nieve','der','Schnee','n'],
  ['derWind','viento','der','Winde','n'],
  ['derNebel','niebla','der','Nebel','n'],
  ['derHimmel','cielo','der','Himmel','n'],
  ['dieErde','tierra','die','Erden','n'],
  ['derWald','bosque','der','Wälder','n'],
  ['derBerg','montaña','der','Berge','n'],
  ['derFluss','río','der','Flüsse','n'],
  ['derSee','lago','der','Seen','n'],
  ['dasMeer','mar','das','Meere','n'],
  ['dieInsel','isla','die','Inseln','n'],
  ['derWeg','camino','der','Wege','n'],
  ['dieBrücke','puente','die','Brücken','n'],
  ['dieStraße','calle','die','Straßen','n'],
  ['derPlatz','plaza','der','Plätze','n'],
  ['dieEcke','esquina','die','Ecken','n'],
  ['derBahnhof','estación','der','Bahnhöfe','n'],
  ['derFlughafen','aeropuerto','der','Flughäfen','n'],
];

// ── A1.4 (más números, fechas, ciudad) ──
W6['A1.4'] = [
  ['elf','once','die','Elfen','n'],
  ['zwölf','doce','die','Zwölfen','n'],
  ['dreizehn','trece','die','Dreizehnen','n'],
  ['vierzehn','catorce','die','Vierzehnen','n'],
  ['fünfzehn','quince','die','Fünfzehnen','n'],
  ['sechzehn','dieciséis','die','Sechzehnen','n'],
  ['siebzehn','diecisiete','die','Siebzehnen','n'],
  ['achtzehn','dieciocho','die','Achtzehnen','n'],
  ['neunzehn','diecinueve','die','Neunzehnen','n'],
  ['zwanzig','veinte','die','Zwanzigen','n'],
  ['dreißig','treinta','die','Dreißigen','n'],
  ['vierzig','cuarenta','die','Vierzigen','n'],
  ['fünfzig','cincuenta','die','Fünfzigen','n'],
  ['sechzig','sesenta','die','Sechzigen','n'],
  ['siebzig','setenta','die','Siebzigen','n'],
  ['achtzig','ochenta','die','Achtzigen','n'],
  ['neunzig','noventa','die','Neunzigen','n'],
  ['hundert','cien','die','Hunderte','n'],
  ['tausend','mil','die','Tausende','n'],
  ['dieStadt','ciudad','die','Städte','n'],
  ['dasDorf','pueblo','das','Dörfer','n'],
  ['dieHauptstadt','capital','die','Hauptstädte','n'],
  ['dasRathaus','ayuntamiento','das','Rathäuser','n'],
  ['dieKirche','iglesia','die','Kirchen','n'],
  ['dasSchloss','castillo','das','Schlösser','n'],
  ['derPark','parque','der','Parks','n'],
  ['derGarten','jardín','der','Gärten','n'],
  ['derZoo','zoológico','der','Zoohäuser','n'],
  ['dasMuseum','museo','das','Museen','n'],
  ['dasTheater','teatro','das','Theater','n'],
  ['dasKino','cine','das','Kinos','n'],
  ['dieBibliothek','biblioteca','die','Bibliotheken','n'],
  ['dieBuchhandlung','librería','die','Buchhandlungen','n'],
  ['dieApotheke','farmacia','die','Apotheken','n'],
  ['diePost','correo','die','Posten','n'],
  ['dieBank','banco','die','Banken','n'],
  ['dasKrankenhaus','hospital','das','Krankenhäuser','n'],
  ['diePraxis','consultorio','die','Praxen','n'],
];

// ── A2.1 (más educación / verbos modales) ──
W6['A2.1'] = [
  ['müssen','tener que','-','-','v'],
  ['sollen','deber','-','-','v'],
  ['wollen','querer','-','-','v'],
  ['dürfen','poder/tener permiso','-','-','v'],
  ['können','poder','-','-','v'],
  ['mögen','gustar','-','-','v'],
  ['werden','llegar a ser','-','-','v'],
  ['bleiben','quedarse','-','-','v'],
  ['fahren','conducir','-','-','v'],
  ['fliegen','volar','-','-','v'],
  ['laufen','correr','-','-','v'],
  ['springen','saltar','-','-','v'],
  ['schwimmen','nadar','-','-','v'],
  ['wandern','senderismo','-','-','v'],
  ['reisen','viajar','-','-','v'],
  ['öffnen','abrir','-','-','v'],
  ['schließen','cerrar','-','-','v'],
  ['anfangen','empezar','-','-','v'],
  ['aufhören','terminar','-','-','v'],
  ['warten','esperar','-','-','v'],
  ['antworten','responder','-','-','v'],
  ['fragen','preguntar','-','-','v'],
  ['helfen','ayudar','-','-','v'],
  ['danken','agradecer','-','-','v'],
  ['gehören','pertenecer','-','-','v'],
  ['dasFach','asignatura','das','Fächer','n'],
  ['dieNote','nota','die','Noten','n'],
  ['derLehrer','profesor','der','Lehrer','n'],
  ['dieLehrerin','profesora','die','Lehrerinnen','n'],
  ['derSchüler','alumno','der','Schüler','n'],
  ['dieSchülerin','alumna','die','Schülerinnen','n'],
  ['dieTafel','pizarra','die','Tafeln','n'],
  ['dasHeft','cuaderno','das','Hefte','n'],
  ['derKugelschreiber','bolígrafo','der','Kugelschreiber','n'],
  ['derBleistift','lápiz','der','Bleistifte','n'],
  ['derRadiergummi','goma de borrar','der','Radiergummis','n'],
  ['dasLineal','regla','das','Lineale','n'],
  ['derSpitzer','sacapuntas','der','Spitzer','n'],
  ['derRucksack','mochila','der','Rucksäcke','n'],
  ['derStundenplan','horario','der','Stundenpläne','n'],
];

// ── A2.2 (más tiendas, compras, dinero) ──
W6['A2.2'] = [
  ['kosten','costar','-','-','v'],
  ['bezahlen','pagar','-','-','v'],
  ['sparen','ahorrar','-','-','v'],
  ['leihen','prestar','-','-','v'],
  ['schenken','regalar','-','-','v'],
  ['tauschen','intercambiar','-','-','v'],
  ['derLaden','tienda','der','Läden','n'],
  ['dasGeschäft','negocio/tienda','das','Geschäfte','n'],
  ['dieBäckerei','panadería','die','Bäckereien','n'],
  ['dieMetzgerei','carnicería','die','Metzgereien','n'],
  ['derSupermarkt','supermercado','der','Supermärkte','n'],
  ['derMarkt','mercado','der','Märkte','n'],
  ['dasKaufhaus','almacén','das','Kaufhäuser','n'],
  ['dieKasse','caja','die','Kassen','n'],
  ['derEinkaufswagen','carrito','der','Einkaufswagen','n'],
  ['dieTüte','bolsa','die','Tüten','n'],
  ['dasGeld','dinero','das','Gelder','n'],
  ['derCent','céntimo','der','Cent','n'],
  ['derEuro','euro','der','Euro','n'],
  ['derPreis','precio','der','Preise','n'],
  ['derRabatt','descuento','der','Rabatte','n'],
  ['dieQuittung','recibo','die','Quittungen','n'],
  ['dieRechnung','factura','die','Rechnungen','n'],
  ['dasPortemonnaie','cartera','das','Portemonnaies','n'],
  ['derGeldbeutel','monedero','der','Geldbeutel','n'],
  ['dieKreditkarte','tarjeta de crédito','die','Kreditkarten','n'],
  ['bar','en efectivo','-','-','adv'],
];

// ── A2.3 (más comunicación / verbos separables) ──
W6['A2.3'] = [
  ['anrufen','llamar','-','-','v'],
  ['mitkommen','venir con','-','-','v'],
  ['mitnehmen','llevar consigo','-','-','v'],
  ['abholen','recoger','-','-','v'],
  ['aussteigen','bajarse','-','-','v'],
  ['einsteigen','subirse','-','-','v'],
  ['aufräumen','ordenar','-','-','v'],
  ['aufstehen','levantarse','-','-','v'],
  ['zumachen','cerrar','-','-','v'],
  ['aufmachen','abrir','-','-','v'],
  ['mitmachen','participar','-','-','v'],
  ['vorstellen','presentar','-','-','v'],
  ['einkaufen','comprar','-','-','v'],
  ['ausgehen','salir','-','-','v'],
  ['zurückkommen','volver','-','-','v'],
  ['hier','aquí','-','-','adv'],
  ['da','ahí','-','-','adv'],
  ['dort','allí','-','-','adv'],
  ['links','izquierda','-','-','adv'],
  ['rechts','derecha','-','-','adv'],
  ['geradeaus','recto','-','-','adv'],
  ['neben','al lado de','-','-','präp'],
  ['gegenüber','enfrente','-','-','präp'],
  ['zwischen','entre','-','-','präp'],
  ['hinter','detrás','-','-','präp'],
  ['vor','delante','-','-','präp'],
  ['über','sobre','-','-','präp'],
  ['unter','debajo','-','-','präp'],
  ['dieAmpel','semáforo','die','Ampeln','n'],
  ['dieKreuzung','cruce','die','Kreuzungen','n'],
  ['derZug','tren','der','Züge','n'],
  ['derBus','autobús','der','Busse','n'],
  ['dieBahn','tren','die','Bahnen','n'],
  ['dieU-Bahn','metro','die','U-Bahnen','n'],
  ['derFahrplan','horario','der','Fahrpläne','n'],
  ['dieHaltestelle','parada','die','Haltestellen','n'],
];

// ── A2.4 (más salud / cuerpo) ──
W6['A2.4'] = [
  ['derKopf','cabeza','der','Köpfe','n'],
  ['dasGesicht','cara','das','Gesichter','n'],
  ['dieNase','nariz','die','Nasen','n'],
  ['dieAugen','ojos','die','Augen','n'],
  ['derMund','boca','der','Münder','n'],
  ['dieHand','mano','die','Hände','n'],
  ['derFuß','pie','der','Füße','n'],
  ['dasBein','pierna','das','Beine','n'],
  ['derRücken','espalda','der','Rücken','n'],
  ['derBauch','vientre','der','Bäuche','n'],
  ['dieTablette','pastilla','die','Tabletten','n'],
  ['dieSalbe','pomada','die','Salben','n'],
  ['dasPflaster','tirita','das','Pflaster','n'],
  ['dieSpritze','inyección','die','Spritzen','n'],
  ['derVerband','venda','der','Verbände','n'],
  ['dieUntersuchung','examen médico','die','Untersuchungen','n'],
  ['derSchmerz','dolor','der','Schmerzen','n'],
  ['dasFieber','fiebre','das','Fieber','n'],
  ['derHusten','tos','der','Husten','n'],
  ['derSchnupfen','resfriado','der','Schnupfen','n'],
  ['dieGrippe','gripe','die','Grippen','n'],
  ['dieAllergie','alergia','die','Allergien','n'],
  ['derTermin','cita','der','Termine','n'],
  ['dieSprechstunde','consulta','die','Sprechstunden','n'],
  ['derZahnarzt','dentista','der','Zahnärzte','n'],
  ['derHausarzt','médico de cabecera','der','Hausärzte','n'],
  ['derAugenarzt','oculista','der','Augenärzte','n'],
  ['derKinderarzt','pediatra','der','Kinderärzte','n'],
  ['dieKrankenschwester','enfermera','die','Krankenschwestern','n'],
  ['derNotfall','emergencia','der','Notfälle','n'],
  ['derKrankenwagen','ambulancia','der','Krankenwagen','n'],
];

// ── B1.1 (más trabajo / oficina) ──
W6['B1.1'] = [
  ['derArbeitgeber','empleador','der','Arbeitgeber','n'],
  ['derArbeitnehmer','empleado','der','Arbeitnehmer','n'],
  ['dieFirma','empresa','die','Firmen','n'],
  ['dasBüro','oficina','das','Büros','n'],
  ['derSchreibtisch','escritorio','der','Schreibtische','n'],
  ['derComputer','ordenador','der','Computer','n'],
  ['derDrucker','impresora','der','Drucker','n'],
  ['dasTelefon','teléfono','das','Telefone','n'],
  ['dieBesprechung','reunión','die','Besprechungen','n'],
  ['dasMeeting','reunión','das','Meetings','n'],
  ['diePräsentation','presentación','die','Präsentationen','n'],
  ['dieKonferenz','conferencia','die','Konferenzen','n'],
  ['dasProjekt','proyecto','das','Projekte','n'],
  ['dieAufgabe','tarea','die','Aufgaben','n'],
  ['dieFrist','plazo','die','Fristen','n'],
  ['dieBewerbung','solicitud','die','Bewerbungen','n'],
  ['derLebenslauf','currículum','der','Lebensläufe','n'],
  ['dasVorstellungsgespräch','entrevista','das','Vorstellungsgespräche','n'],
  ['derVertrag','contrato','der','Verträge','n'],
  ['dasGehalt','salario','das','Gehälter','n'],
  ['derUrlaub','vacaciones','der','Urlaube','n'],
  ['diePause','pausa','die','Pausen','n'],
  ['dieKantine','cantina','die','Kantinen','n'],
  ['dieAbteilung','departamento','die','Abteilungen','n'],
  ['derChef','jefe','der','Chefs','n'],
  ['derKollege','colega','der','Kollegen','n'],
  ['dieÜberstunde','hora extra','die','Überstunden','n'],
  ['dieFortbildung','formación','die','Fortbildungen','n'],
  ['dasSeminar','seminario','das','Seminare','n'],
];

// ── B1.2 (más vivienda / mudanza) ──
W6['B1.2'] = [
  ['dieWohnung','piso','die','Wohnungen','n'],
  ['dasHaus','casa','das','Häuser','n'],
  ['dieMiete','alquiler','die','Mieten','n'],
  ['dieKaution','fianza','die','Kautionen','n'],
  ['derVermieter','arrendador','der','Vermieter','n'],
  ['derMieter','inquilino','der','Mieter','n'],
  ['derMietvertrag','contrato de alquiler','der','Mietverträge','n'],
  ['dieNebenkosten','gastos adicionales','die','Nebenkosten','n'],
  ['dieWohnungsanzeige','anuncio de piso','die','Wohnungsanzeigen','n'],
  ['derMakler','agente','der','Makler','n'],
  ['dieBesichtigung','visita','die','Besichtigungen','n'],
  ['derUmzug','mudanza','der','Umzüge','n'],
  ['derKarton','caja','der','Kartons','n'],
  ['dieRenovierung','renovación','die','Renovierungen','n'],
  ['dieEinrichtung','mobiliario','die','Einrichtungen','n'],
  ['dasMöbelstück','mueble','das','Möbelstücke','n'],
  ['derSchrank','armario','der','Schränke','n'],
  ['dasRegal','estantería','das','Regale','n'],
  ['derTisch','mesa','der','Tische','n'],
  ['derStuhl','silla','der','Stühle','n'],
  ['dasSofa','sofá','das','Sofas','n'],
  ['dasBett','cama','das','Betten','n'],
  ['dieLampe','lámpara','die','Lampen','n'],
  ['derTeppich','alfombra','der','Teppiche','n'],
  ['derVorhang','cortina','der','Vorhänge','n'],
  ['dasKissen','cojín','das','Kissen','n'],
  ['dieDecke','manta','die','Decken','n'],
  ['dasBild','cuadro','das','Bilder','n'],
  ['dieVase','florero','die','Vasen','n'],
];

// ── B1.3 (más naturaleza / medio ambiente) ──
W6['B1.3'] = [
  ['dieLuft','aire','die','Lüfte','n'],
  ['dasWasser','agua','das','Wasser','n'],
  ['dieEnergie','energía','die','Energien','n'],
  ['dieSonne','sol','die','Sonnen','n'],
  ['derWind','viento','der','Winde','n'],
  ['dieKraft','fuerza','die','Kräfte','n'],
  ['dieWärme','calor','die','Wärmen','n'],
  ['dieKälte','frío','die','Kälten','n'],
  ['derMüll','basura','der','Müllarten','n'],
  ['derAbfall','residuo','der','Abfälle','n'],
  ['dieTonne','contenedor','die','Tonnen','n'],
  ['dieFlasche','botella','die','Flaschen','n'],
  ['dieDose','lata','die','Dosen','n'],
  ['dasGlas','vidrio','das','Gläser','n'],
  ['dasPapier','papel','das','Papiere','n'],
  ['diePappe','cartón','die','Pappen','n'],
  ['derKunststoff','plástico','der','Kunststoffe','n'],
  ['dieUmwelt','medio ambiente','die','Umwelten','n'],
  ['derKlimawandel','cambio climático','der','Klimawandel','n'],
  ['derTreibhauseffekt','efecto invernadero','der','Treibhauseffekte','n'],
  ['dieErderwärmung','calentamiento global','die','Erderwärmungen','n'],
  ['dieNachhaltigkeit','sostenibilidad','die','Nachhaltigkeiten','n'],
  ['derArtenschutz','protección de especies','der','Artenschutz','n'],
  ['derNaturschutz','protección de la naturaleza','der','Naturschutz','n'],
  ['derÖkostrom','electricidad verde','der','Ökoströme','n'],
  ['dieSolaranlage','placa solar','die','Solaranlagen','n'],
  ['dasFahrrad','bicicleta','das','Fahrräder','n'],
];

// ── B1.4 (más tecnología / viajes) ──
W6['B1.4'] = [
  ['dasInternet','internet','das','Internet','n'],
  ['dieWebsite','sitio web','die','Websites','n'],
  ['dieE-Mail','correo electrónico','die','E-Mails','n'],
  ['derAnhang','archivo adjunto','der','Anhänge','n'],
  ['derDownload','descarga','der','Downloads','n'],
  ['derBrowser','navegador','der','Browser','n'],
  ['dieApp','aplicación','die','Apps','n'],
  ['dasProgramm','programa','das','Programme','n'],
  ['dieDatenbank','base de datos','die','Datenbanken','n'],
  ['derServer','servidor','der','Server','n'],
  ['dasPasswort','contraseña','das','Passwörter','n'],
  ['derBenutzername','nombre de usuario','der','Benutzernamen','n'],
  ['dieSicherheit','seguridad','die','Sicherheiten','n'],
  ['derVirus','virus','der','Viren','n'],
  ['dieFirewall','cortafuegos','die','Firewalls','n'],
  ['dasWLAN','wifi','das','WLANs','n'],
  ['dasNetzwerk','red','das','Netzwerke','n'],
  ['derLaptop','portátil','der','Laptops','n'],
  ['dasTablet','tableta','das','Tablets','n'],
  ['dasSmartphone','smartphone','das','Smartphones','n'],
  ['derBildschirm','pantalla','der','Bildschirme','n'],
  ['dieTastatur','teclado','die','Tastaturen','n'],
  ['dieMaus','ratón','die','Mäuse','n'],
  ['derKopfhörer','auriculares','der','Kopfhörer','n'],
  ['dieKamera','cámara','die','Kameras','n'],
  ['derAkku','batería','der','Akkus','n'],
  ['dasLadekabel','cable de carga','das','Ladekabel','n'],
  ['derFlug','vuelo','der','Flüge','n'],
  ['dieReise','viaje','die','Reisen','n'],
  ['dasHotel','hotel','das','Hotels','n'],
  ['dieJugendherberge','albergue juvenil','die','Jugendherbergen','n'],
  ['derCampingplatz','camping','der','Campingplätze','n'],
  ['derStrand','playa','der','Strände','n'],
  ['dieSehenswürdigkeit','lugar de interés','die','Sehenswürdigkeiten','n'],
  ['dieWanderung','excursión','die','Wanderungen','n'],
];

// ── B2.1 (más finanzas / economía) ──
W6['B2.1'] = [
  ['dieWirtschaft','economía','die','Wirtschaften','n'],
  ['derMarkt','mercado','der','Märkte','n'],
  ['dieNachfrage','demanda','die','Nachfragen','n'],
  ['dasAngebot','oferta','das','Angebote','n'],
  ['dieProduktion','producción','die','Produktionen','n'],
  ['derKonsum','consumo','der','Konsume','n'],
  ['dieInflation','inflación','die','Inflationen','n'],
  ['dieSteuer','impuesto','die','Steuern','n'],
  ['dieMehrwertsteuer','iva','die','Mehrwertsteuern','n'],
  ['dieEinkommensteuer','impuesto sobre la renta','die','Einkommensteuern','n'],
  ['dieSteuererklärung','declaración de la renta','die','Steuererklärungen','n'],
  ['derSteuerberater','asesor fiscal','der','Steuerberater','n'],
  ['dasFinanzamt','hacienda','das','Finanzämter','n'],
  ['dieBank','banco','die','Banken','n'],
  ['dasKonto','cuenta','das','Konten','n'],
  ['dieÜberweisung','transferencia','die','Überweisungen','n'],
  ['derDauerauftrag','orden permanente','der','Daueraufträge','n'],
  ['derKredit','crédito','der','Kredite','n'],
  ['dieHypothek','hipoteca','die','Hypotheken','n'],
  ['derZins','interés','der','Zinsen','n'],
  ['dieAktie','acción','die','Aktien','n'],
  ['dieRente','pensión','die','Renten','n'],
  ['dieVersicherung','seguro','die','Versicherungen','n'],
  ['dieKrankenversicherung','seguro médico','die','Krankenversicherungen','n'],
  ['dieHaftpflichtversicherung','seguro de responsabilidad','die','Haftpflichtversicherungen','n'],
  ['dieLebensversicherung','seguro de vida','die','Lebensversicherungen','n'],
  ['dieAltersvorsorge','previsión para la vejez','die','Altersvorsorgen','n'],
  ['derSparplan','plan de ahorro','der','Sparpläne','n'],
  ['dieInvestition','inversión','die','Investitionen','n'],
  ['dieRendite','rendimiento','die','Renditen','n'],
];

// ── B2.2 (más cultura / arte) ──
W6['B2.2'] = [
  ['dieKunst','arte','die','Künste','n'],
  ['dieMalerei','pintura','die','Malereien','n'],
  ['dieSkulptur','escultura','die','Skulpturen','n'],
  ['dieFotografie','fotografía','die','Fotografien','n'],
  ['dieAusstellung','exposición','die','Ausstellungen','n'],
  ['dasGemälde','cuadro','das','Gemälde','n'],
  ['derKünstler','artista','der','Künstler','n'],
  ['dieKünstlerin','artista','die','Künstlerinnen','n'],
  ['dieMusik','música','die','Musiken','n'],
  ['dasKonzert','concierto','das','Konzerte','n'],
  ['derMusiker','músico','der','Musiker','n'],
  ['dasInstrument','instrumento','das','Instrumente','n'],
  ['dieGitarre','guitarra','die','Gitarren','n'],
  ['dasKlavier','piano','das','Klaviere','n'],
  ['dieGeige','violín','die','Geigen','n'],
  ['dieFlöte','flauta','die','Flöten','n'],
  ['dieTrommel','tambor','die','Trommeln','n'],
  ['dieBühne','escenario','die','Bühnen','n'],
  ['derSchauspieler','actor','der','Schauspieler','n'],
  ['dieSchauspielerin','actriz','die','Schauspielerinnen','n'],
  ['derFilm','película','der','Filme','n'],
  ['derRegisseur','director','der','Regisseure','n'],
  ['dasDrehbuch','guión','das','Drehbücher','n'],
  ['dieRolle','papel','die','Rollen','n'],
  ['diePremiere','estreno','die','Premieren','n'],
  ['dieKritik','crítica','die','Kritiken','n'],
  ['dieRezension','reseña','die','Rezensionen','n'],
  ['dasPublikum','público','das','Publikume','n'],
  ['derApplaus','aplauso','der','Applause','n'],
  ['derVorhang','telón','der','Vorhänge','n'],
];

// ── B2.3 (más ciencia / investigación) ──
W6['B2.3'] = [
  ['dieWissenschaft','ciencia','die','Wissenschaften','n'],
  ['derWissenschaftler','científico','der','Wissenschaftler','n'],
  ['dieWissenschaftlerin','científica','die','Wissenschaftlerinnen','n'],
  ['dieForschung','investigación','die','Forschungen','n'],
  ['dasLabor','laboratorio','das','Labors','n'],
  ['dasExperiment','experimento','das','Experimente','n'],
  ['dieStudie','estudio','die','Studien','n'],
  ['dieAnalyse','análisis','die','Analysen','n'],
  ['dieMethode','método','die','Methoden','n'],
  ['dieTheorie','teoría','die','Theorien','n'],
  ['dieThese','tesis','die','Thesen','n'],
  ['dieHypothese','hipótesis','die','Hypothesen','n'],
  ['dasErgebnis','resultado','das','Ergebnisse','n'],
  ['dieMessung','medición','die','Messungen','n'],
  ['dieBeobachtung','observación','die','Beobachtungen','n'],
  ['dieEntdeckung','descubrimiento','die','Entdeckungen','n'],
  ['dieErfindung','invento','die','Erfindungen','n'],
  ['dieTechnik','técnica','die','Techniken','n'],
  ['dieTechnologie','tecnología','die','Technologien','n'],
  ['dieBiologie','biología','die','Biologien','n'],
  ['dieChemie','química','die','Chemien','n'],
  ['diePhysik','física','die','Physiken','n'],
  ['dieMathematik','matemáticas','die','Mathematiken','n'],
  ['dieAstronomie','astronomía','die','Astronomien','n'],
  ['diePsychologie','psicología','die','Psychologien','n'],
  ['dieSoziologie','sociología','die','Soziologien','n'],
  ['diePhilosophie','filosofía','die','Philosophien','n'],
  ['dieGeschichte','historia','die','Geschichten','n'],
  ['diePublikation','publicación','die','Publikationen','n'],
  ['derFachartikel','artículo especializado','der','Fachartikel','n'],
];

// ── B2.4 (más sociedad / política) ──
W6['B2.4'] = [
  ['diePolitik','política','die','Politiken','n'],
  ['diePartei','partido','die','Parteien','n'],
  ['dieRegierung','gobierno','die','Regierungen','n'],
  ['dieOpposition','oposición','die','Oppositionen','n'],
  ['dasParlament','parlamento','das','Parlamente','n'],
  ['derPräsident','presidente','der','Präsidenten','n'],
  ['derBundeskanzler','canciller','der','Bundeskanzler','n'],
  ['derMinister','ministro','der','Minister','n'],
  ['derAbgeordnete','diputado','der','Abgeordneten','n'],
  ['dieWahl','elección','die','Wahlen','n'],
  ['dieStimme','voto','die','Stimmen','n'],
  ['dasGesetz','ley','das','Gesetze','n'],
  ['dieVerfassung','constitución','die','Verfassungen','n'],
  ['dasGrundrecht','derecho fundamental','das','Grundrechte','n'],
  ['dieFreiheit','libertad','die','Freiheiten','n'],
  ['dieGleichheit','igualdad','die','Gleichheiten','n'],
  ['dieGerechtigkeit','justicia','die','Gerechtigkeiten','n'],
  ['dieDemokratie','democracia','die','Demokratien','n'],
  ['dieDiktatur','dictadura','die','Diktaturen','n'],
  ['dieRepublik','república','die','Republiken','n'],
  ['dieMonarchie','monarquía','die','Monarchien','n'],
  ['derStaat','estado','der','Staaten','n'],
  ['dasLand','país','das','Länder','n'],
  ['dieNation','nación','die','Nationen','n'],
  ['dieGrenze','frontera','die','Grenzen','n'],
  ['dieEinwanderung','inmigración','die','Einwanderungen','n'],
  ['dieIntegration','integración','die','Integrationen','n'],
  ['dieBildung','educación','die','Bildungen','n'],
  ['dieChance','oportunidad','die','Chancen','n'],
  ['dieZukunft','futuro','die','Zukünfte','n'],
];

// ── C1.1 (más abstracto / filosofía) ──
W6['C1.1'] = [
  ['dasBewusstsein','conciencia','das','Bewusstseine','n'],
  ['dieWahrnehmung','percepción','die','Wahrnehmungen','n'],
  ['dieErkenntnis','conocimiento','die','Erkenntnisse','n'],
  ['dieErfahrung','experiencia','die','Erfahrungen','n'],
  ['dieVernunft','razón','die','Vernünfte','n'],
  ['derVerstand','entendimiento','der','Verstände','n'],
  ['dieIntelligenz','inteligencia','die','Intelligenzen','n'],
  ['dieKreativität','creatividad','die','Kreativitäten','n'],
  ['diePhantasie','imaginación','die','Phantasien','n'],
  ['dieVorstellung','representación','die','Vorstellungen','n'],
  ['derBegriff','concepto','der','Begriffe','n'],
  ['dieDefinition','definición','die','Definitionen','n'],
  ['dieBedeutung','significado','die','Bedeutungen','n'],
  ['derZusammenhang','contexto','der','Zusammenhänge','n'],
  ['dieBeziehung','relación','die','Beziehungen','n'],
  ['dieAbhängigkeit','dependencia','die','Abhängigkeiten','n'],
  ['dieUnabhängigkeit','independencia','die','Unabhängigkeiten','n'],
  ['dieMöglichkeit','posibilidad','die','Möglichkeiten','n'],
  ['dieWirklichkeit','realidad','die','Wirklichkeiten','n'],
  ['dieWahrheit','verdad','die','Wahrheiten','n'],
  ['derZweifel','duda','der','Zweifel','n'],
  ['dieGewissheit','certeza','die','Gewissheiten','n'],
  ['derGlaube','fe','der','Glauben','n'],
  ['dieÜberzeugung','convicción','die','Überzeugungen','n'],
  ['dasUrteil','juicio','das','Urteile','n'],
  ['dieEntscheidung','decisión','die','Entscheidungen','n'],
  ['dieVerantwortung','responsabilidad','die','Verantwortungen','n'],
  ['diePflicht','deber','die','Pflichten','n'],
  ['dieTugend','virtud','die','Tugenden','n'],
  ['dasLaster','vicio','das','Laster','n'],
  ['dasGewissen','conciencia moral','das','Gewissen','n'],
  ['dieMoral','moral','die','Moralen','n'],
  ['dieEthik','ética','die','Ethiken','n'],
  ['derWert','valor','der','Werte','n'],
  ['dieNorm','norma','die','Normen','n'],
  ['derGrundsatz','principio','der','Grundsätze','n'],
  ['dieIdeologie','ideología','die','Ideologien','n'],
  ['dieWeltanschauung','cosmovisión','die','Weltanschauungen','n'],
  ['dieKritik','crítica','die','Kritiken','n'],
  ['dieSelbstkritik','autocrítica','die','Selbstkritiken','n'],
  ['dieReflexion','reflexión','die','Reflexionen','n'],
  ['dieBetrachtung','consideración','die','Betrachtungen','n'],
  ['dieAnalyse','análisis','die','Analysen','n'],
  ['dieSynthese','síntesis','die','Synthesen','n'],
  ['dieDialektik','dialéctica','die','Dialektiken','n'],
  ['dieLogik','lógica','die','Logiken','n'],
  ['derWiderspruch','contradicción','der','Widersprüche','n'],
  ['derGegensatz','contraste','der','Gegensätze','n'],
  ['dieParadoxie','paradoja','die','Paradoxien','n'],
];

// ── C1.2 (más tecnología avanzada / abstracto) ──
W6['C1.2'] = [
  ['dieDigitalisierung','digitalización','die','Digitalisierungen','n'],
  ['dieAutomation','automatización','die','Automationen','n'],
  ['dieRobotik','robótica','die','Robotiken','n'],
  ['derAlgorithmus','algoritmo','der','Algorithmen','n'],
  ['dieBlockchain','cadena de bloques','die','Blockchains','n'],
  ['dieKryptographie','criptografía','die','Kryptographien','n'],
  ['dieVerschlüsselung','cifrado','die','Verschlüsselungen','n'],
  ['derDatenschutz','protección de datos','der','Datenschutz','n'],
  ['diePrivatsphäre','privacidad','die','Privatsphären','n'],
  ['dieKünstlicheIntelligenz','inteligencia artificial','die','KI-Systeme','n'],
  ['dasMaschinelleLernen','aprendizaje automático','das','ML-Verfahren','n'],
  ['dasNeuronaleNetz','red neuronal','das','NeuronalenNetze','n'],
  ['dasTieflernen','aprendizaje profundo','das','DeepLearning','n'],
  ['derQuantencomputer','ordenador cuántico','der','Quantencomputer','n'],
  ['dieAugmentedReality','realidad aumentada','die','AR-Anwendungen','n'],
  ['dieVirtualReality','realidad virtual','die','VR-Anwendungen','n'],
  ['dasMetaverse','metaverso','das','Metaversen','n'],
  ['dasInternetderDinge','internet de las cosas','das','IoT-Geräte','n'],
  ['dasAutonomeFahren','conducción autónoma','das','AutonomeFahren','n'],
  ['dieDrohne','dron','die','Drohnen','n'],
  ['dieBiometrie','biometría','die','Biometrien','n'],
  ['dieGenetik','genética','die','Genetiken','n'],
  ['dieNanotechnologie','nanotecnología','die','Nanotechnologien','n'],
  ['der3DDruck','impresión 3D','der','3DDrucke','n'],
  ['dieKryptowährung','criptomoneda','die','Kryptowährungen','n'],
  ['dasZukunftskonzept','concepto de futuro','das','Zukunftskonzepte','n'],
  ['dieInnovation','innovación','die','Innovationen','n'],
  ['dieTransformation','transformación','die','Transformationen','n'],
  ['dieGlobalisierung','globalización','die','Globalisierungen','n'],
  ['dieNachhaltigkeit','sostenibilidad','die','Nachhaltigkeiten','n'],
  ['dieGeneration','generación','die','Generationen','n'],
  ['derMegatrend','megatendencia','der','Megatrends','n'],
  ['dieZukunftsforschung','prospección','die','Zukunftsforschungen','n'],
  ['dieTrendanalyse','análisis de tendencias','die','Trendanalysen','n'],
  ['diePrognose','pronóstico','die','Prognosen','n'],
  ['dasSzenario','escenario','das','Szenarien','n'],
  ['dieVision','visión','die','Visionen','n'],
  ['dieStrategie','estrategia','die','Strategien','n'],
  ['diePlanung','planificación','die','Planungen','n'],
  ['dieUmsetzung','implementación','die','Umsetzungen','n'],
  ['dieEffizienz','eficiencia','die','Effizienzen','n'],
  ['dieOptimierung','optimización','die','Optimierungen','n'],
  ['dieProduktivität','productividad','die','Produktivitäten','n'],
  ['dieWettbewerbsfähigkeit','competitividad','die','Wettbewerbsfähigkeiten','n'],
  ['dieWertschöpfung','creación de valor','die','Wertschöpfungen','n'],
  ['dieKooperation','cooperación','die','Kooperationen','n'],
  ['diePartnerschaft','asociación','die','Partnerschaften','n'],
  ['dasNetzwerk','red','das','Netzwerke','n'],
  ['dieSynergie','sinergia','die','Synergien','n'],
  ['dasÖkosystem','ecosistema','das','Ökosysteme','n'],
  ['dieInfrastruktur','infraestructura','die','Infrastrukturen','n'],
  ['diePlattform','plataforma','die','Plattformen','n'],
  ['dieSchnittstelle','interfaz','die','Schnittstellen','n'],
  ['dieIntegration','integración','die','Integrationen','n'],
  ['dieKompatibilität','compatibilidad','die','Kompatibilitäten','n'],
  ['dieInteroperabilität','interoperabilidad','die','Interoperabilitäten','n'],
  ['dieSkalierbarkeit','escalabilidad','die','Skalierbarkeiten','n'],
  ['dieFlexibilität','flexibilidad','die','Flexibilitäten','n'],
  ['dieAgilität','agilidad','die','Agilitäten','n'],
  ['dieResilienz','resiliencia','die','Resilienzen','n'],
  ['dieAnpassungsfähigkeit','adaptabilidad','die','Anpassungsfähigkeiten','n'],
  ['dieLernfähigkeit','capacidad de aprendizaje','die','Lernfähigkeiten','n'],
  ['dieProblemlösung','resolución de problemas','die','Problemlösungen','n'],
  ['dasKritischeDenken','pensamiento crítico','das','KritischesDenken','n'],
  ['dieKreativität','creatividad','die','Kreativitäten','n'],
  ['dieKommunikation','comunicación','die','Kommunikationen','n'],
  ['dieZusammenarbeit','colaboración','die','Zusammenarbeiten','n'],
  ['dieTeamarbeit','trabajo en equipo','die','Teamarbeiten','n'],
  ['dieFührung','liderazgo','die','Führungen','n'],
  ['dasManagement','gestión','das','Managementarten','n'],
  ['dieOrganisation','organización','die','Organisationen','n'],
  ['dieProzessoptimierung','optimización de procesos','die','Prozessoptimierungen','n'],
  ['dasQualitätsmanagement','gestión de calidad','das','Qualitätsmanagementarten','n'],
  ['dieRisikobewertung','evaluación de riesgos','die','Risikobewertungen','n'],
  ['dieKennzahl','indicador','die','Kennzahlen','n'],
  ['derMeilenstein','hito','der','Meilensteine','n'],
  ['dieBenchmark','punto de referencia','die','Benchmarks','n'],
  ['dasDashboard','tablero de control','das','Dashboards','n'],
  ['dasReporting','informe','das','Reportings','n'],
  ['dieAuswertung','evaluación','die','Auswertungen','n'],
  ['dieStatistik','estadística','die','Statistiken','n'],
  ['dieVisualisierung','visualización','die','Visualisierungen','n'],
  ['diePräsentation','presentación','die','Präsentationen','n'],
  ['dasStorytelling','narración de historias','das','Storytellings','n'],
  ['dieKultur','cultura','die','Kulturen','n'],
  ['dieDiversität','diversidad','die','Diversitäten','n'],
  ['dieInklusion','inclusión','die','Inklusionen','n'],
  ['dasWohlbefinden','bienestar','das','Wohlbefinden','n'],
  ['dieWorkLifeBalance','conciliación','die','WorkLifeBalancen','n'],
  ['dieGesundheit','salud','die','Gesundheiten','n'],
];

const NIVELES_ORDER = ['A1.1','A1.2','A1.3','A1.4','A2.1','A2.2','A2.3','A2.4',
                       'B1.1','B1.2','B1.3','B1.4','B2.1','B2.2','B2.3','B2.4',
                       'C1.1','C1.2'];

// Generate code
function generateCode() {
  let code = '';
  let total = 0;

  for (const level of NIVELES_ORDER) {
    const words = W6[level] || [];
    if (words.length === 0) continue;

    code += `addLevel('${level}', [\n`;
    for (const w of words) {
      code += `  ['${w[0]}','${w[1]}','${w[2]}','${w[3]}','${w[4]}'],\n`;
      total++;
    }
    code += ']);\n\n';
  }

  return { code, total };
}

// Main
console.log('=== VOCAB WAVE6: Generar ~2,400+ palabras ===\n');

const { code, total } = generateCode();
console.log(`Palabras generadas: ${total}`);

// Write output
const OUTPUT = path.join(__dirname, 'vocab_wave6.jsx');
fs.writeFileSync(OUTPUT, code, 'utf8');
console.log(`Archivo: ${OUTPUT}`);

// Inject into rutaHelpers.jsx (before MULLER_RUTA_LEVELS)
console.log('\n=== Inyectando en rutaHelpers.jsx ===');
const rutaContent = fs.readFileSync(RUTA_FILE, 'utf8');
const insertPoint = rutaContent.indexOf('MULLER_RUTA_LEVELS =');

if (insertPoint < 0) {
  console.error('ERROR: No se encontró MULLER_RUTA_LEVELS =');
  process.exit(1);
}

const before = rutaContent.substring(0, insertPoint);
const after = rutaContent.substring(insertPoint);

const injection = `
// ═══════════════════════════════════════════════════════════════════
// VOCABULARIO WAVE6 (${total} palabras nuevas - temático completo)
// ═══════════════════════════════════════════════════════════════════
${code}
// ═══════════════════════════════════════════════════════════════════
// FIN WAVE6
// ═══════════════════════════════════════════════════════════════════

`;

fs.writeFileSync(RUTA_FILE, before + injection + after, 'utf8');
console.log('✓ Inyectado exitosamente');

// Verify
const finalContent = fs.readFileSync(RUTA_FILE, 'utf8');
const totalWords = (finalContent.match(/\['([^']+)'/g) || []).length;
console.log(`\nTotal palabras en archivo ahora: ${totalWords}`);